### ISSUE TITLE
Change picture hash in URL while slideshow

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/apps#1130]
Change the hash in the URL, each time a new picture is shown in the slideshow. Currently the hash represents the starting picture and doesn't change while the slideshow is running.

See #1123

**Comment by AbdealiJK** [comment]
Shouldn't this issue be closed ? It's pretty old, has a PR and the code is not even in this repo anymore.

**Comment by MorrisJobke** [comment]
Yes. Closing
