### ISSUE TITLE
Show share on hover over gallery

### ISSUE THREAD

**Issue by butonic** [owncloud/apps#1136]
There is a difference in how the share dialog is opened in the files app and in the gallery. In the files app the share button is only shown once you entered an album. In the files app the button is shown when hovering over a file. Shouldn't it be the same in the gallery? Hovering over an album should show a share icon in the bottom-right corner of the album?

@jancborchardt @icewind1991 @MTGap opinions?

**Comment by jancborchardt** [comment]
Any enhancement should be done to https://github.com/owncloud/galleryplus

cc @oparoz as a note for easier sharing here.
