### ISSUE TITLE
image app: folder preview is not updating on deletion of images

### ISSUE THREAD

**Issue by xhiena** [owncloud/apps#1137]
In the images app if you have a folder with photos the preview of the fotos, with 2 images you can see one when you are over left side of the folder and the other on the right side.

### Expected behaviour
When you delete one image of the folder, the preview of the folder is refreshed

### Actual behaviour
Preview is not refreshed, showing deleted images

### Steps to reproduce
1. create a folder
2. upload 2 images
3. go to images app, You can see a folder and if you enter shows 2 images. and in the folder preview you can see the 2 images by moving the mouse from left side to rigth.
4. go to files and delete one image
5. go to images app and in the preview are the two images and if you enter you see only one image

### Server configuration
Operating system: CentOS release 5.9 (Final)

Web server: Server version: Apache/2.2.22 (Unix)

Database: Mysql 5.1.58

PHP version: PHP 5.3.24

ownCloud version: ownCloud 5.0.6

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the gallery repo
