### ISSUE TITLE
Re-Sharing rights are not properly checked within Gallery App

### ISSUE THREAD

**Issue by BitdiddleDe** [owncloud/apps#1150]
Sharing galleries works here as described (share the files, the invited user just sees the shared folders; share within the gallery, the invited users also sees the gallery itself)

I wanted to avoid re-sharing of the shares (files as gallery), so i disabled the rights for the shared user (all items, in special "reshare").

When logging in as the invited users, this one cannot re-share the files (as expected, message "reshare not allowed"), but he /can/ reshare the galleries (which i did not expect). Is this the specified behaviour?

(OC5.0.7 on CentOS)

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the gallery app
