### ISSUE TITLE
Better focus for text files

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/apps#1154]
We should make the text editor not replace the files list when a document is clicked. This is confusing and makes you not sure where you are right now.

Instead it should be more lightbox style: dark background, almost opaque, similar to the pictures viewer in the Pictures app. That way you have feedback that you are still in the folder, and the focus is on the text, without the top bar and sidebar and that in the way.

@icewind1991 is that pictures viewer a general-purpose library? We should use it to show other file types too: text documents (this issue), PDF, Videos etc.

cc @ŧomneedham @owncloud/designers

**Comment by tomneedham** [comment]
Implemented
