### ISSUE TITLE
Integrate FreeIPA support for LDAP app

### ISSUE THREAD

**Issue by djasa** [owncloud/apps#1185]
FreeIPA (http://freeipa.org) uses flat fixed directory tree structure. This could be leveraged by owncloud app to make hooking up owncloud for use with freeipa way easier (based on my brief experience and not-so-deep insight):
what need to be entered by admin:
* directory server UI (e.g. ldaps://freeipa.example.com)
* base dn (e.g. dc=example,dc=com)
* owncloud user UID and password

what can user_ldap guess automagically:
* owncloud user DN: uid=%owncloud_uid,cn=sysaccounts,cn=etc,%base_dn
* user login filter: uid=%uid (+ any additional restriction)
* user list filter: objectClass=person (+ any other restriction)
* group list filter: not sure about these as FreeIPA has more kinds of groups, but "objectClass=posixgroup" may be a good choice as well
* base user tree: cn=users,cn=accounts,%base_dn
* base group tree: cn=groups,cn=accounts,%base_dn
* user display name field: displayName
* group display name field: cn
* email field: mail

What could be done to improve experience:
* let admin enter just ipa domain, crate base DN out of it and fetch freeipa server FQDN from _ldap._tcp.%domain SRV records
* hide user login/list filters, fetch group entries, create a (collapsible?) tree out of them where admin can select which groups can access ownclouds & generate appropriate filter strings out of them
* if home-on-nfs is used in freeipa, owncloud could probably have a subdirectory there 

Similar integration could be done for AD as well.

**Comment by blizzz** [comment]
There were some compatibility fixes here: https://github.com/owncloud/core/pull/7823

If there are still issues, pleaes report in core repository: https://github.com/owncloud/core/issues
