### ISSUE TITLE
calendar: send invitations

### ISSUE THREAD

**Issue by mbiebl** [owncloud/apps#1191]
I'm using an Android Phone with ownCloud as backend and CalDAV Sync as sync adapter.

When creating events where you want to invite users or change the status of existing events, the ownCloud calendar app should provide a function to send emails to the relevant parties.

https://code.google.com/p/sabredav/wiki/IMipHandler might be relevant.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
