### ISSUE TITLE
calendar: sharing calendars

### ISSUE THREAD

**Issue by mbiebl** [owncloud/apps#1192]
Version: 5.0.7

In Version 4.0.x I could share calendars via an URL by using the publish checkbox.
In 5.x that is no longer possible. I can only share a calendar with other owncloud users.

I also want to mention, that I found the UI/dialogs in 4.0.x to edit/share calendars better structured and more intuitive.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
