### ISSUE TITLE
Sharing issue

### ISSUE THREAD

**Issue by romris** [owncloud/apps#1204]
Sharing events is not really possible. Ways to reproduce:

Create an event and submit. 
Click on this event and try to share it with someone (full rights) and submit again. 
Open the event again and you will see that the assigned person can only share the event. (Expected: full rights again)
Try to change the permission to full rights again and you will see that the assigned person will disappear. (Expected: full rights assignment)

Thrown errors:
Fatal  PHP  Setting permissions for 46 failed, because item was not found at /var/www/owncloud/lib/public/share.php#705

Error  OCP\Share  Setting permissions for 47 failed, because the item was not found

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
