### ISSUE TITLE
Slideshow: small images should not scale up

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/apps#1268]
Checking out icons or smaller images, they are scaled up to fit the screen. This is very annoying especially for icons.

Instead, the behaviour for graphics should be:
* if larger than the screen, fit the longest side to the screen.
* if smaller than the screen, show in original size.

Can you look into this @butonic or @icewind1991?

**Comment by jancborchardt** [comment]
This has been fixed since a long time. I assume this is also not happening in Gallery+ @oparoz?

**Comment by LukasReschke** [comment]
I'm sure if Gallery+ does not do this GalleryDeluxe might be able to do. If not there is place for another Gallery app! :speak_no_evil:

**Comment by oparoz** [comment]
@jancborchardt - I'm allowing some upscaling for very small images like icons so that they don't end up being tiny in the middle of the screen, but the user can easily make them fill the screen or see the original size.

**Comment by oparoz** [comment]
And laugh all you want @LukasReschke, I'm sure one day you'll be glad to be able to pick one Gallery app which fits your needs ;)

**Comment by jancborchardt** [comment]
@oparoz hehehe – ok, sounds good. I’ll check it out. If there’s too much crazy UI involved we might need to talk about that, but good thoughts.
