### ISSUE TITLE
Realtime anti-virus scanner doesn't remove infected file on WebDAV client

### ISSUE THREAD

**Issue by daviddst** [owncloud/apps#1271]
Hi,

There is a problem with Antivirus App for files 0.4 and WebDAV client (OwnCloud Windows 1.3.0) with OwnCloud 5.0.9.

1) When we upload an infected file through the WebDAV client, the file is immediately detected/removed on server side, but not on client side. So, the client try to upload the file every 30 sec again and again until the file is removed from client side.

2) The background scanner (run every 1 hour) work correctly, it remove the infected file on server side AND client side, BUT it doesn't notify the user that a infected file has been detected/removed.

Regards,

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the antivirus repo
