### ISSUE TITLE
index .doc files (binary Word 97–2003)

### ISSUE THREAD

**Issue by butonic** [owncloud/apps#1292]
we do not yet support .doc files (binary Word 97–2003).
a hack was posted on stackoverflow: http://stackoverflow.com/a/265017/828717 and
http://www.dannyherran.com/2011/02/read-word-documents-with-php-up-to-word-2003/

official MS documentation: http://msdn.microsoft.com/en-us/library/gg615596(v=office.14).aspx#UnderstandMS_DOC_ExtractText

followup to https://github.com/owncloud/core/issues/162

**Comment by duongtannhu** [comment]
It's been 2 years. Do you have any update? Or do you have plan to make this enhancement (to support office 2003 files)?

Thank you.

**Comment by VicDeo** [comment]
Moved to search_lucene repo
