### ISSUE TITLE
Encoding issue in media server

### ISSUE THREAD

**Issue by sassrobi** [owncloud/apps#1293]
If I want to play music with Tomahawk or Amarok, the song titles are seems strange (like bad encoding) escpecially the non-ascii chars like öüóőúéáűí etc. In the web player it seems good, and the music playback is working in both situations.
Example:
in the file's ID3 (and in web player): "Még közelebb"
in Tomahawk: "MÃ©g kÃ¶zelebb"

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the music repo
