### ISSUE TITLE
Dependencies missing (ubuntu 12.04LTS)

### ISSUE THREAD

**Issue by xhoy** [owncloud/apps#1307]
Hi, 

Don't know if this is the right location for this bug so let me know :)

I just installed OwnCloud 5.0.10 on ubuntu via the repository's,
i added the External storage support 0.2 app.

for installation i used the: deb http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_12.10/ /
 repository.

Now the problem, After installing, on a clean machine. there where 2 dependencies missing:

1) sendmail (I got an error when sending an invite)
2) the dropbox couldn't work because it was missing php5-curl

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the core repo
