### ISSUE TITLE
Manage External Authentication

### ISSUE THREAD

**Issue by drsbaitso** [owncloud/apps#1316]
### Expected behaviour
I use IMAP to authenticate my users, and there doesn't seem to be a way to manage the storage space, or to disable / disallow one user access.

I can create the user manually and then modify the quota, but it would be really nice for the user to be auto-created. Also, the password option should be disabled and it should notify you with maybe an I for IMAP or L for LDAP, or whatever. Then allow me to disable that account or change the quota.

Even more management could be to not allow any new accounts until I specify. For instance, even though I have 500 IMAP users, I only want 3 being allowed to use it... or all but 10, so I can disable those manually.

### Actual behaviour
I can't manage the users without manually adding each user.

### Steps to reproduce
1. Use external authentication.
2. Try to set a quota on those users without manually adding each one.
3. 

### Server configuration
Operating system: Debian

Web server: Apache

Database: MySQL

PHP version: 5.4 or something, doesn't really matter

ownCloud version: 5.0.10

### Client configuration
Browser: Any

Operating system: Any

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

I didn't attach logs, cause they shouldn't be necessary.  The users aren't created, it's not a bug, it's probably just a feature request.

**Comment by blizzz** [comment]
This should work at least since OC 7 (just by looking at the code). Please reopen if it does not.
