### ISSUE TITLE
Encrypted file cannot be changed via WebDAV from two different clients

### ISSUE THREAD

**Issue by Pazu** [owncloud/apps#1344]
If a file is created via WebDAV on an ownCloud instance with the encryption app enabled, then subsequently edited on another machine via WebDAV, the file is corrupted (presumably non-unencryptable).

Client 1: Mac OS X 10.8.4
DAV client: Finder 10.8.3

Client 2: Windows 7 Enterprise Service Pack 1
DAV client: Windows Explorer

Server:
ownCloud 5.0.10
Apache version 2.2.24
PHP version 5.3.25
MySQL version 5.1.70-cll
Architecture x86_64
Operating system linux

Steps to reproduce:
1. Open an application (LibreOffice Calc 4.0.4.2 in my case) on client 1
2. Create a new spreadsheet
3. Save as "test.ods" on ownCloud mounted via WebDAV
4. Open spreadsheet on client 2 via WebDAV
5. Change something, save, and close
6. Attempt to open file on client 1 and file is now corrupt. File is also corrupt via WebDAV on client 2.

**Comment by PVince81** [comment]
Please try again with a recent ownCloud version, best is 8.2.2.
Many issues have been fixed since.

If you still have this issue, please raise it in owncloud/core.
Thanks
