### ISSUE TITLE
Video Playback in provided Viewer seems buggy?

### ISSUE THREAD

**Issue by rcmaples** [owncloud/apps#1348]
I have uploaded a few .mp4 files to test video playback functionality on a new server. So far, it seems that the provided video playback functionality doesn't work properly.
Server Specs:
Ubuntu 13.04 x64
PHP 5.4.9
Apache 2
ownCloud 5.0.10

Video Specs:
H.264 codec video
AAC codec audio

I can get the videos to play in the pop up viewer in Firefox (Win 7 and OS X) only.
Safari (for OS X), IE 9, and Chrome (Win 7 & OSX) just show the loading spinner indefinitely with no indication as to a possible error.

The videos download and play correctly in the iOS app.

Other possibly useful info:
ffmpeg, php5-ffmpeg, vlc, and ubuntu-restricted-extras, have all been installed on the server. I did not use apt-get to install owncloud.

I've tried adding mime types, but can't seem to find the right configuration. Seems like a bug?
Update: If a video is played in a new IE session, it will play correctly. After the first video is viewed in IE, no other videos may be viewed until IE has been closed and reopened.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the videos repo
