### ISSUE TITLE
External Storage: local files not shown

### ISSUE THREAD

**Issue by monreal** [owncloud/apps#1353]
### Expected behaviour
After mounting external local storage, the files already in the directory should show up in the web UI.

### Actual behaviour
I mounted a local folder which the apache process has proper rights to and already has a number of files and folders in it. It displays the contained folder ("AC-DC", see log below) but not the files inside. However, I am able to upload and create files/directories using the web UI just file and they end up in the external directory.

### Steps to reproduce
1. mount local external directory with files
2. try to reach files in web UI

### Server configuration
Operating system: CentOS 6.4

Web server: apache httpd 2.2.15

Database: sqlite 3.6.20

PHP version: 5.3.3

ownCloud version: 5.0.10

### Client configuration
Browser: firefox 24

Operating system: fedora 19

#### Web server error log
[Sun Sep 01 03:44:15 2013] [notice] Apache/2.2.15 (Unix) PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips configured -- resuming normal operations
which: no smbclient in (/sbin:/usr/sbin:/bin:/usr/bin)
which: no smbclient in (/sbin:/usr/sbin:/bin:/usr/bin)
which: no smbclient in (/sbin:/usr/sbin:/bin:/usr/bin)

=> this also shows up in the web UI but I guess it is not relevant

#### ownCloud log (data/owncloud.log)

# cat owncloud.log | grep music
{"app":"PHP","message":"filesize(): stat failed for \/srv\/music\/test at \/home\/www\/owncloud\/lib\/files\/storage\/local.php#74","level":2,"time":"2013-08-31T14:52:47+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/srv\/music\/AC-DC\/test at \/home\/www\/owncloud\/lib\/files\/storage\/local.php#74","level":2,"time":"2013-08-31T14:53:17+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/srv\/music\/Airbourne at \/home\/www\/owncloud\/lib\/files\/storage\/local.php#74","level":2,"time":"2013-08-31T20:57:44+00:00"}
{"app":"PHP","message":"filesize(): stat failed for \/srv\/music\/Airbourne\/Airbourne - Runnin' Wild [Special Edition] - 13 - Dirty Angel.mp3 at \/home\/www\/owncloud\/lib\/files\/storage\/local.php#74","level":2,"time":"2013-08-31T21:02:27+00:00"}

=> the "test" and Airbourne files were created/uploaded by me, there are however other files inside "AC-DC" which do not show up.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the core repo
