### ISSUE TITLE
Copy with middle button from text editor doesn't work

### ISSUE THREAD

**Issue by ghost** [owncloud/apps#1363]
Hi,
I'm unable to copy some text out from ownCloud text editor (the one that opens when clicking some text file) using middle mouse button. I'm using ownCloud version 5.0.10 and Firefox 23.0 and Opera 12.16 on Fedora 19. Copy with middle click doesn't work neither in Firefox nor Opera. Copy with ctrl+c/v does work.
Is anybody else facing this issue? Is it bug or development decision to not support that?
Thanks,
mbartos

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the texteditor repo
