### ISSUE TITLE
Thumbnails in overview image for a gallery not updated on image delete

### ISSUE THREAD

**Issue by 4ZM** [owncloud/apps#1365]
Images are used to create the gallery overview image in Pictures. On mouse over the image changes and scrolls through the different image thumbnails in the gallery.

If one image is removed from the gallery, by removing it from the folder in Files, it is still visible in the scrolling gallery overview image. I.e. there is no way to remove an image from the scrolling overview image.

A workaround to refresh / re-generate the overview image would be appreciated.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the gallery repo
