### ISSUE TITLE
Show who is sharing in Files

### ISSUE THREAD

**Issue by 4ZM** [owncloud/apps#1366]
In the gallery you see who is sharing. This is particularly use full if two people have the same name for a folder / gallery they are sharing.

In the Files this doesn't work. I guess the feature is missing?

Two different shared folders with the same name will get a (n) decoration to the file name in Files and no reference to the user sharing the files is made. It would be nice to have it like it is for Pictures.

**Comment by jancborchardt** [comment]
This is fixed since some time ago – in the Files list you will see the name of the sharer next to the sharing icon.
