### ISSUE TITLE
[Activity] design issues

### ISSUE THREAD

**Issue by Kondou-ger** [owncloud/apps#1373]
![screenshot423](https://f.cloud.github.com/assets/1410802/1143436/e0d7d448-1d3c-11e3-9725-15aa1b3f905f.png)

- [ ] Long foldernames, trolling as usually. Toyed around a bit with `text-overflow: ellipsis` and `overflow:hidden` but couldn't fix this.
- [ ] No icons for folders (or anything) doesn't look really nice. Just show a generic folder-icon. Would be way better.
- [x] The RSS-Feed button is a bit to small (the font is barely readable), and adding a RSS-Icon would make it better, too.

@karlitschek @jancborchardt @kabum @Raydiation

**Comment by jancborchardt** [comment]
This was fixed since a long time ago (ownCloud 7 or so) with the new look of the Activity app. Cheers! :)
