### ISSUE TITLE
All file actions should be available in the file detail view as well

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/apps#1381]
Currently it’s not possible to e.g. share a picture when you loop through it in the slideshow. You need to switch back to the list.

Acting on a file should be possible from that view though too, not only from the list. Probably best place these actions centered below the file / image. Show the name and »Rename« next to it, Share as well, the ability to Download and maybe versions as well. That’s it.

cc @MTRichards @butonic @DeepDiver1975 @karlitschek

**Comment by jancborchardt** [comment]
@oparoz Sharing and deleting is available in Gallery+, right? If so we can safely close this. :) (Sorry, I need to get around to properly test Gallery+ again – https://github.com/owncloud/galleryplus/pull/139 unfortunately is a stupid prevention for that ;)

**Comment by oparoz** [comment]
Not an excuse, just use the proper branch! :P 

The share button is tracked here: https://github.com/owncloud/galleryplus/issues/68
Maybe worth opening a separate issue which includes all Files action

**Comment by jancborchardt** [comment]
Fine by me, closing in favor of https://github.com/owncloud/galleryplus/issues/68 then :)
