### ISSUE TITLE
[Pictures]: Having too many pictures makes the app abort without displaying an error

### ISSUE THREAD

**Issue by gwolf** [owncloud/apps#1383]
I am trying to set up an Owncloud instance with a directory with a very large amount of pictures (~35GB, over 20,000 individual files). 

### Expected behaviour
Either the app should work correctly (displaying the pictures by hierarchy, as it happens with less files available — I tried it with only ~5000 pictures and it worked fine), or it should display an error message explaining what happened.

### Actual behaviour
Once the ~20,000 pictures are uploaded, I click on the "Pictures" icon, and am greeted by a completely blank screen. After some seconds, he log file shows:

{"app":"PHP","message":"Allowed memory size of 94371840 bytes exhausted (tried to allocate 82 bytes) at \/home\/gw_owncloud\/cloud\/lib\/files\/view.php#963","level":4,"time":1380132621}

### Steps to reproduce
1. Upload a large amount of photos to OwnCloud (I did this by copying over a directory straight to data/[user]/files/, not by the OwnCloud interface)
2. Click on "Pictures"
3. Look at a blank, unwelcoming screen

### Server configuration
I am running my OwnCloud instance in a shared hosting environment (Dreamhost).

Operating system: Debian Linux (6.0.6)

Web server: Apache2

Database: MySQL

PHP version: 5.4 

ownCloud version: 5.0.9

### Client configuration
Browser: Both Firefox and Chromium

Operating system: Debian Linux (unstable)

#### Web server error log
```
Insert your webserver log here
```
No error is logged.

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
"app":"PHP","message":"Allowed memory size of 94371840 bytes exhausted (tried to allocate 82 bytes) at \/home\/gw_owncloud\/cloud\/lib\/files\/view.php#963","level":4,"time":1380132621

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
No error that I could find

**Comment by PVince81** [comment]
Please try again with 8.0.5.
Also the galleryplus app might fix the scalability issue too. CC @oparoz

**Comment by oparoz** [comment]
@gwolf - Gallery+ (for 8.0 and 8.1) is here: https://apps.owncloud.com/content/show.php/Gallery?content=169116.

Don't hesitate to report problems here: https://github.com/owncloud/gallery/issues

**Comment by gwolf** [comment]
Thanks - I have to get some time in my hands to upgrade my server and test; meanwhile, I'll gladly accept this to be marked as "closed". Will reopen in the unlikely case it's needed.
