### ISSUE TITLE
Ampache Client can't play more than 2 songs

### ISSUE THREAD

**Issue by edwardslabs** [owncloud/apps#1390]
## Details
I am using nginx, mysql 5, php5-fpm and owncloud 5.0.11

## Behavior
Ampache clients are able to connect to the service and after approx. 2 songs ~5 minutes. No more music will play until the client is restarted.

I have tested this behavior on Amarok (Windows 7), AmpacheX (iOS), and iAmpache(iOS).

## Expected Behavior

Music will be able to play through an ampache client as long as the listener desires limited by network and power of course.

## Workaround

apps/media/lib/ampache.php contains two important time values. The first is the timeout between renewing credentials this is originally set to 10 minutes. I reduced this value to 5 minutes. 

Also on line 98 $interval is set for 10 minutes. This is the amount of time before expired credentials are removed from the database. Increasing this value will allow an Ampache client to connect for the duration of the $interval but after $interval is expired the client will no longer connect. 

It seems that the DB query on line 102 is nuking the active session and after that is nuked the client can no longer retrieve the next song.

**Comment by PVince81** [comment]
@MorrisJobke obsolete ?

**Comment by MorrisJobke** [comment]
I didn't have seen this with the new ampache API.
