### ISSUE TITLE
Google Drive External Storage not working

### ISSUE THREAD

**Issue by ziris** [owncloud/apps#1391]
When I attempt to set up Google Drive in the External Storage app, I get directed to the Google site, but am only presented with an error:

Error: invalid_client

I am filling in the fields in my users (who is not an admin) Personal section as such:

Folder Name: GoogleDrive
External Storage: Google Drive
Client ID: email_address@gmail.com
Client secret: (password to above email address)

I have been trying to search around to see if perhaps I am incorrectly attempting to set this up, but have not found any information. I am using the latest version of Owncloud I could download (5.0.11).

It seems pretty straightforward, so I don't believe I am doing anything wrong. Is this is a bug/known issue, or am I perhaps attempting to set this up incorrectly?

Let me know if you need/would like more information.
# 

EDIT:

Ok, so apparently you have to go in to Google API's and set up a "Client ID for web applications" thing to get the info you need. I went through and set that up, and am able to grant access to my account. However, when I try to browse my files on the account, all I am greeted with is a white page. It is only when I disable the "External storage support" app as my admin user that I am once again able to view my files as the user. I am seeing this error thrown in the error logs:

Fatal   PHP     Error calling GET https://www.googleapis.com/drive/v2/files/root: (403) Access Not Configured at /var/www/owncloud/apps/files_external/3rdparty/google-api-php-client/src/io/Google_REST.php#66

I suppose I'll keep working at it.

**Comment by Amalinda** [comment]
@ziris  can you please elaborate your steps? i stil have some problems.
