### ISSUE TITLE
using external storage, openstack swift, subfolders create additional containers rather than just objects

### ISSUE THREAD

**Issue by idallas** [owncloud/apps#1413]
### Expected behavior
Folders created within a mount with a specified Swift container should be created as objects rather than as containers, modeling a filesystem path.  This is how own cloud works with S3 connections already.

### Actual behavior
Folders created within Swift mounts create new containers with a form like ORIGINAL_CONTAINER\NewFolder\NewSubFolder.  You end up with a lot of separate containers if people create a large hierarchy of folders.

OwnCloud itself still seems to work fine and this will probably not present a problem for relatively small numbers of containers.  Performance with large numbers of containers will likely be slow.

### Steps to reproduce
1. Mount a swift container into own cloud named "testcontainer"
2. Create a folder named "testfolder" in the owncloud Files app under that mounted swift container.
3. Browse the swift object store with Cyberduck or another swift client.
4. You'll see an additional container was created for the new folder you created.  It'll be named "testcontainer\testfolder".

### Server configuration
Operating system: Debian Linux 6.0

Web server: Apache 2.2

Database: MySQL

PHP version: 5.3

ownCloud version: 5.0.12

**Comment by DeepDiver1975** [comment]
Please reopen in core repo is still valid - THX
