### ISSUE TITLE
files_texteditor / php / Safari

### ISSUE THREAD

**Issue by kolella** [owncloud/apps#1441]
Hi,

this just to inform that i had to edit files_texteditor/js/editor.js adding following line (after line 220)

aceEditor.getSession().setUseWorker(false);

in order to make editing of .php files in Safari (5.1.10 OS X 10.6.8) work. 

Owncloud version 5.0.12

regards

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the texteditor repo
