### ISSUE TITLE
Trying to save bookmark edits causes internal server error 500

### ISSUE THREAD

**Issue by sthag** [owncloud/apps#1444]
I'm on Owncloud 5.0.12 and use Googles Chrome 30.

I imported bookmarks from an html file.
I open a bookmark to edit.
I change some vaulues of the bookmark.
I click on save.
The bookmark isn't saved and I get the displayed error.

_Image removed_

```
POST 500 (Internal Server Error)
send
f.extend.ajax
submitBokkmark
f.event.dispatch
h.handle.i
```

Is it me or is it the system?

By
sthag

**Comment by PVince81** [comment]
Closing as duplicate.
Also OC 5 is end of life. Please upgrade.
