### ISSUE TITLE
[Gallery] Add file actions like rename and delete

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#1487]
To make it easier to triage pictures (which might have been uploaded with the instant upload of the mobile clients), it would be nice to have the following actions:
1) Delete picture
2) Rename picture
3) Move picture by dragging to parent / subalbum

For 1) and 2) icons could appear when hovering on a picture thumbnail.

CC @owncloud/designers

**Comment by jancborchardt** [comment]
I’m pretty sure these actions (at least delete) are available in the Gallery+ https://github.com/owncloud/galleryplus – which we should focus our efforts on cc @oparoz :) (Closing this, any issues should be opened in the Gallery+ repo)

**Comment by oparoz** [comment]
None of these are implemented, but the menu item is tracked here: https://github.com/owncloud/galleryplus/issues/39

**Comment by jancborchardt** [comment]
Great stuff!
