### ISSUE TITLE
Picture/Gallery App doe snot show a single picture.

### ISSUE THREAD

**Issue by mwaeckerlin** [owncloud/apps#1489]
There ist no picture in the gallery, the galley-tab is completely blank. In my OwnCloud, I have >50.000 Image files (mostly jpg). Not a single one is shown. It used to work in older 5.x releases, but since some time, nothing appears any more.

There should be a rescan button.

Except some few images that are stored in owncloud folders (instantUpload and clientsync), all my pictures are in a local external storage. Not a single one of them is shown, neither those managed by owncloud, nor those on the external folder. (Background info: I store my pictures in boar version management [http://code.google.com/p/boar/], check them out to a folder and this folder is integrated as external storage into owncloud.)

How can I help you to debug?

Actually I'm using ownCloud 5.0.12+dfsg-1ubuntu1~saucy1 (Debian)

**Comment by PVince81** [comment]
Please try again with 7.0.7 or 8.0.5. The gallery app was optimized a bit for that amount of pics.
