### ISSUE TITLE
[Gallery] Swipe to next pic

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#1504]
Just tried the gallery app on the Nexus 7 tablet and it already looks great!

It would be nice if it was possible to swipe left/right to switch the picture.

- Simple approach: when the user finishes the swipe gesture, switch the pic (the pic doesn't follow the swipe). There are some libraries to detect gestures.

- Complex approach: when the user starts swiping, the picture follows the swipe (like on many image viewes on mobile)

This feature/code should only be enabled when touch support exists (can be detected with Modernizr). Note that some newer laptops might have touch screens as well, so not limited to mobile devices.

CC @owncloud/designers

**Comment by jancborchardt** [comment]
@oparoz is this possible in Gallery+? If so, we can close this. If not: Would indeed be good, and we should open an issue for it in the tracker. :)

**Comment by oparoz** [comment]
The request is there https://github.com/owncloud/galleryplus/issues/141
It's a matter of waiting for @libasys to port his solution :)

**Comment by jancborchardt** [comment]
@oparoz you can close this issue in favor of https://github.com/owncloud/galleryplus/issues/141 then as well ;)
