### ISSUE TITLE
Pictures: allow to share invidual pictures

### ISSUE THREAD

**Issue by mbiebl** [owncloud/apps#1509]
Version: 6.0 beta5

Atm, the only way to share pictures is by sharing each picture individually (not practical if you want to share a large set of pictures) or moving/copying the pictures into a single folder and sharing that folder.

It would be much nicer if in the Pictures app, I can select individual images and share them with a single link. E.g. dropbox does allow that in a nice way.

**Comment by DeepDiver1975** [comment]
Please reopen in gallery repo is still valid - THX

**Comment by mbiebl** [comment]
still valid, as a simple test shows
