### ISSUE TITLE
dropbox files not visible in subdirectory

### ISSUE THREAD

**Issue by moscicki** [owncloud/apps#1512]
Server 5.0.13 CE.
Client: web browser (chrome).

I setup and connected to my dropbox account successfully. This is my test account @ dropbox so I don't have sync clients running against it. I only uploaded a couple of files in dropbx

The files which I uploaded at the top level of dropbox are visible fine on owncloud side. 

Then I created a directory via owncloud web interface and this was propagated to dropbox ok. 
However I am getting this in the logs: 

{"app":"files_external","message":"Resource at uri: https:\/\/api.dropbox.com\/1\/metadata\/dropbox\/sth\/blah could not be found. Path '\/sth\/blah' not found\n","level":3,"time":"2013-11-24T14:33:21+00:00"}

When I added files to this directory on dropbox side are NOT visible on the owncloud side - they eventually become visible after a long while (or maybe that's triggered by something else?).

I also have this appearing in owncloud.log (not sure if that's for the same user though): 
{"app":"core","message":"Can't get cache storage, user not logged in","level":3,"time":"2013-11-24T14:45:19+00:00"}

Also, the browsing of Dropbox folder is kind-of-slowish. 

Does dropbox integration depend on owncloud cron tasks in the background?

**Comment by PVince81** [comment]
Are you still seeing this in 7.0.7 or 8.0.5 ?

**Comment by PVince81** [comment]
Please try again with recent ownClouds. Maybe Dropbox issues have been fixed since :smile:
