### ISSUE TITLE
dropbox mount - cannot create files (but I can create directories)

### ISSUE THREAD

**Issue by moscicki** [owncloud/apps#1513]
Same setup as for: https://github.com/owncloud/apps/issues/1512

I can create directories but I cannot create files in my owncloud Dropbox folder which is mounted to my Dropbox account (app access type: Full Dropbox).

Looks like a bug?

**Comment by PVince81** [comment]
Are you still seeing this in 7.0.7 or 8.0.5 ?

**Comment by PVince81** [comment]
Please try again with recent ownClouds. Maybe Dropbox issues have been fixed since :smile:
