### ISSUE TITLE
Ogg/flac file metadata extraction fail

### ISSUE THREAD

**Issue by Amgine0** [owncloud/apps#1514]
### Expected behaviour
Ogg file id3 tags (Artist, Album, Title) should be used to organize and display scanned music.

### Actual behaviour
All flac/ogg files are lumped under Unknown/Unknown sorted by file name.

### Steps to reproduce
1. Upload ogg or flac files with known good id3 tags
2. Rescan Collection
3. 

### Server configuration
Operating system:
Ubuntu 13.04
Web server: 
Apache2
Database:
MySQL
PHP version:
5.4.9
ownCloud version:
5.0.13
### Client configuration
Browser:
Various - FF/TBB/Midori/Safari/Fenec
Operating system:
Various - Darwin|Mac/Linux/Windows/BSD
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

I'm assuming you're aware of this issue, but don't see a public issue for it in the apps.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the music repo
