### ISSUE TITLE
Pictures: shared pictures show up twice

### ISSUE THREAD

**Issue by mbiebl** [owncloud/apps#1524]
Version: 6.0 RC1

When sharing a folder containing pictures, it shows up twice for the user it was shared with.

See attached screenshot as an example

![pictures-shared](https://f.cloud.github.com/assets/3609611/1641456/4d2c341a-5855-11e3-852c-0259a88cda3d.png)

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the gallery repo
