### ISSUE TITLE
Upgrade 6.0 to 6.0.0a

### ISSUE THREAD

**Issue by Ewoxx** [owncloud/apps#1569]
{"app":"updater","message":"Backup creation failed. Check permissions.","level":3,"time":"2013-12-19T19:58:47+00:00"}
{"app":"updater","message":"Unable copy \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/smb to \/var\/www\/html\/owncloud\/data\/updater_backup\/6.0.0.13-2166dde1\/apps\/files_external\/3rdparty\/smb","level":3,"time":"2013-12-19T19:58:48+00:00"}

Having some problems upgrading 6.0 to 6.0.0a. The log says:
{"app":"updater","message":"Backup creation failed. Check permissions.","level":3,"time":"2013-12-19T19:58:47+00:00"}
{"app":"updater","message":"Unable copy \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/smb to \/var\/www\/html\/owncloud\/data\/updater_backup\/6.0.0.13-2166dde1\/apps\/files_external\/3rdparty\/smb","level":3,"time":"2013-12-19T19:58:48+00:00"}

Found this in another bug but still same problem (executed in /var/www/html/owncloud)
find -type d -exec chmod 755 \{\} \;
find -type f -exec chmod 644 \{\} \;

**Comment by PVince81** [comment]
Any more luck with 6.0.9 or 7.0.7 ?
