### ISSUE TITLE
fluxx_compensator is incompatible with 6.0

### ISSUE THREAD

**Issue by ferdiga** [owncloud/apps#1577]
all admin forms do not save content
hovering over the file system items does not show the menu (share, ..)

had to move away the directory as the apps menu was not accessible any more

it was not obvious to clear the browser (chromium) cache to get things running again.
cleared all cookies of the site, closed browser, restart apache2,  closed tab (finally worked)

**Comment by PVince81** [comment]
Looks like this app was removed and unmaintained. Note that the app was likely to be using hacks to enhance the UI, which are not guaranteed to work in future versions of OC.
Closing.
