### ISSUE TITLE
activity refer to root dir although owncloud is not in root

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/apps#1588]
Owncloud 6.
I can see the following lines in my error.log
File does not exist: /myRootDir/core, referer: https://myDomainName.dk/owncloud/index.php/apps/activity

**Comment by PVince81** [comment]
Please try again with 6.0.9 or 7.0.7. Many activity issues have been fixed already.

If you still see the issue, please raise it in the owncloud/activity repository.
Thanks.
