### ISSUE TITLE
Real fullscreen for gallery

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/apps#1593]
Copied from owncloud/core#6531 by @stefan-niedermann

-----

Actual behaviour: Browser-Control- and URL-Bars are still visible
Expected behaviour:
The Image uses the javascript native fullscreen api instead of displaying the content only in the rendering-pane of the browser.
example: gallery at golem.de
http://www.golem.de/news/archos-70-xenon-7-zoll-tablet-mit-umts-fuer-140-euro-1312-103517.html
// Edit: changed example article because in the original was no gallery ;-)

var element = document.getElementById("#my-container");

if (element.requestFullScreen) {
element.requestFullScreen();
} else if (element.mozRequestFullScreen) {
element.mozRequestFullScreen();
} else if (element.webkitRequestFullScreen) {
element.webkitRequestFullScreen();
}

cc @owncloud/designers

**Comment by oparoz** [comment]
@stefan-niedermann - Try this version
https://github.com/interfasys/galleryplus
master or performance-fixes branch

It includes fullscreen (f) and zoom in/out (up/down, i/o)

**Comment by stefan-niedermann** [comment]
hm @DeepDiver1975 this issue was about the default included gallery app - why closing it? will this feature never be implemented?
even youtube uses the fullscreen mode.

> Normally all the browsers have fullscreen options themselves
Pressing F11 !== fullscreen for gallery picture
Pressing F11 === fullscreen for *browser*, that's a difference.

**Comment by jancborchardt** [comment]
@stefan-niedermann if it’s still relevant, please open it in the correct repository (of the Gallery app).

**Comment by stefan-niedermann** [comment]
Please. The third time i open this issue.
https://github.com/owncloud/gallery/issues/210
