### ISSUE TITLE
[OC6 Activity App] doesn't work in Outlook

### ISSUE THREAD

**Issue by ser72** [owncloud/apps#1606]
In the Activity tab go to RSS feed
Then select "Subscribe using Microsoft Outlook"
![capture](https://f.cloud.github.com/assets/5174383/1904062/80b6d980-7c8a-11e3-8ee9-c9ead5d420dc.PNG)

Press Subscribe

It brings up Microsoft outlook but nothing in the feed:

![capture1](https://f.cloud.github.com/assets/5174383/1904066/8ceefe3a-7c8a-11e3-8c51-22a4677fdd8a.PNG)

{"installed":"true","version":"6.0.0.14","versionstring":"6.0.0a","edition":"enterprise"}

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the acivity repo
