### ISSUE TITLE
[activity] accessing column that was not selected - Undefined index: messageparams

### ISSUE THREAD

**Issue by butonic** [owncloud/apps#1616]
Noticed this in the log of a friends OC6.0.0a installation: 
```json
{"app":"PHP","message":"Undefined index: messageparams at
\/...\/owncloud\/apps\/activity\/lib\/data.php#135","level":2,"time":"2014-01-17T15:14:56+00:00"}
```
activity is trying to access `messageparams` in https://github.com/owncloud/apps/blob/master/activity/lib/data.php#L135 but does not select that column in https://github.com/owncloud/apps/blob/master/activity/lib/data.php#L129

cc @karlitschek

**Comment by DeepDiver1975** [comment]
Please reopen in the activity repo if still valid - thx
