### ISSUE TITLE
[text editor] Changes not detected while saving, can't save afterwards

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#1618]
### Steps to reproduce
1. Setup ownCloud with sqlite for extra slowness
2. Create a text file over the web UI and edit it
3. Type in some text
4. Click save
5. While the editor is saving, type in some text but make sure to stop typing before it has finished saving
6. Click save again
### Expected result

Step 6 saves again
### Actual result

Can't save. Need to edit the file a bit to trigger "change detection", then the file can be changed again
### Versions

OC 6.0.0a
### More information

It looks like the "file is changed" flag is only cleared at the end of the saving process, which means that even if the text was changed in between while saving, that flag is still getting cleared at the end.

To fix this, we need to detect whether the user made further changes while saving, in which case the "file is changed" flag needs to be kept.

@tomneedham

**Comment by tomneedham** [comment]
Implemented
