### ISSUE TITLE
Gallery app: Allowed memory size of 536870912 bytes exhausted

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/apps#1634]
"Allowed memory size of 536870912 bytes exhausted"

I do know similar messages from MediaWiki, when ImageMagick is called in a new shell with insufficient amount of memory for that specific job (for experts: this is explained here https://www.mediawiki.org/wiki/Manual:$wgMaxShellMemory ), and ImageMagick eats up all (restricted) resources.

Can anyone assist, is there a similar variable in owncloud ?

**Comment by oparoz** [comment]
See https://github.com/owncloud/gallery/issues/23

**Comment by MorrisJobke** [comment]
Close because of the duplicate
