### ISSUE TITLE
file is not readable !!!

### ISSUE THREAD

**Issue by marcinplpl** [owncloud/apps#1675]
With some files have a errors like

Example log:

{"app":"OC\Files\Cache\Scanner","message":"!!! Path 'files\/Wydruki xxxx)\/arki Letnisko Sosnowa' is not readable !!!","level":0,"time":"2014-01-24T10:17:28+00:00"}

Should be: Żarki Letnisko, or like with other file files with unicode code. \uxxxx

Where is a problem? Owncloud 6.01, client 1.5.1 . Serwer linux debian with utf PL
client windows xp with windows1250 code page.

Best regards

**Comment by PVince81** [comment]
There is no problem, it's a bogus log entry that is irrelevant and has been removed in more recent versions.
Please upgrade.
