### ISSUE TITLE
Updater fails when working across mountpoints

### ISSUE THREAD

**Issue by torbennehmer** [owncloud/apps#1699]
Hi, my owncloud install is distributed between two mount points. One houses the webhome, temp dir and everything, while the second one is mounted at the data dir of owncloud:

When I try to launch the updater, it fails with the following errors:

Error - updater  
Unable to move /var/www/clients/client1/web27/web/3rdparty/Archive to /var/www/clients/client1/web27/private/updater_backup/tmp/3rdparty/Archive

Error - updater  
Something went wrong for 3rdparty. Rolling back.

Warning - PHP  
rename(/var/www/clients/client1/web27/web/3rdparty/Archive,/var/www/clients/client1/web27/private/updater_backup/tmp/3rdparty/Archive): Invalid cross-device link at /var/www/clients/client1/web27/web/apps/updater/lib/helper.php#27

Warning - PHP  
rename(): The first argument to copy() function cannot be a directory at /var/www/clients/client1/web27/web/apps/updater/lib/helper.php#27

**Comment by johenkel** [comment]
@VicDeo I am not sure why this is deemed closed as I am still running into the same problem.

Trying to upgrade from 7.0.3 to 8.1.3  .
Using the above app.php did not make any difference.

What is the status on that ?

Is there a way to change the backup folder in a config setting ?

**Comment by MorrisJobke** [comment]
> Trying to upgrade from 7.0.3 to 8.1.3 .

Update from 7.0.3 to 8.1.3 is not supported. Please upgrade in following way: 7.0.3 -> 8.0.8 ->8.1.3
