### ISSUE TITLE
updating from old install

### ISSUE THREAD

**Issue by regchan** [owncloud/apps#1715]
5.0.28 I think is current version at this time

ownCloud 6.0.2 is available. Get more information	 

Checking your installation...
Downloading package...
Creating backup...
Here is your backup: /services/webpages/r/e/regchan.co.uk/public/owncloud/data/updater_backup/5.0.28-c1d6adb1.zip
Moving files...
Update failed

The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by PVince81** [comment]
Closing due to lack of feedback.

Please try again with 7.0.7 or 8.0.5
