### ISSUE TITLE
External storage: Dropbox webhooks

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/apps#1812]
I'm posting this here as a reminder that [Dropbox announced webhooks](https://www.dropbox.com/developers/blog/90/announcing-dropbox-webhooks). It would be cool if ownCloud external storage could use this to sync with Dropbox.

**Comment by dhuyvetter** [comment]
They have webhooks now, got the option to set it up when creating a Dropbox app to connect to my ownCloud.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/10139
