### ISSUE TITLE
Add better description for file locking app

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#1822]
People might wonder what this new "File locking" app is, so would be good to have a description in the app info.

@DeepDiver1975 @icewind1991  @jnweiger

**Comment by DeepDiver1975** [comment]
@PVince81 is this sufficuent? https://github.com/owncloud/files_locking/blob/master/appinfo/info.xml#L8

**Comment by PVince81** [comment]
Yes, more than sufficient :wink:
