### ISSUE TITLE
Multiple caldav issue w/ Thunderbird 

### ISSUE THREAD

**Issue by drsbaitso** [owncloud/apps#1897]
### Steps to reproduce
1. Add two calendars to Thunderbird (different user and domain)
2. Try to sync
3.

### Expected behaviour
Sync both calendars

### Actual behaviour
One calendar syncs... the other gets a 404 error

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
7.0.1
**Updated from an older ownCloud or fresh install:**
updated from 6.x
**List of activated apps:**
calendar
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Thunderbird 31.x / lightning 3.3
**Operating system:**

#### Web server error log
```
    10.1.1.1 - - [19/Aug/2014:14:43:23 -0500] "PROPFIND /remote.php/caldav/calendars/user1@example.com/defaultcalendar/ HTTP/1.1" 401 1125 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - - [19/Aug/2014:14:43:23 -0500] "PROPFIND /remote.php/caldav/calendars/user1@otherexample.com/defaultcalendar/ HTTP/1.1" 401 1124 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - user1@otherexample.com [19/Aug/2014:14:43:23 -0500] "PROPFIND /remote.php/caldav/calendars/user1@otherexample.com/defaultcalendar/ HTTP/1.1" 207 2362 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - user1@example.com [19/Aug/2014:14:43:23 -0500] "PROPFIND /remote.php/caldav/calendars/user1@example.com/defaultcalendar/ HTTP/1.1" 207 2333 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - - [19/Aug/2014:14:43:23 -0500] "OPTIONS /remote.php/caldav/calendars/user1@otherexample.com/ HTTP/1.1" 200 1034 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - - [19/Aug/2014:14:43:23 -0500] "OPTIONS /remote.php/caldav/calendars/user1@example.com/ HTTP/1.1" 200 1034 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - user1@otherexample.com [19/Aug/2014:14:43:23 -0500] "PROPFIND /remote.php/caldav/calendars/user1@otherexample.com/defaultcalendar/ HTTP/1.1" 404 1012 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
    10.1.1.1 - user1@example.com [19/Aug/2014:14:43:23 -0500] "PROPFIND /remote.php/caldav/calendars/user1@example.com/defaultcalendar/ HTTP/1.1" 207 101574 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.0 Lightning/3.3"
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
CalDAV: Status 404 on initial PROPFIND for calendar ownCloud
```

I use IMAP as my auth backend.

If I use two calendars from the same domain, they work fine.  As soon as i do one calendar from domain1 and one from domain2, that's when this borks out.  Is it causing a conflict when it checks the login?

I've been trying to figure out if this is a Thunderbird issue, or an ownCloud / sabredav issue. I'm on the latest 7.0.1. I have two calendars that I sync up. If I disable calendar B, calendar A works but when I try to enable calendar B I get a 404 not found error. Do the reverse, restart Thunderbird, calendar B works, and A gets the 404 error. This worked with the last ownCloud v6.

I have the multi-realm config set in Thunderbird so that's not the issue.  And as you can see, it's requesting the correct calendar, ownCloud says not here.

**Comment by drsbaitso** [comment]
Actually I'm going to reopen this.

Just to summarize...

I use IMAP back end for user auth.  If I try to use Thunderbird / Lightning with two separate domains, I can only connect one of the calendars and the other one fails.

So I have a calendar connected as user@domain1
And a second calendar connected as user@domain2

In the latest 8.0.2 (this has happened ever since 7.x) the second calendar will not connect.  It gives a bunch of propfind 404 errors.

However, I just installed a test 6.0.7 OC instance, and I was able to connect to two calendars on two domains (using the same exact backend auth).

If someone wants to test this I can PM someone with some test login creds.

**Comment by RealRancor** [comment]
Have you concidered to report this to the bugtracker of lightning?

**Comment by drsbaitso** [comment]
No I haven't, but I guess I could.  I mean, the fact it worked in 6.x (and prev) and not in 7.x or 8.x made it seem more like an ownCloud issue as that's the only difference when testing.

I'll toss a bug report their way though.  Bugzilla... shivers....

**Comment by RealRancor** [comment]
Hi,

as OC itself can't cause a 404 (file not found) there are probably only two possibilities:

1. Lightning can't handle two different calendars with two different accounts and is accessing a complete wrong URL causing the 404

2. You're using a wrong URL for one of the calendars

Nr. 1 probably should be reported to their bugtracker. I think mozilla has the better knowledge of their product and how to debug it.

Nr. 2 can be tested via your browser by opening the calendar URL. See https://github.com/owncloud/documentation/pull/1025 for some pointers how to get the correct URL.

**Comment by drsbaitso** [comment]
Well, I know the URLs are right because if I disable calendar1, restart TB calendar2 works... and vice versa.  Also v6.x of OC works perfectly with both calendars.

I'll toss a bug report their way and see what's up.

**Comment by PVince81** [comment]
Please try again with 9.0.6 or 9.1.1. If the issue persists, please raise in owncloud/core
