### ISSUE TITLE
[6.0.5RC1] Antivirus app incompatible

### ISSUE THREAD

**Issue by ser72** [owncloud/apps#1901]
The Antivirus app which was packaged with oC6.0.5 is incompatible with this version of oC and cannot be enabled.

![capture](https://cloud.githubusercontent.com/assets/5174383/4029719/41bab196-2c54-11e4-84e3-5885398a9bee.PNG)
![log](https://cloud.githubusercontent.com/assets/5174383/4029720/43e82c3c-2c54-11e4-8068-c5ea4c591b68.PNG)

**Comment by PVince81** [comment]
@VicDeo is this issue still valid ?

**Comment by VicDeo** [comment]
Closing. As I wrote above we don't ship files_antivirus with OC7.
