### ISSUE TITLE
External storage: Google Drive exhibiting the same folders multiple times

### ISSUE THREAD

**Issue by franciscoluiz** [owncloud/apps#1944]
### Steps to reproduce
1. Just add a google drive as external storage
2. Go to your main page 
3. Open the folder that represents the external storage
4. Back one level, to the main
5. Return to the external storage folder..

### Expected behaviour
should show folders properly ... as found on google drive

### Actual behaviour
Each time it returns to the folder, certain folders are being displayed duplicate. every time you return, more are appearing again

### Server configuration
**Operating system**: Linux x86_64
**Database:** mysql 5.0.1
**PHP version:** 5.5.14
**ownCloud version:** 7.0.2.1
**Updated from an older ownCloud or fresh install:** fresh install
**List of activated apps:** external storage

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocadc7d92a5b',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'drive._____.net',
  ),
  'datadirectory' => '/home/______/www/drive/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => '_____',
  'dbhost' => 'mysql.______.net',
  'dbtableprefix' => 'oc_',
  'dbuser' => '______',
  'dbpassword' => '_____',
  'installed' => true,
  'loglevel' => '2',
);

```

**Are you using external storage, if yes which one:** google drive

**Are you using encryption:** no

### Client configuration
**Browser:** chrome, firefox

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
various of this:
{"app":"PHP","message":"session_start(): ps_files_cleanup_dir: opendir(\/tmp) failed: Permission denied (13) at \/home\/________\/www\/drive\/lib\/private\/session\/internal.php#21","level":3,"time":"2014-10-01T12:20:39+00:00"}
{"app":"PHP","message":"Undefined offset: 3 at \/home\/________\/www\/drive\/lib\/private\/share\/share.php#1390","level":3,"time":"2014-10-01T12:20:41+00:00"}
{"app":"PHP","message":"curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set at \/home\/________\/www\/drive\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Client.php#466","level":3,"time":"2014-10-01T12:20:42+00:00"}
{"app":"PHP","message":"Undefined offset: 8 at \/home\/________\/www\/drive\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-10-01T12:26:16+00:00"}
{"app":"PHP","message":"Undefined offset: 9 at \/home\/________\/www\/drive\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2014-10-01T12:26:16+00:00"}

**Comment by ipsec** [comment]
Same problem here.

**Comment by Flachzange** [comment]
Seems to be I have the same problem: after I added a Google Drive external storage the first folder was added and all others remain grey. The log shows the following message as long I don't remove the external google drive storage:
```
{"app":"PHP","message":"Undefined offset: 3 at \/var\/www\/vhosts\/owncloud.local\/httpdocs\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2015-02-07T17:33:48+00:00"}
```

### Server configuration
**Operating system**: Ubuntut 14.04 x64
**Web server:** Apache with nginx
**Database:** MySQL 5.5.41
**PHP version:** PHP 5.5.9
**ownCloud version:** 7.0.4
**Updated from an older ownCloud or fresh install:** fresh install
**List of activated apps:** External Storage, Tasks, Contacts
**Are you using external storage, if yes which one:** Google Drive
**Are you using encryption:** no

**Comment by trogdan** [comment]
I have the same problem, but it don't appear to have any special characters in my GDrive folders.  I am seeing the same "undefined offset" and "duplicate file/folder" errors in my log.

**Comment by PVince81** [comment]
The encoding issue is likely to be fixed by https://github.com/owncloud/core/pull/15215

Please try again with 8.1.4 or 8.2.1.

If you still see this issue, please report it in the core repo: https://github.com/owncloud/core
and add logs (would be good to see these "duplicate entry" issues)
