### ISSUE TITLE
New MKCalendar collections end up as 'unnamed'

### ISSUE THREAD

**Issue by guidedways** [owncloud/apps#1963]
No matter which client we use, the ownCloud collection that gets created using MKCalendar ends up being 'unnamed'. Changing the name does not seem to stick. We're tried the built-in Calendar app in Mac, BusyCal and our own code but nothing seems to be working. We just get 'unnamed'.

**Comment by PVince81** [comment]
If you're still seeing this issue in 8.2.1, please raise in the calendar repo.
