### ISSUE TITLE
External user support broken for SMB

### ISSUE THREAD

**Issue by t-b** [owncloud/apps#1974]
System: debian wheezy

I've just upgraded owncloud from 6.0.x to 7.0.3.
After that I could not login with users through the SMB backend (user_external app).

As it turns out the changes in smb.php from c9f92d3c8 broke the support on my server.
This commit changed the logic so that the user authentication fails even for unrelated errors like NT_STATUS_BAD_NETWORK_NAME.

And on my server I get with the correct password

```
smbclient //192.168.100.46/dummy  -U 'thomas%pw'
Domain=[WORKGROUP] OS=[Unix] Server=[Samba 3.6.6]
tree connect failed: NT_STATUS_BAD_NETWORK_NAME
```

and with an incorrect one

```
smbclient //192.168.100.46/dummy  -U 'thomas%invalidpw'
session setup failed: NT_STATUS_LOGON_FAILURE
```
.

I fixed that locally by removing the `elseif (retVal != 0)` block.

**Comment by fbartels** [comment]
As I am not sure if notifications to watchers of this ticket get send by mentioning it in another ticket, I'll just post it here as well.

I extended the check in smb.php to not count NT_STATUS_BAD_NETWORK_NAME as an error and therefore deny login. The fix is in #2059.
