### ISSUE TITLE
Update 7.0.2->7.0.3 

### ISSUE THREAD

**Issue by jameslbrown** [owncloud/apps#1976]
Used the Update function, but it errors with:

Error	updater	Unable to list /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/3rdparty content	November 17, 2014 17:43:01
Error	PHP	scandir(): (errno 2): No such file or directory at /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/apps/updater/lib/helper.php#81	November 17, 2014 17:43:01
Error	PHP	scandir(/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/3rdparty): failed to open dir: No such file or directory at /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/apps/updater/lib/helper.php#81	November 17, 2014 17:43:01
Error	PHP	rename(/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/owncloud,/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/core): No such file or directory at /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/apps/updater/lib/downloader.php#65	November 17, 2014 17:42:28
Error	PHP	rename(/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/owncloud/apps,/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/apps): No such file or directory at /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/apps/updater/lib/downloader.php#64	November 17, 2014 17:42:28
Error	PHP	rename(/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/owncloud/3rdparty,/Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/3rdparty): No such file or directory at /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/apps/updater/lib/downloader.php#63	November 17, 2014 17:42:28

Update page said:

"Checking your installation...
Downloading package...
Creating backup...
Here is your backup: /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/data/updater_backup/7.0.2.1-fa8b63db.zip
Moving files...
Update failed

Unable to list /Library/Server/Web/Data/Sites/owncloud.bordo.com.au/owncloud/_oc-upgrade/7.0.3.4/3rdparty content

The update was unsuccessful. Please check logs at admin page and report this issue to the ownCloud community."

So that's what I'm doing!

Server is running Mac OS X 10.10.0 Yosemite. (Yes, I know!)

Thanks,

James.

**Comment by PVince81** [comment]
Did you have any more luck with 7.0.7 or newer versions ?

**Comment by jameslbrown** [comment]
Seems to be working in version 8. Thanks.
