### ISSUE TITLE
Skip sync for files when transfer is aborted by the server

### ISSUE THREAD

**Issue by alfredosola** [owncloud/apps#1996]
I had a case where mod_security killed a transfer because the file being transferred was too big for the configured limits, which are the default. This is with mod_security 2.8.0-3 on Debian Jessie, and the Mac client 1.7.1.
The behaviour of the OC client could perhaps be improved by skipping the file and continuing with the rest. It should of course throw an error, but not give up on syncing every file just because one file has a server-side problem transferring.

**Comment by PVince81** [comment]
Please reopen in the client repository as this is about client behavior on errors.
Thanks.
