### ISSUE TITLE
Drop admin_dependencies_chk

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/apps#2001]
see https://github.com/owncloud/core/issues/13599#issuecomment-71028654

**Comment by MorrisJobke** [comment]
I checked all the dependencies that are listed in this app:
 * json_encode - available since PHP 5.2.0
 * curl_init - is a soft dependency in core https://github.com/owncloud/documentation/blob/master/admin_manual/installation/source_installation.rst#prerequisites
 * GD - is a hard dependency in core https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/lib/private/util.php#L586
 * LDAP - hard dependency of user_ldap https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/apps/user_ldap/appinfo/info.xml#L22-22
 * bcadd - precompiled into PHP
 * ctype_digit - precompiled into PHP
 * DOMDocument - is a hard dependency in core https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/lib/private/util.php#L578
 * PDO - is a hard dependency in core https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/lib/private/util.php#L593
 * iconv - is a hard dependency in core https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/lib/private/util.php#L588

**Comment by LukasReschke** [comment]
> bcadd - precompiled into PHP
> ctype_digit - precompiled into PHP

You can't rely on that. There are also distributions that don't ship `json_encode` that's why we have an hard-dependency check as well for that :(

**Comment by MorrisJobke** [comment]
Then I will add those checks in core.

**Comment by MorrisJobke** [comment]
ctyp_digit is already there: https://github.com/owncloud/core/blob/7a9d428d6f6146d44883e2c5bab04db702792ce4/lib/private/util.php#L584

**Comment by MorrisJobke** [comment]
bcadd isn't used anymore by the LDAP code -> drop this dependency
