### ISSUE TITLE
Problem in update app

### ISSUE THREAD

**Issue by soniaarora** [owncloud/apps#2003]
when i update the owncloud i got this problem in error log which not allowing me to update it 

date_default_timezone_set(): Timezone ID '' is invalid at /var/www/html/owncloud/apps/user_otp/3rdparty/multiotp/multiotp.class.php#3759

**Comment by karlitschek** [comment]
This seems to be a problem in the user_otp app. Please contact the author of this app.
Thanks

**Comment by soniaarora** [comment]
when i removed user_otp app ..now i m facing this probelm
/tmp/516f2e68ff7e18534b71abb77959ddd9.zip extraction error
