### ISSUE TITLE
unable to update the owncloud 

### ISSUE THREAD

**Issue by soniaarora** [owncloud/apps#2004]
facing this error 
Error	updater	Retrieving http://download.owncloud.org/community/owncloud-7.0.4.zip

**Comment by RealRancor** [comment]
Hi,

1. please re-open in: https://github.com/owncloud/updater/issues
2. please use https://raw.githubusercontent.com/owncloud/core/master/issue_template.md (as asked in the "contributing guidelines" linked in the yellow box when creating a new issue)

**Comment by PVince81** [comment]
See above.
