### ISSUE TITLE
OC Calendar: Enhancement - Limit number of events displayed in month view

### ISSUE THREAD

**Issue by aproposnix** [owncloud/apps#2005]
I'm currently migrating from Google Calendar to Owncloud (thanks to all the devs for making this possible).  One of the things I use Google Calendar for is keeping a calendar of my all of my phone calls (from Android).  I manged to get my call log to synchronize with owncloud calendar but I've come across a GUI issue. 

When you have multiple (read many) calendar events in a day, the OC calendar app (in the month view) will expand the cells to accommodate the extra information. This looks terrible and makes it hard to read the calendar. It would be better if there was limit on the number of entries to show. For those calendar cells which exceed the limit, there could be a link for "see more" which would open the calendar in day view (seems the easiest way) or could open up a pop-up with the full list of events. 

here's an example of how it looks now: 
![selection_005](https://cloud.githubusercontent.com/assets/6204273/5975132/eac2aaec-a87c-11e4-9fe5-f32ab6fcc034.png)

**Comment by karlitschek** [comment]
looks like a problem in the calendar app. Can you open this issue in the calendar repository please?
Thanks a lot.

**Comment by aproposnix** [comment]
Aha.. sorry for that. I thought this was covering all of the OC apps :)
