### ISSUE TITLE
Encryption app can't tolerate interrupted sync

### ISSUE THREAD

**Issue by LogicalDash** [owncloud/apps#2006]
### Steps to reproduce
1. Enable encryption
2. Sync a whole bunch of files, until something happens to interrupt it
3. Try to sync files that had been partially uploaded

### Expected behaviour
Partially uploaded files should be deleted and replaced by new, fresh copies, and those should get encrypted.

### Actual behaviour
When I upload previously-failed files via the owncloud sync client gui, I get the error message Server did not acknowledge last chunk (No e-tag were present).

When I use cadaver to upload them, I get error 3 from the files_encryption app.

The .part files hang around on the server, and I find .key files with the names the .part files would have if they'd finished uploading.

### Server configuration
**Operating system**: Debian 7.1

**Web server:** apache2

**Database:** sqlite

**PHP version:** 5.4.36

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** Tried old/upgraded, then replaced with fresh install; made no difference.

**List of activated apps:**
 - activity
 - calendar
 - contacts
 - documents
 - files
 - files_encryption
 - files_external
 - files_pdfviewer
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - search_lucene
 - templateeditor
 - updater

**The content of config/config.php:**

```
  'instanceid' => 'oc4934be4e14',
  'trusted_domains' => 
  array (
    0 => 'www.zacharyspector.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://www.zacharyspector.com/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'maintenance' => false,
```

**Are you using external storage, if yes which one:** Local only

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox

**Operating system:** Kubuntu 14.10

**Comment by LogicalDash** [comment]
I'm using the cheapest of cheap webhosts, the lowest tier offered by cloudatcost.com

Without encryption, owncloud tolerates the situation remarkably well.

**Comment by RealRancor** [comment]
Dup of: https://github.com/owncloud/core/issues/12725

**Comment by PVince81** [comment]
Closing as duplicate.
Please follow up in https://github.com/owncloud/core/issues/12725
