### ISSUE TITLE
Feature request: Contacts app - add contact photo from url

### ISSUE THREAD

**Issue by frode** [owncloud/apps#2007]
Adding contact photos from a URL would be very handy.

In many scenarios you lookup contact information from a web site, under a companies employee overview where the profile photos are included. 

Simply copy the image url and paste it in a field that appears if you choose "Upload from url" (visible option when you hoover the contact photo.)

**Comment by karlitschek** [comment]
Please open this feature request in the contacts repository. thanks

**Comment by MorrisJobke** [comment]
Can you please reopen this in the calendar bug tracker: https://github.com/owncloud/calendar
