### ISSUE TITLE
app: external; low height of embedded page

### ISSUE THREAD

**Issue by rfettheidler** [owncloud/apps#2015]
OS: Centos 6, 7
Owncloud: 7.x
Browser: Firefox 31.x, Opera 12.x
external pages are embedded with low height

Solution: change first line of file apps/external/templates/frame.php to
```
<iframe src="<?php p($_['url']); ?>" width="100%" height="100%" id="ifm" style="display: block;"></iframe>
```
Inside the base is height missing .

**Comment by karlitschek** [comment]
great. Do you want to send a pull request? :-)

**Comment by MorrisJobke** [comment]
No. There is already a PR.

**Comment by MorrisJobke** [comment]
#1910

**Comment by MorrisJobke** [comment]
This will make it into 8.1. Or should this be backported @karlitschek ?

**Comment by karlitschek** [comment]
Please backport

**Comment by MorrisJobke** [comment]
@karlitschek stable8 only or also stable7?

**Comment by karlitschek** [comment]
stable8 should be enough I think
