### ISSUE TITLE
Display first apps with an update pending

### ISSUE THREAD

**Issue by awikatchikaen** [owncloud/apps#2019]
The new display of apps in the admin menu is great, but like in the 'play store', it would be useful to have the apps to update in the first result. 

Or have a special category

**Comment by RealRancor** [comment]
Hi,

AFAIK the app management is something handled in core so you probably should re-open this in:

https://github.com/owncloud/core/issues

**Comment by MorrisJobke** [comment]
Done https://github.com/owncloud/core/issues/14525
