### ISSUE TITLE
duplicate groups in contacts app when adding new contact with group selected

### ISSUE THREAD

**Issue by drsbaitso** [owncloud/apps#2023]
If I click on one of my groups (Bar)... then click New Contact.  After entering in the name, the Group selection shows two Bar groups.

![dupe](https://cloud.githubusercontent.com/assets/3653167/6416045/b8eaa590-be68-11e4-89ec-36ccd575faed.PNG)

**Comment by karlitschek** [comment]
Can you open this in the contacts repository please. Thanks a lot!
