### ISSUE TITLE
contact,"firm" field is used as "full name" of a person

### ISSUE THREAD

**Issue by promeneur** [owncloud/apps#2024]
opensuse 13.1 , kde 4.14.4 , kaddressbook 4.14.4
raspbian , owncloud 7.0.4 , contact 0.3.0.18

in kaddressbook in owncloud adressbook i create a card about a firm (not a person) then i don't fill the full name field
i fille the field "organisation" (in english "firm" ?) 
the name of the firm is "AB Renovation"
then
i wait for synchronisation to owncloud addressbook
then
i open a session in owncloud then i go to the addressbook

the card is there

i open the card

i see that the field "société" (in english "firm" ?)
it is filled with "AB Renovation" ; good .
but
i see the field "NOM" ("NAME") is filled with "AB Renovation" . this is non sense it's not a person.

 this lead to a pb : 
in android addressbook  a card is added.
in the list it appears as "Renovation AB" where "Renovation" is the name and "AB" is the nickname
then
when i search the card "AB renovation" i search in "A" list not in "R" list" and i don't find it.

a worst case : 
 a firm name "DEUX PLUS DEUX" becomes "DEUX DEUX PLUS" in android .
if you investigate you see in the card this : 
nickname : "DEUX"
2nd nickname : "DEUX"
name : "PLUS"

there is not this pb with google contacts ; it accepts a card without name and with  a firm name.
 please add a second type of card : the type "firm card"
or just accept a card without name .

thanks

**Comment by MorrisJobke** [comment]
Please reopen this in the contacts app: https://github.com/owncloud/contacts
