### ISSUE TITLE
[external] ownCloud theming error (with solution!)

### ISSUE THREAD

**Issue by deMattin** [owncloud/apps#2026]
I actually theme my owncloud and one task is to colorize the menu and show a different ownCloud header depending on the app, that is activated.

In this context I recognzed, that the stylesheet ../apps/external/css/style.css is integrated in the wrong place so this stylesheet loads independent of the fact, if external app is active or not.
So theming owncloud results in unwanted effects.

The fix is simple - you only have to move the "style.css" integration to the correct and recommended place.

1. patch of the file .../owncloud/apps/external/appinfo/app.php:

```php
...
use OCA\External\External;

//OCP\Util::addStyle( 'external', 'style');
OCP\App::registerAdmin('external', 'settings');
...
```
2. patch of the file .../owncloud/apps/external/index.php:
```php
...
OCP\JSON::checkAppEnabled('external');
OCP\User::checkLoggedIn();

OCP\Util::addStyle( 'external', 'style');

$id = isset($_GET['id']) ? (int)$_GET['id'] : 1;
...
```
I tested it with and without theming and it works fine including offering now the theming possibility and I have found no negative aspects.
The style.css (and possibly a theme, that is overwriting this css-file) is now only loaded, if the external app is really active - as it should be!

~~Could someone please make a pull request for this?~~

**Comment by deMattin** [comment]
@karlitschek:
You gave this the enhancement flag.
But in my opinion it' more likely a bug. :wink:
Even without theming, the overhead grows up and speed is reduced due to loading unneccessary css definitions.

**Comment by karlitschek** [comment]
@deMattin A question of perspective :-)
Do you want to open a pull request on fix this?

**Comment by deMattin** [comment]
I already made it!
https://github.com/owncloud/apps/pull/2027

**Comment by karlitschek** [comment]
ahh cool!

**Comment by deMattin** [comment]
Could you please check my request?
Maybe I did something wrong because only one of two patches seems to be automatically checked.

**Comment by deMattin** [comment]
Fixed the pull request (made a new one): #2036

**Comment by MorrisJobke** [comment]
sorry ... wanted to close the old PR :(

**Comment by deMattin** [comment]
Can be closed because PR is merged and issue is solved!
