### ISSUE TITLE
Problem with update from 7.0.2

### ISSUE THREAD

**Issue by prepu** [owncloud/apps#2030]
Hi, I have tried to update the Owncloud server in a Windows Server 2008 from 7.0.2 to 8.0.2 and I got this message:

Unable to move C:\xampp\htdocs\owncloud2\data to C:\xampp\htdocs\owncloud2\data 

Why do I have this problem?

**Comment by MorrisJobke** [comment]
@prepu This is something for the https://github.com/owncloud/core issue tracker. But I'm unsure about the current state of the windows support.
