### ISSUE TITLE
External Files - DropBox - Updated file, modified date not updated

### ISSUE THREAD

**Issue by lyallp** [owncloud/apps#2031]
### Steps to reproduce
1. Have Dropbox setup as external storage
2. Have a file loaded previously, visible
3. Upload a new copy of the same file, overwriting
4. After successful upload, modified date/time does not change, have to go back to Files and drill back into External Storage

### Expected behaviour
After update, the modified date/time should update, as it does with 'internal' storage, ie, 'seconds ago'

### Actual behaviour
The updated date/time remains unchanged, from the originally uploaded copy of the file

### Server configuration
**Operating system**: Linux (Shared Hosting) x86_64

**Web server:** Apache 2.2.29

**Database:** MySQL 5.5.42-cli

**PHP version:** 5.4.36

**ownCloud version:** ownCloud 8.0.2 (stable) 

**Updated from an older ownCloud or fresh install:** Updated from 8.0.0

**List of activated apps:** 
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - mozilla_sync
 - tasks
 - templateeditor
 - updater

**The content of config/config.php:**
<?php
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'secret',
  'dbuser' => 'secret',
  'dbpassword' => 'secret',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'forcessl' => true,
  'theme' => '',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'default_language' => 'en',
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'defaultapp' => 'calendar',
  'knowledgebaseenabled' => true,
  'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
  'appstoreenabled' => false,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/secret/public_html/cloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpauthtype' => 'LOGIN',
  'appcodechecker' => '',
  'log_type' => 'owncloud',
  'logfile' => '/home/secret/owncloud/logs/owncloud.log',
  'loglevel' => '2',
  'logdateformat' => 'Y-m-d H:i:s',
  'logtimezone' => 'Australia/Adelaide',
  'log_rotate_size' => '31457280',
  'passwordsalt' => 'acc481916f0bd3a46d5257dea0fa2a',
  'trashbin_retention_obligation' => 180,
  'allow_user_to_change_display_name' => true,
  'xframe_restriction' => true,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'customclient_desktop' => '',
  'customclient_android' => '',
  'customclient_ios' => '',
  'remember_login_cookie_lifetime' => 1296000,
  'updatechecker' => false,
  'writable_appsdir' => true,
  'datadirectory' => '/home/secret/owncloud/data',
  'version' => '8.0.2.0',
  'maxZipInputSize' => '838860800',
  'allowZipDownload' => true,
  'instanceid' => '514824ae2237a',
  'maintenance' => false,
  'mail_from_address' => 'OwnCloud-NoReply',
  'mail_domain' => 'secret.com',
  'trusted_domains' => 
  array (
  ),
  'secret' => 'secret',
  'forceSSLforSubdomains' => true,
);

**Are you using external storage, if yes which one:** Via the external storage app, DropBox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**No

### Client configuration
Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0

**Operating system:**
Linux lyalls-pc 3.18.7-gentoo #1 SMP Sun Feb 22 10:29:18 CST 2015 x86_64 Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz GenuineIntel GNU/Linux

**Comment by MorrisJobke** [comment]
@karlitschek @icewind1991 @DeepDiver1975 Isn't this something for the core repo, because dropbox is part of the core?

**Comment by karlitschek** [comment]
Yes it is. @lyallp Can you open this in the core repository please? Thanks.
