### ISSUE TITLE
external storage makes owc unusable (white page after login)

### ISSUE THREAD

**Issue by mr-gosh** [owncloud/apps#2033]
after the update from owncloud 7.0.? to 8.0.2 we had a white page for one user after login - some other users didn't have files listed in their files app.

after a little search we recognized that the "external storage" app (0.2.3) is creating the problems.
if this app is deactivated, we can see all files and the user with the white page can see things...

=====

after some search we recognized that it was not allowed to have apps activated during the update process - but that was the fact for us. perhaps the problems are produced through this?!?

@iakiakiak

**Comment by MorrisJobke** [comment]
@mr-gosh Can you have a look at the owncloud log for more info?

**Comment by iakiakiak** [comment]
Owncloud log wile activating external storage support:
Error 	PHP 	file_exists(): open_basedir restriction in effect. File(/l10n/) is not within the allowed path(s): (/var/www/vhosts/domain.net/httpdocs/:/tmp/) at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/l10n.php#462 	2015-04-01T20:39:02+00:00
**Error 	PHP 	Class 'OC_Filestorage_Dropbox' not found at /var/www/vhosts/domain.net/httpdocs/owncloud/apps/files_external/lib/config.php#927 	2015-04-01T20:38:51+00:00**
Error 	PHP 	file_exists(): open_basedir restriction in effect. File(/l10n/) is not within the allowed path(s): (/var/www/vhosts/domain.net/httpdocs/:/tmp/) at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/l10n.php#462 	2015-04-01T20:38:50+00:00
Error	PHP	require(): open_basedir restriction in effect. File(/version.php) is not within the allowed path(s): (/var/www/vhosts/domain.net/httpdocs/:/tmp/) at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(/version.php): failed to open stream: Operation not permitted at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(): open_basedir restriction in effect. File(/version.php) is not within the allowed path(s): (/var/www/vhosts/domain.net/httpdocs/:/tmp/) at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(): Failed opening required 'version.php' (include_path='/var/www/vhosts/domain.net/httpdocs/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/vhosts/domain.net/httpdocs/owncloud/3rdparty/pear/pear_exception:/var/www/vhosts/domain.net/httpdocs/owncloud/3rdparty/pear/archive_tar:/var/www/vhosts/domain.net/httpdocs/owncloud/lib/private:/var/www/vhosts/domain.net/httpdocs/owncloud/config:/var/www/vhosts/domain.net/httpdocs/owncloud/3rdparty:/var/www/vhosts/domain.net/httpdocs/owncloud/apps:/var/www/vhosts/domain.net/httpdocs/owncloud/lib:.::/var/www/vhosts/domain.net/httpdocs/owncloud') at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(/version.php): failed to open stream: Operation not permitted at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(): open_basedir restriction in effect. File(/version.php) is not within the allowed path(s): (/var/www/vhosts/domain.net/httpdocs/:/tmp/) at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(/version.php): failed to open stream: Operation not permitted at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:06+00:00
Error	PHP	require(): open_basedir restriction in effect. File(/version.php) is not within the allowed path(s): (/var/www/vhosts/domain.net/httpdocs/:/tmp/) at /var/www/vhosts/domain.net/httpdocs/owncloud/lib/private/util.php#320	2015-04-01T20:39:0

**Comment by mr-gosh** [comment]
iakiakiak just posted it... ;-)

**Comment by PVince81** [comment]
@iakiakiak please double check that the ownCloud source code was properly updated.
This class "OC_Filestorage_Dropbox" is extremely old (maybe pre-OC4) and didn't exist since a long time.
Maybe also check "mount.json" in the data folder and see whether this class name is set there.

**Comment by PVince81** [comment]
what I mean is that when you updated the source code, you need to delete the old PHP code first before extracting the tarball. Don't just extract the new tarball over the old code. (in case you did that)

**Comment by PVince81** [comment]
Please double check how you upgraded the source code.
When upgrading you should delete all the old source code before extracting the new one.

You can also check your mount.json file, maybe there is still an older reference to this class that need to be deleted.

If you're still seeing this issue with 8.0.9, 8.1.4 or 8.2.1, please reopen and post your mount.json
