### ISSUE TITLE
Music app doesn't read MP3 tags (ownCloud 7.0.2)

### ISSUE THREAD

**Issue by temmokan** [owncloud/apps#2034]
Music app: 0.3.5

Web server: Apache 2.2.15, PHP 5.5.21

OS: CentOS 6.5 x86_64

allow_url_fopen is True in php.ini, magic quotas are turned off

In music/ app files tree, in 3rdparty/getID3/getid3/getid3.php, on line 96, 

public $option_max_2gb_check = false

Rescan:

./occ music:scan --all

performs and reports scan are done, nothing written to owncloud.log, yet all music files are still by Unknwon Artist within Unknown Album.

I would appreciate pieces of advise on how to handle that.

**Comment by MorrisJobke** [comment]
Reopened in https://github.com/owncloud/music/issues/356
