### ISSUE TITLE
Update fails with "unable to list [...]/owncloud/_oc-upgrade/8.0.2.0/3rdparty content"

### ISSUE THREAD

**Issue by resound88** [owncloud/apps#2035]
Hi together,
we have problems with upgrading our ownCloud 6.0.4.1 to a never version with help of the update-center.
This is the error message:
Unable to list [...]owncloud/_oc-upgrade/8.0.2.0/3rdparty content
The newly created folder _oc-upgrade has been removed after the update attempt, but the permissions seemed to be okay.
It's running on Debian 6.
Best regards

**Comment by VicDeo** [comment]
@resound88 sorry, direct upgrade to 6 to 8 is not supported, please migrate to OC7.0.5 first.
https://doc.owncloud.org/server/6.0/admin_manual/maintenance/update.html#upgrade

**Comment by VicDeo** [comment]
@resound88 argh. Please do not use 
`wget http://download.owncloud.org/community/owncloud-latest.tar.bz2` as specified in the manual above but 7.0.5 from this page `https://owncloud.org/changelog/` instead:
`wget https://download.owncloud.org/community/owncloud-7.0.5.tar.bz2`

**Comment by resound88** [comment]
@VicDeo Thank's a lot, that worked perfectly!
