### ISSUE TITLE
Hidden files are not displayed properly if the contain two dots

### ISSUE THREAD

**Issue by PeterPablo** [owncloud/apps#2038]
### Steps to reproduce
1. Open files app in browser
2. Open folder containing hidden files: `.hidden` and `.hdf2.9`

### Expected behaviour
`.hdf2.9` should be completely gray.

### Actual behaviour
Notice that `.hdf2.9` is not properly colored, due to the second dot in the filename.
![image](https://cloud.githubusercontent.com/assets/4340267/6825772/28cd7740-d2fd-11e4-8095-f8b6a267dc27.png)

### Server configuration

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** updated

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium 37

**Operating system:** Ubuntu

**Note:** I stripped down the template a bit, since I think this info is not relevant here.

**Comment by MorrisJobke** [comment]
This isn't how it should work. Only the extension is shown in gray. And currently the extension is determined by everything behind the last dot. For more hidden file stuff see https://github.com/owncloud/core/issues/2589

**Comment by PeterPablo** [comment]
I saw that other issue, as well as the PR https://github.com/owncloud/core/pull/4369 and https://github.com/owncloud/core/pull/8438 that were both not accepted.
Even if the current behavior should show the extension in gray, I think it is weird to handle files starting with a dot like this...

**Comment by MorrisJobke** [comment]
@PeterPablo Let me have a look at this :)

**Comment by PeterPablo** [comment]
Don't worry. It's certainly of low priority. Just wanted to make you aware of this. Me pointing to the line of code probably simplifies matters.

**Comment by MorrisJobke** [comment]
@PeterPablo Yes...but it is really early in the morning and this is an easy starter ;)
