### ISSUE TITLE
Admin documentation/help link in LDAP configuration does not load

### ISSUE THREAD

**Issue by scobarbb** [owncloud/apps#2039]
For app 'LDAP user and group backend'

admin guide/help link resolve to this link:

https://doc.owncloud.org/server/8.0/admin_manual/configuration/user_auth_ldap.html

Returns 404.

**Comment by RealRancor** [comment]
Hi,

does the initial linik which resolves to this contains a "goto.php" ?

**Comment by karlitschek** [comment]
@carlaschroder @danimo

**Comment by scobarbb** [comment]
This is the first link:
http://doc.owncloud.org/server/8.0/go.php?to=admin-ldap
Then resolves to:
https://doc.owncloud.org/server/8.0/admin_manual/configuration/user_auth_ldap.html

**Comment by RealRancor** [comment]
Ah, yes. Those links are handled in:

https://github.com/owncloud/documentation/issues/

**Comment by scobarbb** [comment]
So this need to be re-entered over there, or can this be re-assigned?

**Comment by RealRancor** [comment]
github doesn't allow the move issues to other repositories. But i think you can leave this here, will create a PR to fix this later.

**Comment by RealRancor** [comment]
PR in https://github.com/owncloud/documentation/issues/994
