### ISSUE TITLE
[tasks] Tasks app doesn't work with 8.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#2045]
The tasks app can be enabled with 8.1, but clicking the icon in the navigation menu redirects to the main page.

@LukasReschke I guess maybe that app is missing the new routing ? I'll have to look that up to find out how to fix it.

**Comment by PVince81** [comment]
Looks like the routing changes, on it.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/tasks/blob/master/appinfo/routes.php ? :see_no_evil:

**Comment by PVince81** [comment]
Yes, I was on the wrong branch (stable7) when looking at the tasks app...
