### ISSUE TITLE
[tasks] Tasks app requires external calendar app

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#2046]
It looks like the "tasks" app requires the "calendar" app to be enabled.

Maybe we should move the "tasks" app to its own repo too ?

@karlitschek @DeepDiver1975 @LukasReschke what do you think ?

**Comment by RealRancor** [comment]
Mhh, i thought the tasks app (former tasks enhanced) already has its repos here:

https://github.com/owncloud/tasks

**Comment by PVince81** [comment]
Yes it has. I was on the wrong branch (stable7) when I looked at it. Closing.
