### ISSUE TITLE
Recommended apps never load

### ISSUE THREAD

**Issue by ntassani** [owncloud/apps#2051]
Hi! I have recently installed Owncloud in my xampp with the bitnami owncloud module in elementary freya. All work flawesly, but the recommended apps section never load. I chek the permissions and is all ok.
I manually install the contacts app ok.

Any help? thanks for your amazing work :)

**Comment by karlitschek** [comment]
Hmm. Maybe the bitname package has problems with network connections or is somehow firewalled? I recommendto report this problem to them. Works fine here.

**Comment by ntassani** [comment]
http://horasextras.ddns.net/owncloud please help!!! all is working ok... only this problem.
Please, don't close my problem...

**Comment by carlaschroder** [comment]
@ntassani I am also seeing this behavior. 8.02 ES, on both Chrome and Firefox. Which version of ownCloud are you running? Which Web browser? I'm wondering if it's a theme bug. When you View Source, do you see anything like this:

```
<nav><div id="navigation">
			<div id="apps" class="svg">
				<ul>
									<li data-id="files_index">
						<a href="/owncloud/index.php/apps/files" title=""
							>
							<img class="app-icon svg" alt="" src="/owncloud/core/img/places/files.svg"/>
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Files							</span>
						</a>
					</li>
									<li data-id="activity">
						<a href="/owncloud/index.php/apps/activity/" title=""
							>
							<img class="app-icon svg" alt="" src="/owncloud/apps/activity/img/activity.svg"/>
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Activity							</span>
						</a>
					</li>
```

**Comment by carlaschroder** [comment]
Oh, never mind the View Source output-- not sure that's relevant. Anyway, I can confirm that you're not the only one seeing this behavior, @ntassani

**Comment by ntassani** [comment]
Yes, i have the version 8.02. And i use Opera and Chrome.
And yes, i have in the source:
<nav><div id="navigation">
			<div id="apps" class="svg">
				<ul>
									<li data-id="files_index">
						<a href="/owncloud/index.php/apps/files" title=""
							>
							<img class="app-icon svg" alt="" src="/owncloud/core/img/places/files.svg"/>
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Archivos							</span>
						</a>
					</li>
									<li data-id="activity">
						<a href="/owncloud/index.php/apps/activity/" title=""
							>
							<img class="app-icon svg" alt="" src="/owncloud/apps/activity/img/activity.svg"/>
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Actividad							</span>
						</a>
					</li>
									<li data-id="gallery_index">
						<a href="/owncloud/index.php/apps/gallery/" title=""
							>
							<img class="app-icon svg" alt="" src="/owncloud/apps/gallery/img/gallery.svg"/>
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Imágenes							</span>
						</a>
					</li>
									<li data-id="contacts">
						<a href="/owncloud/index.php/apps/contacts/" title=""
							>
							<img class="app-icon svg" alt="" src="/owncloud/apps/contacts/img/contacts.svg"/>
							<div class="icon-loading-dark" style="display:none;"></div>
							<span>
								Contactos							</span>
						</a>
					</li>

**Comment by RealRancor** [comment]
Hi,

this don't looks like an issue with an app itself (which this issue tracker is about) but more like a core problem. There are also some reported issues with the appstore connection if your system is missing the intermediate cert.

**Comment by ntassani** [comment]
RealRancor, are you saying this problem is related to ssl certificates? I dont use https... But if that correct the problem i want use that :)
I know, this is not a bigger issue becuase i can search and insall the apps manually without problems. But 1 click can be amazing :)

**Comment by RealRancor** [comment]
Hi,

i say it could be related to the SSL connection to the appstore. Even if you don't use SSL for your server this connection is done via SSL.

**Comment by ntassani** [comment]
Hi! I switch to ssl conection and the issue persists... Is a real mistery, i do the exact installation under virtualbox and the recommended apps are loading. I check the permissions again and is all ok. The apps folder is 777. I dont know what more can i try.

**Comment by RealRancor** [comment]
Hi,

its not the certificate/ssl connection to your server as written  above.

**Comment by ntassani** [comment]
Realrancor, how i can check the ssl connection to the appstore? Where is the connection file/files?

**Comment by RealRancor** [comment]
See https://forum.owncloud.org/viewtopic.php?f=31&t=26310&start=30#p85771

**Comment by PVince81** [comment]
Is this still happening ?
