### ISSUE TITLE
uploading ics file with multiple events fails with : 400 Bad Request.

### ISSUE THREAD

**Issue by miguelclean** [owncloud/apps#2053]
When I try uploading ics files to my calendar with *cadaver* (http://www.webdav.org/cadaver/) I get a "400 Bad Request" response, if the *ics* file contains more than one event. (i.e. multiple events with different UID's). It works fine as long as there is only one event (or all events share the same UID). 

Am I expected to upload each event in a seperate *ics* file?

owncloud 8.0.3
cadaver 0.23.3

**Comment by MorrisJobke** [comment]
@miguelclean This seems to be a calendar issue. Please reopen here: https://github.com/owncloud/calendar/issues

Also be more precise, what upload means. Maybe paste in your cadaver commands.
