### ISSUE TITLE
After enable the user_external app there is no table and setting for imap user

### ISSUE THREAD

**Issue by vikasnagare** [owncloud/apps#2056]
I enable the own cloud user_external app but no seting available in admin and when i adding the code in config.php it gives error. and make blank.
Please help.

I have to use imap user for login owncloud

**Comment by RealRancor** [comment]
Anything in your logfiles? Could be also just a syntax error you have done in the config.php

**Comment by RealRancor** [comment]
@vikasnagare PING?
