### ISSUE TITLE
Multiple Users Wrong Distribution / Not Showing Other users Data: Only Names - Storage Charts 2 Application 2.6.0

### ISSUE THREAD

**Issue by t2tbr** [owncloud/apps#2057]
I have only 2 users in my OC 8.03.
My user is an admin, and the other is not.

When I open the graphs, they only display data as if the admin user has all the data. If I open it as the other user, it shows as if only the other user has all the data.

Even if I filter (in the admin page), the other user (clicking in over the other user) it shows 0, just flat lines with value 0.

My setup is with MySql.

Thanks

**Comment by t2tbr** [comment]
Quick update: I logged with the other user (it has never been logged before, only Client Sync) and now the charts are displayed as if each user is using 50% of the used space. Example: 21% and 21%, even though I know that that is not correct (should be 80% 20%).

**Comment by RealRancor** [comment]
Hi,

please note that this is the issue tracker of the ownCloud core apps. The issue tracker of the Storage Charts 2 App is located here:

https://github.com/hypery2k/owncloud/issues

Please close this issue and re-open there.

**Comment by t2tbr** [comment]
Moved issue to correct place.
