### ISSUE TITLE
Internal server error after upgrading Owncloud from 8.0.2 to 8.0.3

### ISSUE THREAD

**Issue by Luticus** [owncloud/apps#2058]
I've actually solved this problem but figured I'd post it in case anyone else has the issue and needs help.  Also it would be great if the devs could find a solution so the issue can be avoided in the future.

After upgrading Owncloud to version 8.0.3 I received an Internal server error when trying to get to the login page.  The Owncloud Log didn't show any new entries, but fortunately the Apache log did!

Turns out the upgrade overwrote my external sites app with a new version and this cleared out my custom icons.  This somehow cause an error that prevented the site from loading.  I had to extract my back up and move the icons back into the img folder in external apps.  

Hopefully this helps!

**Comment by karlitschek** [comment]
can you post the error you saw in the apache log?
This is very strange.

**Comment by Luticus** [comment]
[Sat May 09 19:24:50 2015] [error] [client 0.0.0.0] {"reqId":"4a95f79a66aed5226ca295757d4be765","remoteAddr":"0.0.0.0","app":"index","message":"Exception: {\\"Message\\":\\"image not found: image:1.png webroot:\\\\\\/owncloud serverroot: \\\\\\/owncloud\\",\\"Code\\":0,\\"Trace\\":\\"#0  \\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/helper.php(216): OC\\\\\\\\URLGenerator->imagePath('external', '1.png')\\\\n#1  \\\\\\/owncloud\\\\\\/lib\\\\\\/public\\\\\\/util.php(316): OC_Helper::imagePath('external', '1.png')\\\\n#2  \\\\\\/owncloud\\\\\\/apps\\\\\\/external\\\\\\/appinfo\\\\\\/app.php(36): OCP\\\\\\\\Util::imagePath('external', '1.png')\\\\n#3  \\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/app.php(117): require_once(' \\\\\\/ownc...')\\\\n#4  \\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/app.php(98): OC_App::requireAppFile('external')\\\\n#5  \\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/app.php(77): OC_App::loadApp('external')\\\\n#6  \\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(778): OC_App::loadApps()\\\\n#7  \\\\\\/owncloud\\\\\\/index.php(36): OC::handleRequest()\\\\n#8 {main}\\",\\"File\\":\\" \\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/urlgenerator.php\\",\\"Line\\":153}","level":4,"time":"2015-05-09T19:24:50-04:00","method":"POST","url":"\\/owncloud\\/\\/index.php\\/apps\\/ocsms\\/push?format=json"}


These were the kids of messages I was seeing.  As soon as I replaced the png files in ../owncloud/apps/externalsites/img, everything worked fine.  BTW, I have zeroed out the connecting IPs and removed the leading directories to my owncloud install so ignore that :).

**Comment by patricktokeeffe** [comment]
I receive this error on a clean DigitalOcean ownCloud 8.0.2 (14.04 x64) droplet after running

    ~# apt-get update
    ~# apt-get upgrade

I checked that ownCloud *does* operate correctly before attempting to update. After running these commands, an Internal Server Error page is returned instead. The upgrade command doesn't finish either:

````
*lots of trimmed output* 
...
Preparing to unpack .../owncloud-server_8.0.3-2_all.deb ...
Unpacking owncloud-server (8.0.3-2) over (8.0.2-5) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb (--unpack):
 trying to overwrite '/var/www/owncloud/.htaccess', which is also in package owncloud-config-apache 8.0.3-2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../owncloud-app-activity_8.0.3-2_all.deb ...
Unpacking owncloud-app-activity (8.0.3-2) over (8.0.2-5) ...
Preparing to unpack .../owncloud_8.0.3-2_all.deb ...
Unpacking owncloud (8.0.3-2) over (8.0.2-5) ...
Preparing to unpack .../patch_2.7.1-4ubuntu2_amd64.deb ...
Unpacking patch (2.7.1-4ubuntu2) over (2.7.1-4ubuntu1) ...
Preparing to unpack .../php-pear_5.5.9+dfsg-1ubuntu4.9_all.deb ...
Unpacking php-pear (5.5.9+dfsg-1ubuntu4.9) over (5.5.9+dfsg-1ubuntu4.7) ...
Preparing to unpack .../policykit-1_0.105-4ubuntu2.14.04.1_amd64.deb ...
Unpacking policykit-1 (0.105-4ubuntu2.14.04.1) over (0.105-4ubuntu2) ...
Preparing to unpack .../python-urllib3_1.7.1-1ubuntu3_all.deb ...
Unpacking python-urllib3 (1.7.1-1ubuntu3) over (1.7.1-1ubuntu0.1) ...
Preparing to unpack .../unattended-upgrades_0.82.1ubuntu2.2_all.deb ...
Unpacking unattended-upgrades (0.82.1ubuntu2.2) over (0.82.1ubuntu2.1) ...
Preparing to unpack .../wpasupplicant_2.1-0ubuntu1.2_amd64.deb ...
Unpacking wpasupplicant (2.1-0ubuntu1.2) over (2.1-0ubuntu1.1) ...
Preparing to unpack .../cloud-init_0.7.5-0ubuntu1.5_all.deb ...
Unpacking cloud-init (0.7.5-0ubuntu1.5) over (0.7.5-0ubuntu1.4) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
~#
````

**Comment by patricktokeeffe** [comment]
Continuing anyway produces an exception.

````
/var/www/owncloud# sudo -u www-data php occ upgrade
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/owncloud/lib/private/db/connection.php:33
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(814): OC\DB\Connection->connect()
#1 /var/www/owncloud/lib/private/db/connection.php(111): Doctrine\DBAL\Connection->executeQuery('SELECT `configv...', Array, Array, NULL)
#2 /var/www/owncloud/lib/private/appconfig.php(259): OC\DB\Connection->executeQuery('SELECT `configv...', Array)
#3 /var/www/owncloud/lib/private/app.php(219): OC\AppConfig->getValues(false, 'enabled')
#4 /var/www/owncloud/lib/private/app.php(71): OC_App::getEnabledApps()
#5 /var/www/owncloud/lib/base.php(542): OC_App::loadApps(Array)
#6 /var/www/owncloud/lib/base.php(1011): OC::init()
#7 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#8 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
````

**Comment by PVince81** [comment]
Are you still seeing such issues with 8.0.5 ?

**Comment by Luticus** [comment]
I did have the issue with 8.0.4, have not gotten any upgrade message for 8.0.5 and will likely go straight to 8.1 soon.

**Comment by PVince81** [comment]
Please reopen if you're still having issues with the most recent versions.
