### ISSUE TITLE
Update .travis.yml in all repos to match stable8.1

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/apps#2060]
- [x] activity: https://github.com/owncloud/activity/pull/296
- [x] bookmarks: https://github.com/owncloud/bookmarks/pull/148
- [x] calendar: No `.travis.yml`
- [x] chat: No limit
- [x] contacts: https://github.com/owncloud/contacts/pull/897
- [x] documents: https://github.com/owncloud/documents/pull/481
- [x] files_antivirus: https://github.com/owncloud/files_antivirus/pull/43
- [x] files_locking: https://github.com/owncloud/files_locking/pull/31
- [x] files_pdfviewer: https://github.com/owncloud/files_pdfviewer/pull/52
- [x] files_texteditor: No limit
- [x] firstrunwizard: No limit
- [x] gallery: https://github.com/owncloud/gallery/pull/187
- [x] galleryplus: https://github.com/owncloud/galleryplus/pull/137
- [x] mail: https://github.com/owncloud/mail/pull/653
- [x] news: No limit
- [x] search_lucene: https://github.com/owncloud/search_lucene/pull/86
- [x] shorty: No `.travis.yml`
- [x] tasks: https://github.com/owncloud/tasks/pull/161
- [x] templateeditor: https://github.com/owncloud/templateeditor/pull/25
- [x] updater: https://github.com/owncloud/updater/pull/120

**Comment by DeepDiver1975** [comment]
thx @nickvergessen
