### ISSUE TITLE
Add a new user automatically to group

### ISSUE THREAD

**Issue by crysman** [owncloud/apps#2061]
Hello,

I've modified the user_external plugin (apps/user_external/lib/imap.php) in a way that every IMAP authenticated newcomer is being set default quota. That was easy:
`OC_Preferences::setValue($uid, 'files', 'quota', '256 MB');`

Now I want the newly created usr to be automatically assigned to a group (already existing group).

How do I do that, please?

**Comment by karlitschek** [comment]
sounds like a great question to ask on the owncloud devel mailinglist. thanks :-)
