### ISSUE TITLE
Automatic upgrade of ownCloud third-party apps / "App-Store"

### ISSUE THREAD

**Issue by Dark-Fenix** [owncloud/apps#2066]
Hi,

First, my apologies if the question has already been asked, or if it's not the right place to do so.

Is there any graphical method to automatically update specific apps to their latest stable versions, or allowing the administrator to chose the version/tag to install ?

I've seen during my update to 8.0.2 that the web interface indicates the available updates for the owncloud-supported apps, but not for the third-party ones (or maybe I missed it, but I needed to upgrade them manually through SSH). And what about the apps which are regularly updated, how can the administrators stay up-to-date without having to inspect each github repo ?

Is there any really efficient "app-store" currently on the roadmap, accessible directly from the administration interface of ownCloud and allowing everyone to set up apps ? :)

Thanks in advance for your answers !

**Comment by RealRancor** [comment]
Hi,

i think thats something which should go to:

https://github.com/owncloud/core/issues

as this is something which is handled in core.

Personally i have subscribed to the apps i'm using at https://apps.owncloud.com to get mail notifications on updates.

**Comment by Dark-Fenix** [comment]
You are right, I will put this in the core repo :)

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/core/issues/16378

Feel free to close this one.

**Comment by Dark-Fenix** [comment]
Sure.
