### ISSUE TITLE
After Upgrade to 8.0.3 / External Storage / "Cannot redeclare class smb"

### ISSUE THREAD

**Issue by BlueStar88** [owncloud/apps#2068]
Expected behaviour:

External Storage module should work, even if there are multiple instances of OC installed on the same host.

Actual behaviour:

First OC instance wins, all successive ones die on visit with following lighttpd error:

---
Cannot redeclare class smb in /var/www/instance1/apps/files_external/3rdparty/smb4php/smb.php on line 45
---

The error points to the code of the first visited OC instance. The webserver delivers nothing to the webbrowser. The first visited OC instance works like expected.

OS: Ubuntu Server 14.04.2 LTS
DB: MySQL 5.5.43-0ubuntu0.14.04.1
PHP: 5.5.9+dfsg-1ubuntu4.9
OC: 8.0.3
Web: lighttpd 1.4.35-0.1
Updated Installation (from 8.0.2)
Apps: Activity,Bookmarks,Calendar,Contacts,Deleted Files,Documents,External Sites,External storage support,First Run Wizard,Full Text Search,Imprint,Mail Template Editor,PDF Viewer,Pictures,Server-side Encryption,Share Files,Text Editor,Updater,Versions,Video Viewer

config.php
---
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'datadirectory' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => '4',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',
  ),
  'share_folder' => '/Shared',
  'secret' => 'XXX',
  'overwrite.cli.url' => 'XXX',
);
---

Usage of external storage unknown. I can not speak on behalf of other users.

Encryption is used.

External User-Backend not used.

Other information will be delivered on request.

**Comment by RealRancor** [comment]
Hi,

AFAIK problems/bugs of the files_external app are handled in core:

https://github.com/owncloud/core/issues

**Comment by BlueStar88** [comment]
You're right, I was not reading the parts list of core. Thanks for the hint! I'll try to move this out of here...
