### ISSUE TITLE
Bug in Owncloud 8 UI when going back from open PDF.

### ISSUE THREAD

**Issue by xymantec** [owncloud/apps#2069]
It looks like when you press back on an open PDF the screen gets stuck on the PDF but you can see it list out folders, check screenshot provided.

![books files owncloud](https://cloud.githubusercontent.com/assets/6463675/7668796/9ae1f5dc-fc00-11e4-8608-d8c71e8f023c.png)

**Comment by cstroe** [comment]
+1

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/files_pdfviewer/issues/79
