### ISSUE TITLE
Cannot import calendars with no objects

### ISSUE THREAD

**Issue by spawnazzo** [owncloud/apps#2070]
### Steps to reproduce
1. Download a calendar with some "online" sources like http://www.officeholidays.com/ics/subscribe_region.php?tbl_region=zug&tbl_country=Switzerland
2. Upload the files 
3. make an import

### Expected behaviour
Calendar data should be retrieved from the network 

### Actual behaviour
No error issued only a progressbar that is not working 

### Server configuration
**Operating system**: Ubuntu 14.04.1

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.5.9

**ownCloud version:** 8

**Updated from an older ownCloud or fresh install:** fresh install 

**List of activated apps:** calendar and ldap

**The content of config/config.php:** just basic info

```
Insert your config.php content here
not needed
```

The issue is rised from line 118 on apps/calendar/lib/import.php a check should be performed here and maybe add the possibility to download the events from internet. 
In that specific calendar works. In order to keep solve the problem i had to import the calendar into my calendar app (google calendar but it also works on ical) download all the items then export the filled calendar and reimport it on my company calendar again. 

This is a bit annoying do you have any hint? 

thanks

**Comment by RealRancor** [comment]
Hi,

the issue tracker of the calendar app is located here:

https://github.com/owncloud/calendar/issues

As github doesn't allow to move issues its probably the best if you're re-opening this there.

**Comment by spawnazzo** [comment]
Reopened here
https://github.com/owncloud/calendar/issues/791
