### ISSUE TITLE
Undefined variable: user at /opt/bitnami/apps/owncloud/htdocs/apps/files_antivirus/lib/scanner.php#61

### ISSUE THREAD

**Issue by mesiah70** [owncloud/apps#2074]
Dear all,

I have the following issue regardin the clamav on OC 8.0. I got this below error. I know this issue was opened last year in Julay, but all the suggested tips didn't work:

Undefined variable: user at /opt/bitnami/apps/owncloud/htdocs/apps/files_antivirus/lib/scanner.php#61

I don't have an empty line as well. So what may cause this, clamav version is 0.4.2

Rgds and thy for your help

Mesiah70

**Comment by VicDeo** [comment]
@mesiah70 antivirus issues are tracked here https://github.com/owncloud/files_antivirus/issues

Regarding your issue: please update the app with recent stable8 branch https://github.com/owncloud/files_antivirus/archive/stable8.zip

**Comment by mesiah70** [comment]
Sorry but I get this error, after I've activated the plugin. The OC is not accessible anymore

An exception occurred while executing 'ALTER TABLE `oc_files_antivirus_status` RENAME TO `oc_files_avir_status`': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_owncloud.oc_files_antivirus_status' doesn't exist
