### ISSUE TITLE
after updating files_antivirus to the latest version 0.6.2 error with bitnami_owncloud.oc_files_antivirus_status doesn't exist

### ISSUE THREAD

**Issue by mesiah70** [owncloud/apps#2075]
Hello,

I got the following error, when I update the files_antivirus according VicDeo on my bitnami oc:

An exception occurred while executing 'ALTER TABLE oc_files_antivirus_status RENAME TO oc_files_avir_status': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_owncloud.oc_files_antivirus_status' doesn't exist

Thanks for your kind help

Haydar

**Comment by VicDeo** [comment]
@mesiah70 remove these lines https://github.com/owncloud/files_antivirus/blob/master/appinfo/preupdate.php#L12-L15 

**and please report antivirus issues to [antivirus repo](https://github.com/owncloud/files_antivirus/issues)**
