### ISSUE TITLE
last song replays after calling a android phone with the client

### ISSUE THREAD

**Issue by kaystrobach** [owncloud/apps#2077]
steps to reproduce (android):

1. start a song or audio book in the owncloud client
2. wait until the screen goes off
3. wait until the song or music is over
4. call the phone
5. music starts again

expected behaviour

* do not replay song

workaround:

* after starting playing music go the the start screen

**Comment by RealRancor** [comment]
Hi,

please re-open in: https://github.com/owncloud/android/issues

**Comment by kaystrobach** [comment]
done
