### ISSUE TITLE
Feature request for File types restrictions (allowed file types to upload,create,rename) 

### ISSUE THREAD

**Issue by madhusudan** [owncloud/apps#2078]
Hi,
I was wondering why still no one has thought about implementing allowed file type restrictions!!.
Like allowing only Images/Text/Documents to be uploaded and blocking executables like .exe,.bat,.msi etc.. (for security reasons) through out the site. This is the basic need for any web application.

For an easy example, image if a user has an executable file that contains malicious code and he is unaware of that and uploads the same to the site, and if the antivirus  fails to identify it as a threat,  if another user downloads the same file and executes it!, and imagine if many users does same!!!.

An option in admin page like 2 radio buttons with one long text field for entering allowed file types(like below).

                             * Enable all File Types
                             *Allowed File Types
                                 textfield
                                      txt,pdf,doc,jpg,png,jpeg,docx,ppt,pptx,xls,xlsx,..........

Isn't this a good idea that makes sense..? (I believe prevention is better than cure! :-) )

**Comment by RealRancor** [comment]
Hi,

at least the File Firewall of the Enterprise Edition is providing such fine granular upload permission for filetypes: https://github.com/owncloud/documentation/pull/1173

**Comment by RealRancor** [comment]
Just to have a context why this was closed:

A new app is now providing this functionality: https://apps.owncloud.com/content/show.php/files_filter?content=174667

**Comment by mckaygerhard** [comment]
a new app was provided but seems not official so app could be died by author lack of manteneance..

the request was made over the oc team not for external..

must remain opened its nonsense

**Comment by RealRancor** [comment]
You request is nonsense

**Comment by Rankgel** [comment]
would be helpful have this function in OC 7, but if it's not posible, please give us a lead of what  is needed to implement it in OC7,I'm not saying you to do it, but  I ask you to let me do it  and for those who still use OC7. I have no plans to upgrade my OC.

**Comment by RealRancor** [comment]
https://doc.owncloud.org/server/7.0/developer_manual/app/index.html might be a starting point.

Still, oC 7 will reach end-of-life in a month...

**Comment by madhusudan** [comment]
checked the file filter app, https://apps.owncloud.com/content/show.php?action=content&content=174667
It works but it blocks(deletes) the file after uploading the file, that doesn't make sense for a big file, it should be blocked before upload itself, user could save some bandwidth!.. :).
This app can be modified and later can be pushed into the core part, as many people need it.

@Rankgel 
you need to edit some core files like upload.php in apps/files/ajax/  which will block at front end (in browser), again this blocks after upload only, and i have not tested on mobile apps / WEBDAV uploads.
after the below line 
` $l = \OC::$server->getL10N('files'); `

I added this 
`$allowed_types = array('.mbz','.txt','.csv','.htm','.html','.xml','.css','.doc','.docx','.xls','.xlsx','.rtf','.ppt','.pptx','.pdf','.swf','.flv','.avi','.wmv','.mov','.jpg','.jpeg','.gif','.png','.mp3','.aac','.ogg','.mov','.mp4','.mkv');

foreach ($_FILES['files']['name'] as $filename)
{
        if($filename != "")
        {

         if (preg_match('/\.([a-z0-9]+)$/i', $filename, $match))
                    if (isset($match[0]))
                        $ext = $match[0];

            if (!in_array($ext,$allowed_types)) {

             OCP\JSON::error(array('data' => array('message' => $l->t('invalid file extension!, allowed file types are .txt,.csv,.htm,.html, .xml, .css, .doc, .docx, .xls, .xlsx, .rtf, .ppt, .pptx, .pdf, .swf, .flv, .avi, .wmv, .mov, .jpg, .jpeg, .gif, .png'))));
                die();
                }
}
}
`
I am not sure how much this gonna help you. hope may be someone else can help you better.

**Comment by RealRancor** [comment]
@madhusudan 

> It works but it blocks(deletes) the file after uploading the file, that doesn't make sense for a big file, it should be blocked before upload itself, user could save some bandwidth!..

Have you considered to request this as a feature at https://github.com/musaa32/files_filter/issues

**Comment by madhusudan** [comment]
@RealRancor 

already did in owncloud.com  site

https://apps.owncloud.com/content/show.php?action=knowledgebase&content=174667

**Comment by RealRancor** [comment]
@madhusudan The issue tracker is the place for that, not the comments of an app. :-)

**Comment by carlospea** [comment]
i'm using OC 7 too, why migrating if are working fine, my life are easy as its, i nood need new features, please make it work with oc 7 wahy always upgrades and upgrades... why so more work!?

**Comment by VicDeo** [comment]
Current status of OC7 is `security fixes only`. If somebody else would like to invest their time into this I  won't mind.
Finally unsubscribing from notifications here.

**Comment by RealRancor** [comment]
Also unsubscribing. Looks also like multiple accounts from the same user posting here...
