### ISSUE TITLE
Feature Request:  ownCloud Desktop Client for Linux

### ISSUE THREAD

**Issue by greavette** [owncloud/apps#2081]
Hello,

I've recently installed the Linux ownCloud Desktop client on Lubuntu and noticed that this GUI is missing the option to 'Choose what to sync'.  I really like this feature from the Windows Client I use and would like to see this on the Linux Client.

Thank you.

**Comment by carlaschroder** [comment]
Hi @greavette, you should have a 'Choose what to sync' button on your Linux client. Which version are you running? Look on the General tab; the current version is 1.8.2. These screenshots are from my Linux Mint system.

![linux-sync-client](https://cloud.githubusercontent.com/assets/8388387/8264687/570443d4-169e-11e5-8ad8-bcf95e98458e.png)

![linux-sync-client1](https://cloud.githubusercontent.com/assets/8388387/8264689/5c11f3d0-169e-11e5-87c3-565c8c9fabc7.png)

**Comment by RealRancor** [comment]
Btw. the issue tracker of the sync client is located here:

https://github.com/owncloud/client/issues

**Comment by greavette** [comment]
Hello,

Seems I'm running version 1.5?  I added the opensuse repo for 14.04 and installed owncloud-client.  I guess I'm running an older version then?

Thanks RealRancor...I didn't realize I put this issue in the wrong place.  I'll post my question there.

Thank you.

**Comment by RealRancor** [comment]
Hi,

yes. 1.5 is an old version. The "Choose what to sync" feature was introduced in 1.7:

http://www.webupd8.org/2014/11/owncloud-client-170-released-with.html

Its also not needed to ask the question at the clients issue tracker. For such questions the forums https://forum.owncloud.org/ or the users mailinglist should be used.

**Comment by carlaschroder** [comment]
Hi @greavette, did you mean the repo for xUbuntu 14.04? At any rate I'm not sure how you got such an old version. I checked the links on openSUSE Build Service, which is where our official clients are hosted, and they look correct. To get the current desktop sync client (or any current ownCloud download) start at  https://owncloud.org/install/. I hope that helps!

**Comment by RealRancor** [comment]
Its very likely a problem with the repository priorities where the client 1.5 is pulled from the ubuntu repos instead of the one of OBS. Still i think this is an topic for the forums.
