### ISSUE TITLE
https://apps.owncloud.com/content/show.php?content=148406

### ISSUE THREAD

**Issue by enoch85** [owncloud/apps#2085]
Enabled experimental apps, and saw this in the description. Maybe not the best if you ask me.

```
DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

0. You just DO WHAT THE FUCK YOU WANT TO.
```

Is it possible to change that, or disable the app from appstore?

**Comment by karlitschek** [comment]
You mean because of the use of this four letter word?
I personally don't like words like that and I try to avoid them personally. But is is definitely not illegal to use this words in a license. So in the spirit of free speech I think we can't and shouldn't delete this app.

**Comment by MorrisJobke** [comment]
It even seems to be GPL compatible https://en.wikipedia.org/wiki/WTFPL

**Comment by enoch85** [comment]
:+1:
