### ISSUE TITLE
[files_videoviewer] X-Sendfile likely required for video streaming - to be documented

### ISSUE THREAD

**Issue by svet-b** [owncloud/apps#2087]
### Issue context
A number of users have reported video streaming with files_videoviewer not working properly (or at all) for a wide range of browser/media configurations (e.g. https://github.com/owncloud/apps/issues/2065, https://github.com/owncloud/apps/issues/2064, https://github.com/owncloud/apps/issues/1900, https://github.com/owncloud/apps/issues/1879, and elsewhere). These issues arise even in situations where the browser and media formats are otherwise compatible, and appear to be related to the way ownCloud serves files rather than the client configuration.

### Potential resolution of issue
My own search for the root cause of this indicated that enabling the X-Sendfile module on the server side is essential for getting streaming to work correctly. Since X-Sendfile gets the server (e.g. Apache) to serve the file directly - instead of feeding all of it through download.php - it enables partial downloads and seeking within media files. I've documented my configuration and the behavior experienced at https://forum.owncloud.org/viewtopic.php?f=31&t=29431

Enabling X-Sendfile on a dedicated server worked by following the instructions published at https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/serving_static_files_configuration.html - though that document does not mention any relation to video streaming.

### Recommendation
Provided that the lack of X-Sendfile is indeed a common cause for failed streaming (rather than coincidental for me), I would recommend documenting this requirement more clearly, by for example adding a mention to the files_videoviewer app description.

**Comment by RealRancor** [comment]
Hi,

you could also cross-post this to https://github.com/owncloud/documentation/issues to get it also documented within the docs.

**Comment by PVince81** [comment]
Another idea is to switch the video viewer to use the Webdav endpoint, which is based on SabreDAV which, AFAIK, supports fseek when range requests are required.

Note that X-Sendfile cannot work with encryption and external storage.

**Comment by Bugsbane** [comment]
I'm one of the people who's always had virtually no video playback. That said, I'm using Nginx, which from that documentation, is supposed to have Nginx's equivalent activated by default.

**Comment by PaulAnnekov** [comment]
I have wasted a lot amount of my time to understand this bug and even created the question on [SO](http://stackoverflow.com/q/31999168/782599).
I have nginx + php5fpm and this article in docs helped me to solve the problem: [Serving Static Files for Better Performance](https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/serving_static_files_configuration.html).
But it was not so easy to find it. Maybe you should better add some notification in "Security & setup warnings" block on Admin page of ownCloud installation? This block has helped me a lot, but not for this issue.

**Comment by Bugsbane** [comment]
@PaulAnnekov - So, Paul, you're saying that you implemented the Nginx (X-Accel-Redirect) section of those docs (either Method 1 or Method 2) and that got video to play on your ownCloud install?

I'm curious, as I have a similar setup wo you and have never managed to get video to work right, which hurts, given that my main usecase is sharing photos and videos with family.

**Comment by PaulAnnekov** [comment]
@Bugsbane 
> So, Paul, you're saying that you implemented the Nginx (X-Accel-Redirect) section of those docs (either Method 1 or Method 2) and that got video to play on your ownCloud install?

Yes.

> my main usecase is sharing photos and videos with family

The same for me.

There was 2 main issues:
1. PHP was sending static files. It does not support `Range` requests so videos were not streaming. I have fixed it by enabling `X-Accel-Redirect` feature and now nginx sends static files. I can show you my nginx config if you want.
2. moov Atom was at the end of some mp4 (avc+aac) videos. So in Chrome this video was not seekable. You can read about it here: [Streaming MP4 with Nginx](https://sixohthree.com/streaming-mp4-with-nginx)

**Comment by Bugsbane** [comment]
> I can show you my nginx config if you want.

If you wouldn't mind, of appreciate it. I'm still somewhat new to NGINX and learning the ropes re configuring things.

Thanks!

**Comment by PaulAnnekov** [comment]
@Bugsbane,

```
upstream php-handler {
  # replace it with php5-fpm's unix socket to make it faster.
  server owncloud:8080;
}

server {
  listen 80;
  server_name example.com;
  # enforce https
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name example.com;

  ssl_certificate /etc/ssl/nginx/example.crt;
  ssl_certificate_key /etc/ssl/nginx/example.key;

  # Path to the root of your installation
  root /var/www/owncloud;
  # set max upload size
  client_max_body_size 10G;
  fastcgi_buffers 64 4K;

  # Disable gzip to avoid the removal of the ETag header
  gzip off;

  rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
  rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
  rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

  index index.php;
  error_page 403 /core/templates/403.php;
  error_page 404 /core/templates/404.php;

  location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
  }

  location ~ ^/(?:\.htaccess|config|db_structure\.xml|README){
    deny all;
  }

  # Read comment about MOD_X_ACCEL_REDIRECT_ENABLED below.
  location ^~ /data {
      internal;
  }

  location / {
    # The following 2 rules are only needed with webfinger
    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

    rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
    rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

    rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

    try_files $uri $uri/ /index.php;
  }

  location ~ \.php(?:$|/) {
    include fastcgi_params;
    fastcgi_pass php-handler;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param HTTPS on;

    # Fixing bug when PHP was serving files and not nginx. Some videos was not playing in HTML5 video tag.
    # https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/serving_static_files_configuration.html
    # http://stackoverflow.com/questions/31999168/html5-video-player-does-not-play-mp4-h264-video-in-chrome
    # https://forum.owncloud.org/viewtopic.php?f=31&t=29431
    fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on;
  }

  # Optional: set long EXPIRES header on static assets
  location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
     expires 30d;
     # Optional: Don't log access to assets
     access_log off;
  }
}
```

**Comment by oparoz** [comment]
@PVince81 is correct. `Range` seeking is disabled in Files and for text previews we had to switch to the WebDav endpoint. The same thing should be done for videos.

**Comment by RealRancor** [comment]
FYI, sendfile was removed in oC8.2 https://github.com/owncloud/core/pull/18881 as discussed in https://github.com/owncloud/core/issues/18870

**Comment by PaulAnnekov** [comment]
@RealRancor so video seeking will not work any more?

**Comment by RealRancor** [comment]
Sorry, no idea. That is something you need to find out.

**Comment by PVince81** [comment]
To make video seeking work, the video viewer(s) need to use the Webdav endpoint which already supports range requests.

**Comment by Bugsbane** [comment]
And are there any video viewer apps that use Webdav endpoint? Would they still require the X-Accel-Redirect modifications to nginx's configuration?

This issue is a blocker for one of my main use cases with ownCloud (sharing personal videos with non technical friends and family who expect to be able to just press play on videos and have it "just work"), so I would be thrilled if there was an app (even experimental) that got around this.

**Comment by PaulAnnekov** [comment]
@Bugsbane the same use case for my cloud... I will not update to 8.2 until seeking will work.

**Comment by Bugsbane** [comment]
@PaulAnnekov - Not sure that holding on to 8. really helps. I've had this issue since the first release of ownCloud, right up to my current 8.1.3 install. Seems that the real fix will be either nginx config and/or a better app that uses webdav endpoints.

**Comment by PVince81** [comment]
@VicDeo how difficult would it be to make the video viewer use the Webdav endpoint ?
Here you can see how the text preview does it for text files in public link mode: https://github.com/owncloud/core/blob/v8.2RC1/apps/files_sharing/js/public.js#L116

**Comment by PVince81** [comment]
it wouldn't require x-sendfile. SabreDAV uses `fseek` on the original to find ranges.

**Comment by PVince81** [comment]
you can try changing this line's value here: https://github.com/owncloud/apps/blob/master/files_videoviewer/js/viewer.js#L57 to something like OC.linkToRemote('webdav') + OC.joinPaths(viewer.dir + file)

That would be for the non-public link mode.
In public link mode the URL would be like this one https://github.com/owncloud/core/blob/v8.2RC1/apps/files_sharing/js/public.js#L116 and you need to set the authorization headers too.

**Comment by VicDeo** [comment]
I don't know how to send custom header with mediaelementjs and doubt it is possible.
See https://github.com/owncloud/apps/issues/2111 which works for logged in users

**Comment by supportreq** [comment]
@VicDeo this change allowed viewing videos by downloading partial content. In case I want to start viewing the video from 40min, if the file is not downloaded completed it will first complete downloading all the previous 40min and than start.. Can we do something about this?

Thank You

**Comment by PVince81** [comment]
Backport pending: https://github.com/owncloud/apps/pull/2111
@VicDeo can you do it ?

**Comment by VicDeo** [comment]
@PVince81 8.2 already has it. Backport all the way down to stable7?

**Comment by VicDeo** [comment]
stable8.1: https://github.com/owncloud/apps/pull/2118
stable8: https://github.com/owncloud/apps/pull/2119

**Comment by PVince81** [comment]
Regarding public page seeking, raised https://github.com/owncloud/apps/issues/2120
