### ISSUE TITLE
Add new user automatically to group, set quota

### ISSUE THREAD

**Issue by crysman** [owncloud/apps#2088]
Hello, please, 2 things:

1) How to **set quota automatically for the first time a user logs in** (using IMAP auth)? I've added this line:
    
    OC_Preferences::setValue($uid, 'files', 'quota', '256 MB');

But that obviously changes the quota any time user logs in - I need to do it just once, by the first login. I need this hack because all my users are "registering" and logging via IMAP authentication and I need to set a "default quota" for all of such users.

2) How to make a **newly created user automatically assigned to a group** (already existing group)? Again, just once, first login.

If I knew the ownCloud API, it would be quite easy to figure out, but I do not have time to study it :/ ... somebody must easily know?!... Thanks a lot!

**Comment by crysman** [comment]
PS: I do not want (yet) anyone to actually implement it. I just need some piece of code I shall add into the `/var/www/owncloud/apps/user_external/lib/imap.php` file, thanks a lot.

**Comment by crysman** [comment]
Please, any help here? I just need information, no coding at all...

What I need is simple:
1) **userExists()** function - is there any? What is it's name?
2) **addToGroup()** function - There is obvously some. Just how to use it correctly to assign the current uid to "myfavourite" group.

I will highly appreciate help. I've already tried forum - no result. I've tried devel mailing list - no result. I've tried to contact the author of the user_external plugin himself - no result. Quite frustrated already :/ Thank you!

**Comment by MorrisJobke** [comment]
1)

```php
$config = \OC::$server->getConfig();
if($config->getUserValue($uid, 'files', 'quota') === null) {
    $config->setUserValue($uid, 'files', 'quota', '256 MB');
}
```

2)

```php
$user = \OC::$server->getUserSession()->getUser();
if($user !== null) {
    $group = \OC::$server->getGroupManager()->get('groupId');
    if(!$group->inGroup($user)) {
        $group->addUser($user);
    }
}
```

**Comment by crysman** [comment]
seems to work perfectly, many thanks, Morris!
