### ISSUE TITLE
Update 7.0.2 > 8.0.4

### ISSUE THREAD

**Issue by werthersd** [owncloud/apps#2090]
I tried to update owncloud using the automatic way and got these error warnings:

Error 	PHP 	Method OC_L10N_String::__toString() must not throw an exception at /homepages/4/d516943181/htdocs/owncloud/lib/private/defaults.php#0 	2015-07-25T11:32:59+00:00
Fatal 	index 	Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT `configvalue`, `appid` FROM `oc_appconfig` WHERE `configkey` = ?' with params ["enabled"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away 	2015-07-25T11:32:59+00:00
Error 	PHP 	PDOStatement::execute(): Error reading result set's header at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643 	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): MySQL server has gone away at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	PHP	Method OC_L10N_String::__toString() must not throw an exception at /homepages/4/d516943181/htdocs/owncloud/lib/private/defaults.php#0	2015-07-25T11:32:59+00:00
Fatal	index	Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT `configvalue`, `appid` FROM `oc_appconfig` WHERE `configkey` = ?' with params ["enabled"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): Error reading result set's header at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): MySQL server has gone away at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	PHP	Method OC_L10N_String::__toString() must not throw an exception at /homepages/4/d516943181/htdocs/owncloud/lib/private/defaults.php#0	2015-07-25T11:32:59+00:00
Fatal	index	Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT `configvalue`, `appid` FROM `oc_appconfig` WHERE `configkey` = ?' with params ["enabled"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): Error reading result set's header at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): MySQL server has gone away at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	PHP	Method OC_L10N_String::__toString() must not throw an exception at /homepages/4/d516943181/htdocs/owncloud/lib/private/defaults.php#0	2015-07-25T11:32:59+00:00
Fatal	index	Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT `configvalue`, `appid` FROM `oc_appconfig` WHERE `configkey` = ?' with params ["enabled"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): Error reading result set's header at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	PHP	PDOStatement::execute(): MySQL server has gone away at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:59+00:00
Error	updater	An exception occurred while executing 'SELECT `configvalue`, `configkey` FROM `oc_appconfig` WHERE `appid` = ?' with params ["documents"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away	2015-07-25T11:32:59+00:00
Error	updater	Something went wrong for apps. Rolling back.	2015-07-25T11:32:43+00:00
Error	PHP	PDOStatement::execute(): Error reading result set's header at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:43+00:00
Error	PHP	PDOStatement::execute(): MySQL server has gone away at /homepages/4/d516943181/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php#643	2015-07-25T11:32:43+00:00

Does anyone know what's wrong with it?

**Comment by karlitschek** [comment]
The message 'mysql has gone away' means that your mysql deamon was stopped or has crashed. Nothing we can do in ownCloud

**Comment by werthersd** [comment]
Neu aufsetzen, oder?

**Comment by RealRancor** [comment]
@werthersd Sometimes its enough to raise the MySQL timeouts like described here:

https://doc.owncloud.org/server/8.0/admin_manual/issues/index.html#common-problems-error-messages
