### ISSUE TITLE
Import of tasks to database fails when there is an emoij in the file

### ISSUE THREAD

**Issue by J-Silverbee** [owncloud/apps#2097]
I tried to upload an .ics file to my owncloud 8.1. It imports everything. But the wirte to the database is broken when there is an emoij in the TODO-item.

For example this text 
"aaike\n\n\n\nPs. Reviews volgen nog! 😃\n\n\n\nVerstuurd vanaf mijn iPhone"

becomes 

"aaike\n\n\n\nPs. Reviews volgen nog!"

in the database. Everything behind the emoij gets lost and the task+-app get stuck with this error:

Exception: {"Message":"End of document reached prematurely","Code":0,"Trace":"#0 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(168): Sabre\\VObject\\Parser\\MimeDir->readLine()\n#1 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine('BEGIN:VTODO')\n#2 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\n#4 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(142): Sabre\\VObject\\Reader::read('BEGIN:VCALENDAR...')\n#5 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n#6 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery('1', Array)\n#7 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(621): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n#8 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(231): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n#9 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/behee...')\n#10 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#15 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/apps\/calendarplus\/appinfo\/remote.php(80): Sabre\\DAV\\Server->exec()\n#17 \/home\/epique\/domains\/owncloud.epique.com\/public_html\/remote.php(132): require_once('\/home\/epique\/do...')\n#18 {main}","File":"\/home\/epique\/domains\/owncloud.epique.com\/public_html\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250}

**Comment by RealRancor** [comment]
Hi,

i think the apps issue tracker is the wrong place for this. If you think this is an issue within oC itself then you might want to re-open in by using the issue template (https://raw.githubusercontent.com/owncloud/core/master/issue_template.md):

https://github.com/owncloud/core/issues

If you think its an issue within the Calendar App (AFAIK this handles also Tasks) re-open in:

https://github.com/owncloud/calendar/issues

**Comment by RealRancor** [comment]
Ref for an existing issue in the calendar tracker: https://github.com/owncloud/calendar/issues/909

Might be related to https://github.com/owncloud/core/issues/4513
