### ISSUE TITLE
LDAP authentication fails if using AD as backend

### ISSUE THREAD

**Issue by timboven** [owncloud/apps#2100]
I was unable to connect to my owncloud instance with my active directory account.
I was able to fix this by changing the file user_ldap.php - method checkPassword.
I replaced the line `$users = $this->access->fetchUsersByLoginName($uid, $attrs);` (4th line in the method) with:
```PHP
  $filter = \OCP\Util::mb_str_replace(
                       '%uid', $uid, $this->access->connection->ldapLoginFilter, 'UTF-8');
  $filter = str_replace("%uid", $uid,  $this->access->connection->ldapLoginFilter);
  $users = $this->access->fetchListOfUsers($filter, $attrs);
```

**Comment by karlitschek** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
@timboven please fill out the issue template and report any error messages that occur: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Your first line does not have any effect, because $filter is overwritten in your second line. Then, everything else happens just the same is in the method in Access (https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/access.php#L644), **except** that you apparently do not escape the $uid. How does your login name look like?

**Comment by blizzz** [comment]
@timboven oh, and please reopen the issue with the missing information in the core repository. Thank you! https://github.com/owncloud/core

**Comment by timboven** [comment]
1) Correct the the first line doesn't have any effect - was one of my earlier attempts while checking the issue - didn't cleanup correctly
2) my login name is just 'tboven' - so a plain simple userid
3) Why open an issue against core while it seems to be caused by an app here?

**Comment by blizzz** [comment]
>  2) my login name is just 'tboven' - so a plain simple userid

Then it should work just as fine without your change.

> 3) Why open an issue against core while it seems to be caused by an app here?

Because the LDAP backend resides in core.

**Comment by timboven** [comment]
I've tested it multiple times and it never succeeded - the uid-parameter was never replaced.

I was not aware that the LDAP backend was in core while this was here - will create the ticket then on the correct place later today - thanks for pointing me in the correct direction.

**Comment by RealRancor** [comment]
@timboven If unsure where an app belongs to have a look at the folder structore on github like:

https://github.com/owncloud/apps

and:

https://github.com/owncloud/core/tree/master/apps

user_ldap which is the ldap backend is located in core for example:

https://github.com/owncloud/core/tree/master/apps/user_ldap
