### ISSUE TITLE
Files App Fails to Show Content when Gallery App and Picture App are both installed.

### ISSUE THREAD

**Issue by backandforth** [owncloud/apps#2102]
###Solved behaviour
Files App and other apps such as gallery allow viewing and modifications of saved content.

### Actual behaviour
Both apps showing no viewing or modifiable content (no directories, files, button to add directory). The options on the side bar were showing.

### Solution
Do not enable both Gallery and Picture app

### Server configuration
Ubuntu 15.04

**Web server:**
Apache 2.4.10

**Database:**
MySQL 10.0.2.20MariaDB

**PHP version:**
5.6.4

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - documents: 0.10.2
 - encryption: 1.0.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - ownnote: 1.05
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - external
 - files_external
 - galleryplus
 - user_external
 - user_ldap
 - user_webdavauth

from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxx.xx.xx.xxxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://xx.xxx.x.xx',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'xxxxxxxxx',
  'dbhost' => 'xxxxxxx',
  'dbtableprefix' => 'xxxxx',
  'dbuser' => 'xxxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxxxxx',
  'logtimezone' => 'America',
  'installed' => true,
  'loglevel' => 0,
  'logfile' => '/var/www/owncloud/data/owncloud.log',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Hi,

don't think that anyone will note this in here. The "Pictures" app is deprecated and will be replaced with the new "Gallery" app soon. Both also have their issue tracker here:

https://github.com/owncloud/gallery/issues

Normally the newer "Gallery" app should disable the "Pictures" app when enabled according to https://github.com/owncloud/gallery/issues/181#issuecomment-114142461

cc @oparoz

**Comment by oparoz** [comment]
@RealRancor is correct, Gallery+ (14+) should print a message if Pictures is still enabled.
@backandforth, please re-open [here](https://github.com/interfasys/galleryplus/issues) if that's not the case, once I release v14
