### ISSUE TITLE
Shared file scanning: File does not exists

### ISSUE THREAD

**Issue by dbeniamine** [owncloud/apps#2103]
Hello,

I use clam 0.98.7 in socket mode with ownclooud 8.1.1 and I have a weird issue:
Their is one file (file.pdf) in a shared directory (dir) from a user A to a user B that is constantly scanned in user B home by clam while it actually exists only in A's home directory ...

    {"reqId":"e7ts7fzrU2CXIvdH8E9h","remoteAddr":"","app":"files_antivirus","message":"File does not exist. File: 2023 Path: B\/files\/dir\/file.pdf","level":3,"time":"2015-09-11T01:00:24+00:00"}
    {"reqId":"e7ts7fzrU2CXIvdH8E9h","remoteAddr":"","app":"no app in context","message":"Error while running background job: ","level":3,"time":"2015-09-11T01:00:24+00:00"}

How can I tell owncloud /clam to stop trying to scan this file ?

**Comment by RealRancor** [comment]
Hi,

isn't this more something for the issue tracker of files_antivirus? https://github.com/owncloud/files_antivirus/issues

**Comment by dbeniamine** [comment]
Yes sorry, I thought that I was posting it there, I must have done some mess with my firefox tabs ...

**Comment by RealRancor** [comment]
@dbeniamine Yes, i think you can close this one.
