### ISSUE TITLE
Somebody spam the app section

### ISSUE THREAD

**Issue by Hideio** [owncloud/apps#2105]
hundreds of new entries 
https://apps.owncloud.com/
![owncloud applications - apps owncloud com](https://cloud.githubusercontent.com/assets/14086435/9975635/f2568556-5ec2-11e5-9306-5c01f09bbe80.png)

![owncloud applications - apps owncloud com 1](https://cloud.githubusercontent.com/assets/14086435/9975645/4b10988a-5ec3-11e5-8c24-966f1eee5200.png)

**Comment by karlitschek** [comment]
deleted
