### ISSUE TITLE
Update the env.global.CORE_BRANCH setting in .travis.yml

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/apps#2112]
- [x] apps: No tests
- [x] activity: https://github.com/owncloud/activity/pull/415
- [x] bookmarks: https://github.com/owncloud/bookmarks/pull/161
- [x] calendar: No `.travis.yml`
- [x] chat: No stable8.1
- [x] contacts: https://github.com/owncloud/contacts/pull/1062
- [x] documents: https://github.com/owncloud/documents/pull/557
- [x] files_antivirus: https://github.com/owncloud/files_antivirus/pull/79
- [x] files_locking: https://github.com/owncloud/files_locking/pull/45
- [x] files_pdfviewer: https://github.com/owncloud/files_pdfviewer/pull/72
- [x] files_texteditor: https://github.com/owncloud/files_texteditor/pull/129
- [x] firstrunwizard: https://github.com/owncloud/firstrunwizard/pull/34
- [x] gallery: https://github.com/owncloud/gallery/pull/436
- [x] mail: Not stable8.1
- [x] news: No stable8.1
- [x] search_lucene: https://github.com/owncloud/search_lucene/pull/110
- [x] shorty: No `.travis.yml`
- [x] tasks: No tests
- [x] templateeditor: https://github.com/owncloud/templateeditor/pull/33
- [x] updater: https://github.com/owncloud/updater/pull/181

**Comment by MorrisJobke** [comment]
All merged
