### ISSUE TITLE
App "external"

### ISSUE THREAD

**Issue by gitmas** [owncloud/apps#2114]
Hi guys

Is it somehow possible, to get a dynamic Link with the $_SERVER['HTTP_HOST'] variable? The reason I need this is, that I would like to link the AWStats for each customer seperately. For every customer, we have a unique Subdomain. This would by far the best solution for us! :)
The Link would look like this: https://$_SERVER['HTTP_HOST']/awstats/awstats.pl?config=$_SERVER['HTTP_HOST']

Or otherwise, set a Link which is only available for one group/user instead of all users

I'll appreciate any help from you guys!

Marco

**Comment by RealRancor** [comment]
Hi,

@gitmas This doesn't looks like a bug or a feature request so i think this question is better placed at the developers mailinglist:

https://mailman.owncloud.org/mailman/listinfo/devel

**Comment by MorrisJobke** [comment]
`getAbsoluteURL` of the `IURLGenerator` interface may help here https://github.com/owncloud/core/blob/0d98e5e456ed9f5ea05a6e8213b0a71da7b84075/lib/public/iurlgenerator.php#L85-85
