### ISSUE TITLE
Issues with list of mixed users (local and LDAP)

### ISSUE THREAD

**Issue by Resquer** [owncloud/apps#2116]
I have sucessfully upgraded from 8.1.3 to 8.2, and now I can not to see users in the "Users" panel. I have both local and LDAP users, and some of them are included in additional groups. If I choose some group directly, everything is OK, I can see users, but if I try to see ALL users, the spinner rotates continiously and never ends. In the error log I see "Error	PHP	Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() at /var/www/apps/user_ldap/lib/access.php#698".

**Comment by MorrisJobke** [comment]
user_ldap is a core app - please open this in core: https://github.com/owncloud/core

**Comment by shtrom** [comment]
See owncloud/core#20090
