### ISSUE TITLE
There is something wrong when I used swift as external storage

### ISSUE THREAD

**Issue by kebenxiaoming** [owncloud/apps#2117]
Recently,I use swift as external storage,it can be used normally.But something happened in owncloud.log when I upload or delete files:

{"reqId":"d60b3118a7d20f90e323463eaf1b2f49","remoteAddr":"127.0.0.1","app":"files_external","message":"Client error response\r\n[status code] 404\r\n[reason phrase] Not Found\r\n[url] http:\/\/192.168.200.188:8080\/v1\/AUTH_0fd51bb47779419e890c7320c12fbc43\/1001001166\/1.zip","level":3,"time":"2015-11-05T09:08:49+00:00"}

Maybe it's the problem of v1 authentication?

This question only happened when I upload or delete file and only happened in log;

Wait for response and THX.

**Comment by karlitschek** [comment]
Can you please reopen this issue in the core repository? thanks a lot.
