### ISSUE TITLE
Use public.php/webdav for public link videos

### ISSUE THREAD

**Issue by PVince81** [owncloud/apps#2120]
@VicDeo as discussed

This is possible since 8.2 by using the "public.php/webdav/" endpoint.
Use the share token as user id, no need to pass a password as it will use the public auth.

Since this is Webdav, Range requests should work and should make seeking possible.

**Comment by PVince81** [comment]
Requires https://github.com/owncloud/core/pull/20688

**Comment by PVince81** [comment]
For 9.0, getDownloadUrl can be used.
For previous versions, construct the URL manually.
The format is: "http://token@host/owncloud/public.php/webdav/path/to/file.avi"

**Comment by PVince81** [comment]
Hmmm, it looks like it's not enough.
Changing the JS code only affects video previews started from a public file list.
To make the embedded viewer for direct link shares, the video tag template needs to be changed on the server side: https://github.com/owncloud/core/blob/v8.2.1/apps/files_sharing/templates/public.php#L99

**Comment by PVince81** [comment]
Tentative PR here https://github.com/owncloud/apps/pull/2127
but it doesn't work due to token authentication

**Comment by mitar** [comment]
Yes, the question is how to make URLs which work for public, private, and also non-shared files. For example, [Music app](https://github.com/owncloud/music) should also use WebDav URLs, but what to use if the file is private, and has not yet been shared, but you want to play it in a player where you do not want to embed username and password of the user in.

**Comment by PVince81** [comment]
@mitar that's probably a completely different topic/approach. I think eventually ownCloud core should support authentication tokens and then maybe you can create a public URL that uses your own token to access the file directly.

**Comment by PVince81** [comment]
Obsolete, range requests will work in 9.0 thanks to https://github.com/owncloud/core/pull/24750
