### ISSUE TITLE
Playing a video locks the file and doesn't unlock it when it stops.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/apps#2121]
### Steps to reproduce

1.- Upload a video.
2.- Reproduce it.
3.- Jump to the middle of the video, clicking in the time slider.
4.- Close the video player.
5.- Move the video file into a folder.

### Expected behaviour
Video is played correctly, file is moved to the folder.

### Actual behaviour
Video is played correctly and when moving the file you are not allowed because it is locked. (A warning message appears).

### Server configuration

Operating system:
Ubuntu 14.04

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.1.0","versionstring":"8.2.1 RC1","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
Fresh

List of activated apps:
Default in enterprise edition.

The content of config/config.php:

Are you using external storage, if yes which one: local/smb/sftp/...
No

Are you using encryption: 
No

Logs

Client configuration

browser
Chrome 41, Firefox

**Comment by SergioBertolinSG** [comment]
cc @PVince81 @icewind1991

**Comment by PVince81** [comment]
I wonder if the mediaelement isn't closing the network connection properly @VicDeo

**Comment by PVince81** [comment]
@SergioBertolinSG did you stop the video or just pause it ?
Does it unlock if you switch away or close the browser tab ?

Also check the network console and find the video stream connection. I think the video player probably keeps the connection open in case you unpause. As long as the network connection is open, the file will be locked and it is expected so that no one can for example delete the file while someone is still reading it.

**Comment by SergioBertolinSG** [comment]
I closed the video viewer and moved the file.
When closing the tab it gets unlocked yes.

**Comment by PVince81** [comment]
@icewind1991 and I tried on our environments (both Firefox), seeked a bit, then closed the player.
It was still possible to move/delete the file.

**Comment by PVince81** [comment]
If closing the tab works, then it means that the browser still had a network connection, maybe still streaming a bit. It's more a bug of the video player then or the library it uses.

Locking works as expected, as long as the connection is open.

Mind opening a ticket in https://github.com/owncloud/apps for the video player ?

CC @VicDeo
