### ISSUE TITLE
Gallery does not show images in Firefox 

### ISSUE THREAD

**Issue by flowolf** [owncloud/apps#2123]
when using the gallery app (index.php/apps/gallery/) Firefox never shows any Images.
I'll just see the wheel of death. 
![screenshot from 2015-11-25 16 10 36](https://cloud.githubusercontent.com/assets/900893/11400704/23bf1058-938f-11e5-90f3-690d047f00ae.png)
I'm using Firefox 42.0 on Ubuntu 14.04.3.
The same app seems to work fine under Chromium (45.0.2454.101 Ubuntu 14.04 (64-bit))
The Owncloud version seems to be 8.0.4.

**Comment by MorrisJobke** [comment]
Is there anything in the web developer console (press F12 and switch to the console tab - also the network tab would be of interest)

**Comment by flowolf** [comment]
yes.
seems to be a problem with content security policy...
![screenshot from 2015-11-25 16 24 43](https://cloud.githubusercontent.com/assets/900893/11401072/0eaf9b9a-9391-11e5-98f0-5ab9a7b9b8cc.png)

**Comment by MorrisJobke** [comment]
@LukasReschke sorry to get you in this, but are these the default csp rules? Or does this look like additional ones from a web server?

**Comment by LukasReschke** [comment]
> @LukasReschke sorry to get you in this, but are these the default csp rules? Or does this look like additional ones from a web server?

This is due to a recent behavioural change in Firefox. Please do update to ownCloud 8.1.x at least. I dont think we should backport such changes considering that Gallery is anyways sub-par in 8.0…

**Comment by LukasReschke** [comment]
Closing from my PoV. Please update.

**Comment by flowolf** [comment]
Didn't work with 8.1.4.

8.2.1 works. thanks
