### ISSUE TITLE
"Invalid Argument Exception" error when tried to create thumbnails for the Gallery + app 

### ISSUE THREAD

**Issue by Biopticon** [owncloud/apps#2130]
Hello,

I enabled Gallery+ application. I opened the Gallery+ page. After a long hour glass activity, it said "No pictures found. Upload new pictures in the files..." So I tried to create picture thumbnails manually by issuing the following command:

sudo -u www-data ./occ gallery:create-thumbnails --path=/media/OwnCloud/data/user/files/documents/Music

But I get the following error:

  [InvalidArgumentException]
  There are no commands defined in the "gallery" namespace.

What's wrong? How can I make Gallery+ app to index the pictures in the "/media/OwnCloud/data/user/files/documents/Music" directory (at an external drive)?

**Comment by MorrisJobke** [comment]
Please reopen this in the gallery+ bug tracker: https://github.com/owncloud/gallery/issues
