### ISSUE TITLE
error files_locking free: Released locks on

### ISSUE THREAD

**Issue by TheKaban** [owncloud/apps#2134]
Hi friends!
Please tell me what to do with this error:

Debug files_locking FREE: Released locks on /cloud/data/gusev/cache/Terr1r0ri9.2015.O.WEB-DLRip.1.46.avi-chunking-4113678890-233.C0LJJuIQkIpQlU1E.part

Why you may receive this error?
How this error can be corrected?

Thank you!

**Comment by MorrisJobke** [comment]
This is not an error, but a debug log. You can set the log level to something higher to avoid such messages. This is just information to be able to better debug possible problems. Beside that it can be ignored.
