### ISSUE TITLE
Activity app: "remote user" did something

### ISSUE THREAD

**Issue by alve89** [owncloud/apps#2141]
### Affected apps
Activity

### Expected behavior
Displayed activity: remote_user@another-domain.tld created xyz.pdf

### Actual behaviour
Displayed activity: "remote user" created xyz.pdf

### Steps to reproduce
1. Share a directory with an external user: remote_user@another-domain.tld
2. This user does something within his own account in the external cloud

### Server configuration
Operating system: Linux 3.13.0-77 Ubuntu

Web server: Apache 2.0

Database: MySQL 5.0.11

PHP version: 5.6.17

ownCloud version: 8.2.2

### Client configuration
Browser: Safari 9.0.2

Operating system: Mac OS 10.11.2

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
Not sure if relevant:
Error	PHP	Undefined index: HTTP_USER_AGENT at /www/htdocs/w013f149/cloud/LIVE/lib/private/appframework/http/request.php#678

#### Browser log
```

**Comment by RealRancor** [comment]
@alve89 Could you re-open in https://github.com/owncloud/activity/issues where the issue tracker of the activity app is located

**Comment by alve89** [comment]
Can I directly do this or just copy-paste?

**Comment by RealRancor** [comment]
@alve89 Unfortunately github doesn't allow to move issue so closing this issue and opening a new one is needed.
