### ISSUE TITLE
Multiple Google Drive accounts as External Storage all direct to the same account

### ISSUE THREAD

**Issue by benmichael** [owncloud/apps#2144]
### Affected apps
External Storage

### Expected behaviour
- If I add n Google Drive accounts as external storage
- I should have n external storage directories
- 1 per Google Drive account.

### Actual behaviour
- I have n external storage directories
- They all contain the contents of the same Google Drive account

### Steps to reproduce
1. Add a Google Drive account
2. Add another Google Drive account
3. Browse to External Storage
4. Inspect the contents of each Google Drive mount, they are the same.  (They should be different)
5. Let your Client Sync the external storage
6. Inspect the contents of each synced Google Drive directory, they are the same. (They should be different)

### Server configuration
Operating system: Ubuntu Linux 14.04

Web server: Apache2

Database: MariaDB

PHP version: 5.5

ownCloud version: 8.1.3

### Client configuration
Browser: Google Chrome 48

Operating system: Ubuntu Linux 14.04

**Comment by MorrisJobke** [comment]
Hi @benmichael - files_external is one of the few core apps. Please reopen this in the core bug tracker https://github.com/owncloud/core/issues

Thanks
