### ISSUE TITLE
SFTP External Storage not showing all directories on slow connection

### ISSUE THREAD

**Issue by benmichael** [owncloud/apps#2145]
### Affected apps
External Storage

### Expected behaviour
When I browse to sftp external storage, I should see all my directories.  If the connection is too slow, the directories may be loaded asynchronously, but then there should be a "still loading" indicator.

### Actual behaviour
I see a subset of my directories

### Steps to reproduce
1. Create SFTP external storage
2. The SFTP server/mount point directory should have at least 30 directories/files
3. The connection to the SFTP should be slow (500kbps up)
4. Browse to the SFTP external storage directory
5. Inspect for missing directories/files

### Server configuration
Operating system: Ubuntu Linux 14.04

Web server: Apache2

Database: MariaDB

PHP version: 5.5

ownCloud version: 8.1.3

**Comment by MorrisJobke** [comment]
Hi @benmichael - files_external is one of the few core apps. Please reopen this in the core bug tracker https://github.com/owncloud/core/issues

Thanks
