### ISSUE TITLE
Specify mounting point of external storages

### ISSUE THREAD

**Issue by alve89** [owncloud/apps#2148]
### Affected apps
Files External

### Expected behavior
In http://cloud.tld/index.php/settings/[admin/personal] under "External Storage" you should be able to set a mounting point (e.g. an existing folder within the cloud or the root directory).

### Actual behavior
External storages are always mounted in the root directory.

### Server configuration
Operating system: Ubuntu 3.13

Web server: Apache 2

Database: MySQL 5.0.11

PHP version: 5.6.17

ownCloud version:8.2.2

### Comments
That's a pity - especially if you have a several external storages you want to share with other users - it was so much more efficient to mount these storages within a shared folder rather than share all storages again manually.

**Comment by MorrisJobke** [comment]
Hi @alve89 

The files_external app is one of the few core apps. Could I ask you to open this issue in the core bug tracker?

Thanks

https://github.com/owncloud/core/issues

**Comment by alve89** [comment]
Alright, thank you.
