### ISSUE TITLE
Update the env.global.CORE_BRANCH setting in .travis.yml

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/apps#2149]
- [x] apps: No tests
- [x] activity: https://github.com/owncloud/activity/pull/469
- [x] announcementcenter: https://github.com/owncloud/announcementcenter/pull/51
- [x] bookmarks: https://github.com/owncloud/bookmarks/pull/228
- [x] calendar: https://github.com/owncloud/calendar/pull/257
- [x] chat: No stable9
- [x] contacts: https://github.com/owncloud/contacts/pull/77
- [x] documents: https://github.com/owncloud/documents/pull/613
- [x] files_antivirus: https://github.com/owncloud/files_antivirus/pull/90
- [x] files_locking: https://github.com/owncloud/files_locking/pull/48
- [x] files_pdfviewer: https://github.com/owncloud/files_pdfviewer/pull/100
- [x] files_texteditor: https://github.com/owncloud/files_texteditor/pull/166
- [x] files_videoplayer: No tests
- [x] firstrunwizard: https://github.com/owncloud/firstrunwizard/pull/41
- [x] gallery: https://github.com/owncloud/gallery/pull/552
- [x] mail: No stable9
- [x] news: No stable9
- [x] notifications: https://github.com/owncloud/notifications/pull/70
- [ ] search_lucene: https://github.com/owncloud/search_lucene/pull/116
- [x] shorty: No travis
- [x] tasks: No tests
- [x] templateeditor: https://github.com/owncloud/templateeditor/pull/38
- [x] updater: No ownCloud on tests

**Comment by nickvergessen** [comment]
Any new app I forgot?

**Comment by cmonteroluque** [comment]
files_videoplayer?
files_videoviewer?
user_external?

**Comment by nickvergessen** [comment]
> files_videoplayer?

Has no tests

> files_videoviewer?
> user_external?

Those are part of the apps repo which doesn't have tests.

**Comment by cmonteroluque** [comment]
ok thanks. Nothing I can think of then

**Comment by MorrisJobke** [comment]
search lucene was moved to 9.0.1 -> closing this
