### ISSUE TITLE
External sites images should be stored in theme

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/apps#2154]
Ref https://github.com/owncloud/core/issues/22982#issuecomment-194154351

cc @cmonteroluque Can you also create the milestones for this repo? THX.

**Comment by pirate** [comment]
Is it possible for the integrity check code to just exclude the image files fetched in `settings/external.php`?

`settings/external.php`:
```php
$images = glob(\OC_App::getAppPath('external') . '/img/*.*');
```

**Comment by VicDeo** [comment]
1. use app-theme, app-themes support was added in https://github.com/owncloud/apps/pull/2226
2. exclude app-theme from integrity check

closing is fixed
