### ISSUE TITLE
caldav not working with windows 10 mobile due to wrong useragent in sabre-dav

### ISSUE THREAD

**Issue by mer-at** [owncloud/apps#2161]
### Affected apps
Tell us which app(s) you are talking about
CALDAV sync with Windows Phone 10(Calendar)

### Expected behaviour
Tell us what should happen
it should sync

### Actual behaviour
Tell us what happens instead
it doesnt sync
ownCloud version: 9.0

i'll just post the solution:
update your sabre-dav library you are using for owncloud according to: https://github.com/fruux/sabre-dav/issues/727
That fixes issues with the useragent of WP10

**Comment by RealRancor** [comment]
@mer-at No need to open here. This is a core issue where upgrading to SabreDAV 3.1 including that fix is already planned for oC 9.1: https://github.com/owncloud/core/issues/22724

**Comment by MorrisJobke** [comment]
Core issue -> closing this one here
