### ISSUE TITLE
Can't upgrade to 8.2.3 - PHP - Cross Device Issue

### ISSUE THREAD

**Issue by fedev** [owncloud/apps#2164]
### Affected apps
Owncloud upgrade from 8.2.2 to 8.2.3

### Expected behaviour
Clicking on Update should update to new release

### Actual behaviour
This has been reported in the past and fixed before apparently. The issue happens when PHP is trying to rename folders across devices.

I'm running Owncloud in a Docker container:

https://hub.docker.com/_/owncloud/

as recommended, it is suggested to have Apps, Config and Data on the host and not the container itself. That places these folders on another device which prevents the upgrade from taking place.

It is worth mentioning I've been able to upgrade this container before so it must be something new.

### Steps to reproduce
1. Click on Update 
2. See it fail
3. 

### Server configuration
Operating system: Debian GNU/Linux 8 (jessie)

Web server: Apache 2

Database: Mariadb

PHP version: 5.6.17

ownCloud version: 8.2.2

#### ownCloud log (data/owncloud.log)
Error 	updater 	Unable to move /var/www/html/apps/external to /var/www/html/_oc-upgrade/tmp/apps/external 	2016-03-30T00:29:18+00:00
Error 	updater 	Something went wrong for apps. Rolling back. 	2016-03-30T00:29:16+00:00
Error 	PHP 	rename(/var/www/html/apps/external,/var/www/html/_oc-upgrade/tmp/apps/external): Invalid cross-device link at /var/www/html/apps/updater/lib/helper.php#52 	2016-03-30T00:29:16+00:00

**Comment by MorrisJobke** [comment]
This is something that needs to be handled by the docker container maintainers. Please report this in https://github.com/docker-library/official-images/issues

**Comment by fedev** [comment]
Wouldn't it be the same issue if I set this up manually and not in a container? If I were to use different subvolumes or different partitions?

What I mean is, if this is a PHP issue. Won't it happen anyway? Could we perhaps have another way to run the upgrade? Like writing on a custom folder for example?
