### ISSUE TITLE
external storage app fails on ssl openstack endpoint

### ISSUE THREAD

**Issue by stefanost67** [owncloud/apps#2165]
### Affected apps
External Storage Support

### Expected behaviour
- swift storage is configured
- container is created via owncloud
- files can be uploaded
- images can be previewed
- files can be downloaded with no corruption

### Actual behaviour

Everything is fine if the obiect storage authentication endpoint and storage endpoint are not ssl protected (e.g. http://.........), if the obiect storage authentication endpoint and storage endpoint are
ssl protected (e.g. https://....., but the CA certificate is known system wide) the following happens:

- swift storage is configured
- container is created via owncloud
- files can be uploaded (integrity verified with swift client)
- downloads are corrupt: an html file, always the same, is downloaded with the name of the original file
![img_3339](https://cloud.githubusercontent.com/assets/10981270/14140556/f92524d8-f679-11e5-9321-4704f02ce18f.jpg)
 
### Steps to reproduce
1. install owncloud
2. enable external support app
3. configure swift storage with (authentication and storage endpoints are https://......)

### Server configuration
Operating system:
fresh and up to date ubuntu 14.04 
Web server: 
apache2 2.4.7-1ubuntu4.9
Database:
mysql-server-5.5 5.5.47-0ubuntu0.14.04.1
PHP version:
php5 5.5.9+dfsg-1ubuntu4.14
ownCloud version:
owncloud 9.0.0-2.1
### Client configuration
Browser:
up to date chrome and up to date firefox
Operating system:
ubuntu 14.04

#### Web server error log

no errors reported, following the entry in access.log

172.17.9.62 - - [30/Mar/2016:13:27:31 +0200] "GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2Fslabs&files=IMG_3339.jpg&downloadStartSecret=tp5ug3bpjvuvoujqxqeabgldi HTTP/1.1" 200 11445 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

#### ownCloud log (data/owncloud.log)

{"reqId":"avezeh0VLu0\/Tda\/Wwqb","remoteAddr":"172.17.9.62","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/3rdparty\/guzzle\/stream\/Guzzle\/Stream\/PhpStreamRequestFactory.php#268","level":3,"time":"2016-03-30T11:27:32+00:00"}
{"reqId":"avezeh0VLu0\/Tda\/Wwqb","remoteAddr":"172.17.9.62","app":"no app in context","message":"Exception: {\"Exception\":\"Guzzle\\\\Common\\\\Exception\\\\RuntimeException\",\"Message\":\"Error creating resource.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php(218): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->createResource(Object(Closure))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php(62): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->createStream(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/swift.php(332): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->fromRequest(Object(Guzzle\\\\Http\\\\Message\\\\Request))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(287): OC\\\\Files\\\\Storage\\\\Swift->fopen('IMG_3339.jpg', 'r')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(313): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('IMG_3339.jpg', 'r')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(287): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('IMG_3339.jpg', 'r')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/permissionsmask.php(110): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('IMG_3339.jpg', 'r')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(811): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->fopen('IMG_3339.jpg', 'r')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(879): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->readFirstBlock('IMG_3339.jpg')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(358): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('IMG_3339.jpg')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(287): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('IMG_3339.jpg', 'rb')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1057): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('IMG_3339.jpg', 'rb')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(905): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/slabs\\\/IMG_3339...', Array, 'rb')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(409): OC\\\\Files\\\\View->fopen('\\\/slabs\\\/IMG_3339...', 'rb')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(184): OC\\\\Files\\\\View->readfile('\\\/slabs\\\/IMG_3339...')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(89): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/slabs', 'IMG_3339.jpg', false)\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/slabs', Array, false)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 [internal function]: __lambda_func(Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func('?lambda_1549', Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php\",\"Line\":271}","level":3,"time":"2016-03-30T11:27:32+00:00"}

#### Browser log

resource interpreted as Document but transferred with MIME type image/jpeg: "http://cloud141.lngs.infn.it/owncloud/index.php/apps/files/ajax/download.ph…%2Fslabs&files=IMG_3339.jpg&downloadStartSecret=e7qdeiohl5hydxg84efes1c3di".
OC.redirect	@	js.js?v=81d7901…:234
Files.handleDownload	@	files.js?v=81d7901…:315
FileList._onClickDownloadSelected	@	filelist.js?v=81d7901…:659
x.event.dispatch	@	jquery.min.js?v=81d7901…:5
v.handle	@	jquery.min.js?v=81d7901…:5

**Comment by RealRancor** [comment]
@stefanost67 The files_external is part of core so you might want to re-open in https://github.com/owncloud/core/issues

**Comment by PVince81** [comment]
Please reopen in core, thanks
