### ISSUE TITLE
[Feature Request] Always open firstrunwizard after login

### ISSUE THREAD

**Issue by balduin-kowalski** [owncloud/apps#2176]
Is there a way to open the firstrunwizard after every login? By default it opens only after the very first login of a new user.

I want to display news for the users and like to use the firstrunwizard to display them.

Already did a lot of research about this topic, but couldn´t find any working solutions.

**Comment by MorrisJobke** [comment]
For news the announcement center app should be used https://github.com/owncloud/announcementcenter

**Comment by balduin-kowalski** [comment]
Thanks for the tip. But I need a message in a lightbox coming up after every login and the firstrunwizard already opens in a lightbox. So I guess it is easier to make the firstrunwizard to open after every login, than to fiddle a lightbox around the announcement center.
