### ISSUE TITLE
still no support for deletion of a single occurence of a repeated event

### ISSUE THREAD

**Issue by baumanager** [owncloud/apps#2187]
### Affected apps
OC Calendar

### Expected behaviour
Deletion of one event in a series should allow the options:
1. Delete only this occurrence
2. Delete this and the following occurrences
3. Delete whole series

### Actual behaviour
Deletion of one event deletes entire series

### Steps to reproduce
see #320

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

### Client configuration
Browser:

Operating system:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@baumanager The issue tracker of the calendar app is located here: https://github.com/owncloud/calendar/issues

Please re-open the issue there after you had a search for existing issues at that repository
