### ISSUE TITLE
Segate Personal Storage Cloud (arm7) update fault

### ISSUE THREAD

**Issue by armisis** [owncloud/apps#2190]
### Affected apps
Update App

### Expected behaviour
owncloud should update

### Actual behaviour
Upgrade is not possible. Make sure that your webserver has write access to the following files and directories:

/var/www/owncloud/3rdparty
/var/www/owncloud/3rdparty/Archive
/var/www/owncloud/3rdparty/Console
/var/www/owncloud/3rdparty/Jcrop
/var/www/owncloud/3rdparty/LICENSE INFO
/var/www/owncloud/3rdparty/MDB2.php
/var/www/owncloud/3rdparty/OS
/var/www/owncloud/3rdparty/PEAR
/var/www/owncloud/3rdparty/PEAR-LICENSE
/var/www/owncloud/3rdparty/PEAR.php
/var/www/owncloud/3rdparty/PEAR5.php
/var/www/owncloud/3rdparty/Patchwork
/var/www/owncloud/3rdparty/Pimple
/var/www/owncloud/3rdparty/Sabre
/var/www/owncloud/3rdparty/System.php
/var/www/owncloud/3rdparty/XML
/var/www/owncloud/3rdparty/class.phpmailer.php
/var/www/owncloud/3rdparty/class.smtp.php
/var/www/owncloud/3rdparty/css
/var/www/owncloud/3rdparty/doctrine
/var/www/owncloud/3rdparty/fontawesome
/var/www/owncloud/3rdparty/getid3
/var/www/owncloud/3rdparty/js
/var/www/owncloud/3rdparty/mediawiki
/var/www/owncloud/3rdparty/miniColors
/var/www/owncloud/3rdparty/patches.txt
/var/www/owncloud/3rdparty/phpass
/var/www/owncloud/3rdparty/symfony
/var/www/owncloud/3rdparty/timepicker
/var/www/owncloud/3rdparty/zxcvbn
/var/www/owncloud
/var/www/owncloud/.htaccess
/var/www/owncloud/console.php
/var/www/owncloud/core
/var/www/owncloud/cron.php
/var/www/owncloud/db_structure.xml
/var/www/owncloud/index.html
/var/www/owncloud/index.php
/var/www/owncloud/l10n
/var/www/owncloud/lib
/var/www/owncloud/occ
/var/www/owncloud/ocs
/var/www/owncloud/public.php
/var/www/owncloud/remote.php
/var/www/owncloud/robots.txt
/var/www/owncloud/search
/var/www/owncloud/settings
/var/www/owncloud/status.php
/var/www/owncloud/version.php
/var/www/owncloud/themes
/var/www/owncloud/apps/gallery
/var/www/owncloud/apps/files_encryption
/var/www/owncloud/apps/user_webdavauth
/var/www/owncloud/apps/files_pdfviewer
/var/www/owncloud/apps/files_trashbin
/var/www/owncloud/apps/files_external
/var/www/owncloud/apps/tasks
/var/www/owncloud/apps/search_lucene
/var/www/owncloud/apps/calendar
/var/www/owncloud/apps/files_videoviewer
/var/www/owncloud/apps/contacts
/var/www/owncloud/apps/external
/var/www/owncloud/apps/activity
/var/www/owncloud/apps/files_sharing
/var/www/owncloud/apps/admin_dependencies_chk
/var/www/owncloud/apps/documents
/var/www/owncloud/apps/files_texteditor
/var/www/owncloud/apps/updater
/var/www/owncloud/apps/user_ldap
/var/www/owncloud/apps/firstrunwizard
/var/www/owncloud/apps/bookmarks
/var/www/owncloud/apps/user_external
/var/www/owncloud/apps/files
/var/www/owncloud/apps/files_versions

Please fix this and retry.

The update was unsuccessful. Please check logs at admin page and report this issue to the ownCloud community.

### Steps to reproduce
1. attempt update

### Server configuration
Operating system: Seagate Personal Storage Cloud

**Comment by RealRancor** [comment]
@armisis

So whats the issue here? The message is clearly stating whats wrong (permissions wrong).

Please close here and use https://central.owncloud.org/ for such support questions.
