### ISSUE TITLE
Access class methods of other apps

### ISSUE THREAD

**Issue by alve89** [owncloud/apps#2206]
Is it possible to access (public) class methods or properties of other apps from within an app? If yes - how?

**Comment by kdslkdsaldsal** [comment]
@alve89 Please note this is a bugtracker. For questions (especially development specific) use either:

https://central.owncloud.org/c/development

or:

https://mailman.owncloud.org/mailman/listinfo/devel

**Comment by PVince81** [comment]
No. In general inter-app dependencies are not supported as they are highly unreliable.

Now if you know the namespace of an app you might be able to hack your way through...

Closing as this is not a place to ask dev questions.
