### ISSUE TITLE
calendar app Certificate has been revoked

### ISSUE THREAD

**Issue by localguru** [owncloud/apps#2215]
OC 9.0.10

After upgrading from 8.2 to 9.0 I get the following error on calendar app.

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
```

This problem is bothering a lot of people

https://apps.owncloud.com/content/show.php?content=168707&forumpage=8

And see https://github.com/nextcloud/calendar/issues/498  too

**Comment by VicDeo** [comment]
@localguru thanks for reporting this.
Disclaimer: I'm not a  maintainer of this app just watching all new issues here.
The right place to report calendar issues is a calendar repo :) 
And it seems this issue is already known https://github.com/owncloud/calendar/issues/800
