### ISSUE TITLE
owncloud folder erased if you run device maintenance

### ISSUE THREAD

**Issue by Lioxen** [owncloud/apps#2220]
### Affected apps
android owncloud client
maybe only on samsung devices with android >= 7

### Expected behaviour
the owncloud folder should not be erased if I start the device maintenance

### Actual behaviour
the owncloud folder will be erased if you run the device maintenance

### Steps to reproduce
1. install the android owncloud client on your android device
2. sync some files so the owncloud folder will be created
3. start the device maintenance
4. the owncloud folder is disappeared and the client has to sync everything again
I do not know if this is a samsung app or also in the stock adroid availible. I also have only the german naming and translated it. (Einstellungen->Gerätewartung)

### alternative  Steps to reproduce
to see that this happens only with the owncloud app installed follow this instructions. It is important, that the owncloud app is **not installed** in the first place!
1. if you do not have one, install a file manager (e.g. Amaze)
2. open the file manager and go to your sdcard folder
3. create a folder named "owncloud" and copy some files into it (important: this files will be erased)
4. start the device maintenance under settings
5. reopen the file manager, the owncloud folder should still exist
6. now install the owncloud client
7. start the device maintenance under settings again
8. reopen the file manager, now the owncloud folder is disappeared

### Server configuration
this is not relevant for this error

### Client configuration
Operating system: android 7 or later

**Comment by PVince81** [comment]
@Lioxen please reopen in the android repo: https://github.com/owncloud/android

Thanks!
