### ISSUE TITLE
App: user_external with IMAP auth does not work from within the owncloud client

### ISSUE THREAD

**Issue by mmccarn** [owncloud/apps#302]
After configuration user_external to allow IMAP auth to the owncloud web interface I am unable to configure the owncloud client.

I resolved this issue as follows:

1) Create the new user in the oc_users table manually:
 #mysql owncloud
insert into oc_users (uid,password) values ('imapuser','*');

2) Login to the web interface as 'imapuser' and change my password to match the password on the IMAP server.

I conclude from this that the owncloud client authenticates only against the internal user database.

ownCloud client, version 1.1.2
ownCloud v4.5.4

**Comment by crysman** [comment]
Hello, please, how to make a newly created user automatically assigned to a group (already existing group)?

I am trying to figure it out myself, but no luck :/ and this thread seems to be a right one to ask.

I need something like

           if ! (userExists($uid)) {
               addToGroup($uid, "myfavouritegroupname");
           }

But I do not know the names and parameters of real functions (if present?)

Thanks a lot!
Using ownCloud 8.0.x

**Comment by mmccarn** [comment]
Here are the relevent bits of the code I'm using.  

Your code seems to be saying "if the user does not exist then add him/her to "myfavoritegroupname".  You need to create the user before you add them to the group.

My code runs 'createGroup' before running 'addToGroup'; my guess is that I stole this construction from another authenticator.

```...
+	private $gid;
+	private $uida;
...
+		$this->uida=explode('@',strtolower($uid),2);
+		$this->gid=$this->uida[1];
...
+
+                        /**
+                        * Create a group for each domain
+                        */
+			OC_Group::createGroup($this->gid);
+			OC_Group::addToGroup($uid, $this->gid);
+
...
 			return $uid;
```

**Comment by crysman** [comment]
I am not creating any user, I am using IMAP authentication ("user_external") plugin... There is this line in the plugin source:

    $this->storeUser($uid);

but I do not know what storeUser() function does.

What I do **need is the userExists()** function - any available?

**Comment by crysman** [comment]
I may add a user to a group via

    OC_Group::addToGroup($uid, "myfavouritegroup");

Is that correct?
