### ISSUE TITLE
Calendar: Cannot delete a single occurence of a repeated event

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/apps#320]
In the webinterface, a repeating event can only be deleted as a whole- clicking on the "Delete" button for a repeating event simply deletes all occurences. What would be nice is the option to delete a single occurence of the event (like e.g. google calendar provides the option to do) - i.e. create an exception to the repeated event.

**Comment by KingCrunch** [comment]
Hi @georgehrke 

The linked issue #33 doesn't look like a duplicate of this one :confused: A simple warning isn't very helpful, if you _want_ to edit single instances.
