### ISSUE TITLE
Support for Reminders

### ISSUE THREAD

**Issue by georgehrke** [owncloud/apps#34]
Support reminders in calendar app

**Comment by yasokuhl** [comment]
+1

**Comment by Superheld** [comment]
no alarm-function or reminders on smartphones until now? :( 
-1

**Comment by DanielBadri** [comment]
Any news on this?

**Comment by brauliobo** [comment]
+1, any news?

**Comment by cidious** [comment]
:+1: +1

**Comment by DeepDiver1975** [comment]
Please reopen in calendar repo is still valid - THX
