### ISSUE TITLE
ODT Viewer - Display document in full width

### ISSUE THREAD

**Issue by onny** [owncloud/apps#348]
Hi,
I'm using the latest OwnCloud version (4.5.1) and noticed, that the ODTviewer does not adopt to smaller screen resolutions (mine is 1024x768).
In LibreOffice, the document looks like this: http://image.bayimg.com/d710140a969901ecb3d4cce12702e0bfa538d02c.jpg
Whereas OwnCloud won't resize the document to full width or won't handle line breaks correctly:
http://image.bayimg.com/a295925bc5aba6f028f44ebac8f69fafae404926.jpg

Best regards,
onny

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the documents repo
