### ISSUE TITLE
Safari: text in file editor is not scrollable 

### ISSUE THREAD

**Issue by MTRichards** [owncloud/apps#364]
Transferred from Bug Genie: http://bugs.owncloud.org/thebuggenie/owncloud/issues/oc-1962

Confirmed on Mac and iPad with Safari. Works on Windows Safari and Firefox as it should.

Description:
In Safari is not possible to scroll through long text in the file editor.

Own Cloud 4.5, Safari 6.0.1

Reproduction steps:
Open a long txt file and try to scroll through it on a Mac.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the texteditor repo
