### ISSUE TITLE
No settings dialogue for Pictures section

### ISSUE THREAD

**Issue by philomatic** [owncloud/apps#373]
Regarding to this:

http://bugs.owncloud.org/thebuggenie/owncloud/issues/oc-319

There should be an options/settings dialogue for the Pictures section (a.o. to exclude folders from scanning).

However, this settings dialogue doesn't appear in my ownCloud webinterface (see attached image).

Any ideas?
![noGalleryOptions](https://f.cloud.github.com/assets/1078945/24426/cf454a98-4aa7-11e2-9866-ec81915bd1a7.PNG)

**Comment by DeepDiver1975** [comment]
Please reopen in gallery repo is still valid - THX
