### ISSUE TITLE
[calendar] allow undoing event deletion

### ISSUE THREAD

**Issue by ghost** [owncloud/apps#409]
The title says it all. Users should be able to undo deletion of an event in the calendar app

A similar feature is available in the "files" app, where a banner "file deleted. Undo" appears after deleting a file.

Calendar events may contain valuable data such as phone numbers, addresses or important comments. Since deleting an event is just one click away, an "undo last action" feature would be very useful.

Thanks

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
