### ISSUE TITLE
Public link for calendars.

### ISSUE THREAD

**Issue by Hayholten** [owncloud/apps#411]
Hello!
It seems that with the lastest versions of OwnCloud, the option to get a public link for sharing calendars has disappeared! On olders versions, the option was simply reachable by one click (see picture).
How can we get back this precious option?
Thanks!
![241368test](https://f.cloud.github.com/assets/3150194/35482/ad6411ec-5200-11e2-88fb-fddcb84b493a.jpg)

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.

**Comment by georgehrke** [comment]
https://github.com/owncloud/core/issues/22735
