### ISSUE TITLE
For further versions: embedded calendar...

### ISSUE THREAD

**Issue by Hayholten** [owncloud/apps#412]
Hello!
OwnCloud is just the best for managing cloud. But, it miss a precious option according to me. It will be great to get the possibility to export/ embed a chosen calendar on a HTML website (like the iFrame way of Google for example).
Do you think that it could be developped in the future?
Thanks for reply!

**Comment by law** [comment]
+1

**Comment by rysiekpl** [comment]
[I have implemented this a year ago](https://github.com/owncloud/calendar/pull/308), and [it still has not been merged](https://github.com/owncloud/calendar/pull/440). Apparently, [it also isn't going to get in ownCloud 8](https://github.com/owncloud/calendar/pull/440#issuecomment-68790060).

**Comment by law** [comment]
That is deeply unfortunate.  Is there anything we, the non coding users of owncloud, can do to help push this along?

**Comment by krueuw** [comment]
Hayholten is already waiting for two years and we waiting with her/him. This function was already in early versions implemented, later deleted - why??? Then from rysiekpl reimplemented / newimplemented - and not merged in V7 - and now not in V8 - waste of time. Owncloud seems ill - a hard word, but good organisation is a other think. What can we now do? For ever V6 with a fix?

**Comment by georgehrke** [comment]
> later deleted - why?

Because we moved the common sharing api of ownCloud. Additionally there were no embedded calendars, only public sharing. 

> and not merged in V7 

Because the UI of the Pull request was completely broken and we hadn't had enough time to fix it. 

>  and now not in V8

There are generally no new features in the calendar in ownCloud 8, because we don't have enough human resources for that.

> What can we now do?

Try to get more people involved with calendar development.

**Comment by alexdor** [comment]
@georgehrke We would like to implement the embedded calendar feature, can it be done using the api or do we have to modify the source code?

**Comment by georgehrke** [comment]
First https://github.com/owncloud/calendar/pull/440 needs to be fixed and merged. We can't talk embedded calendars before.

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
