### ISSUE TITLE
Theme Creator/Viewer for ownCloud

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/apps#415]
I haven't been introduced to creating themes for ownCloud yet but wouldn't it be great if the user get the right to tweak with the colors of the navigation panel, fonts used, and other basic layout stuff. 
On a later stage, we can also include live viewing of various themes user created and saved on the cloud allowing him to choose from one, similar to what we have in CMSes like WordPress. 
Is this possible? I mean we can do a lot with this app in terms of features. What do you guys think?

**Comment by jancborchardt** [comment]
If someone wants to go for a graphical editor, they can go for it and write an app. I wouldn’t say this is something we should do in core though. Theming is pretty simple for the ones who want to do it, especially when 8.1 is released with the new example theme. :)
