### ISSUE TITLE
Auto-Completion in Title

### ISSUE THREAD

**Issue by blizzz** [owncloud/apps#424]
Sometimes calendar entries you do are very similar to older ones, like appointments for doctors, hairdresser or likes. Instead of typing all of it into the title field again and again it would be nifty if the app remembers often used entry titles and offers them as auto-completion.

@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
Yo @blizzz can you reopen that in the Calendar repo? I support this request! :D

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
