### ISSUE TITLE
Wrong Time if sharing an calendar entry

### ISSUE THREAD

**Issue by sk800s** [owncloud/apps#425]
If you set time in an entry of an calendar z.b. 16:00 an you share this entry with an other user, the other user see 15:00 in his preview. If the other user open this entry - here ist the time right. (Version is 4.5.5)

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
