### ISSUE TITLE
External Storage Swift works with OpenStack Keystone authentication?

### ISSUE THREAD

**Issue by diwakartimilsina** [owncloud/apps#432]
Hi,
      I have a Swift cluster that is hooked up with OpenStack Keystone authentication. Does ownCloud work with Keystone based authentication? I have noticed the following difference between Swift based authentication URL and Keystone based authentication URL.

http://192.168.0.15:8080/auth/v1.0 (Swift authentication)

http://192.168.0.15:5000/v2.0 (Keystone based authentication)

Looks like php-opencloud PHP library is able to authenticate with Keystone:

https://github.com/rackspace/php-opencloud

Any feedback is appreciated.

Thanks.

**Comment by butonic** [comment]
https://github.com/owncloud/core/issues/2419 has been closed, reopen that PR if you still cannot connect via keystone.
