### ISSUE TITLE
Location view on the calendar

### ISSUE THREAD

**Issue by laurencedv** [owncloud/apps#452]
I use the calendar mainly for school i need to see the location of each event. The only way i know of is to click on the event ,edit it and than click on advance. It would be neat that we could see it on the "large" view directly in the calendar view, a bit like google calendar show it.
Even more neat would be to have settings to edit the default view in the calendar but that's a lot more.

Anyways just a feature request :) keep up the awesome work!

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
