### ISSUE TITLE
Wrong track order for OGG files in music player

### ISSUE THREAD

**Issue by edappere** [owncloud/apps#458]
In OwnCloud's music player all my OGG files are sorted by alphabetical order and not by track number. This doesn't happen for mp3 files created by the same software (in that case XCFA on Ubuntu).

As a reference I'm using Owncloud 4.5.4 with Media app 0.4.3

**Comment by icewind1991** [comment]
If this issue is still valid with the 8.2 media player please reopen in the music repo
