### ISSUE TITLE
Calendar title does not show date correctly in russian locale

### ISSUE THREAD

**Issue by zeldigas** [owncloud/apps#491]
Owncloud version 1.5.4.

* Select russian language in personal
* Go to internal calendar app 
* select a month display mode ("Месяц" in russian locale) and look at title field (a field between switching arrows)

Expected behaviour: there is a month description according to selected in calendar i.e. Январь, Февраль...

Actual behaviour: 
There is "MMMM yyyy" ("ММММ гггг" in russian locale) date formatting placeholder instead. A problem field is marked with yellow on screenshot below:
![calendar-bug](https://f.cloud.github.com/assets/749858/110544/6b9f4816-6ac5-11e2-8d29-1ea8415d8be6.png)

Week mode and list mode work fine, there is a correct date periods:
![calendar-correct](https://f.cloud.github.com/assets/749858/110562/0e04ae2a-6ac6-11e2-8ccd-6b46e27c112c.png)

**Comment by DeepDiver1975** [comment]
Please reopen in calendar repo is still valid - THX
