### ISSUE TITLE
Calendar Feature request: option to avoid conflicts

### ISSUE THREAD

**Issue by kfthier** [owncloud/apps#508]
For some calendars (room booking, resource allocation, ...) it would be useful to automatically avoid conflicts by not allowing overlapping events. This could be implemented as an option in the individual calendar settings.

**Comment by sualko** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
