### ISSUE TITLE
External storage openstack swift doesn't mount

### ISSUE THREAD

**Issue by MTRichards** [owncloud/apps#53]
Activate the ownCloud swift connector, and point to rackspace cloudfiles authentication url, using username and password.  Add mount and folder gets created inside my ownCloud. Replace the "root" with the container name.

Error log says "unexpected error ()" and then nothing else happens.  When I click on the mounted folder inside the web client, it simply reloads the main ownCloud page.

opensuse 12.2, 4.5.1a, firefox on windows.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the core repo
