### ISSUE TITLE
New features for Calender App

### ISSUE THREAD

**Issue by VisithaB** [owncloud/apps#549]
Hi All,

As undergraduates of Computer Science and Engineering, University of Moratuwa, we created a feature for the calender app. Currently a user can create an event on the calendar and he can share it with other users. We implemented a feature to send emails to recipients when user shares an event. The email will contain the information about the owner of event, Time, Date, Location, etc. And currently when an event is being shared (eg. Meeting), a message will be displayed on the calendar of others with whom the file is being shared. We added two buttons "Confirm" and "Reject" on that message. When user clicks on the Confirm button, a value will be stored in database and when the event owner sees again his shared event, he will see the shared users and their confirmation or rejection with a check box. 

We tested the email functionality with a gmail account and it worked successfully. First we had to do some configurations in the php.ini file and added gmail server, port, gmail account user name and password there. And we added new field "Email" to the user creation page by Admin. Then at the user creation, admin have to give the email of user together with user name and password. That email will be stored in the "oc_users" table. And the email will be sent according to the email addresses of that table. 

And in the event confirmation functionality, we added new column "confirm" to the "oc_share" table and keep a value to determine the user confirmation. 

What are the things we should follow to add those features to the main repository? Please send us the steps we should follow to add those changes in calendar app.

And we can give more details about these functionalities and the files where we did the changes. Please give your valuable ideas about these two features and the things we should improve.

Thanks in advance..!!

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
