### ISSUE TITLE
files_odfviewer OwnCloud V4.5.6

### ISSUE THREAD

**Issue by debug-ch** [owncloud/apps#551]
Displaying .ods Files will be truncated at the End. The last few Lines are missing.
A Test-Page using the installed .js and .css Files will be displayed correctly.

Trucated:
![Truncated](https://f.cloud.github.com/assets/3531407/144802/9479847a-743b-11e2-9e7b-ae4db5688af8.png)

Sample Output:
![Sample](https://f.cloud.github.com/assets/3531407/144808/f4b710d2-743b-11e2-8113-16683f39ea81.png)

Thomas Müller (@DeepDiver1975) has the Information already.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the documents repo
