### ISSUE TITLE
Show task due date in Calendar

### ISSUE THREAD

**Issue by diederikdehaas** [owncloud/apps#56]
In Kontact (KDE-PIM) the tasks/todo items are shown in the calendar view. In ownCloud there's something similar with birthdates of contacts.
What I like to see is the tasks integrated into the calendar, so I can see in the calendar when a task is due.

**Comment by imasen** [comment]
What about this feature?

It would be great to see this.

**Comment by 4oo4** [comment]
Agreed, it would be extremely handy to have them integrated. Implementing this is above my head but I would be willing to help anyone to get this rolling.

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
