### ISSUE TITLE
shared address books are not syncable on Mac OS X 10.8

### ISSUE THREAD

**Issue by shezi** [owncloud/apps#562]
### Expected behaviour

In Mac OS X Address Book, I am adding a CardDav account to be synced. I expect to use either groups or the CardDAV link for the specific address book I am using and to see these contacts.
### Actual behaviour

When adding a contacts/CardDAV account to the Address Book in Mac OS X 10.8, only the contacts in the general group are synchronized. It is not possible in Mac OS X to reach any of the contacts in a group that is not the main group, because the URLs get changed once the account is added, and reverted to the main principal link.

I know that this is a fault in Apple's CardDAV sync client, but it makes the shared contacts feature in ownCloud pretty much useless for me.

There should be a way to add other contact groups to the Apple Address Book sync, for example with a different principal URL or any kind of workaround.
### Steps to reproduce
1. Create a new address book in ownCloud and add at least one card.
2. Set up Mac OS X 10.8 Address Book CardDAV account with the link for this group.
3. The actual server link used by MacOS is the principal address book in ownCloud, which does not contain the card created in step 1.
### Server configuration

Operating system: Mac OS X 10.8

ownCloud version: 4.5.6

**Comment by poggenpower** [comment]
Here a workaround, if you have two address books in one owncloud account.
- Create a dummy account. 
- Export the address book with the later alphabetic order to the dummy account.
- In the dummy account delete the default address book or ensure that the imported address book has higher alphabetic order. 
- Add the a new account for the dummy user to your Contacts app. 
Hope this helps.
