### ISSUE TITLE
Calendar: No events shown if one item has invalid data

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/apps#58]
Through an import of an ics file from google calendar, somehow there came to be some invalid data in one event in the calendardata field of my calendar_objects table. Specifically, the "Created" field contained a timestamp considered invalid by Sabre (00001231T000000Z). The effect was that for the one month containing this event, the whole calendar did not show any event in the month view of the web interface, and not even an error message as to why the calendar remained empty - only in the apache error log there was an according entry. Even after correcting the faulty data in the database, the calendar did not immediately show the events (due to some owncloud-internal caching?). Clearing the apc cache and restarting the (apache) server helped nothing; only after entering a new event in the same month, the calendar was reloaded.

See also this forum thread: http://forum.owncloud.org/viewtopic.php?f=3&t=4686

I understand that invalid data shouldn't be in the calendar in the first place;  what would be nice, however, would be if ideally all of the following four things would happen: (a) in case of such faulty data, an error should be shown indicating that there's a problem with the data and with what specific event; (b) all other events which don't have faulty data should be shown normally and (c) there should be some possibility to properly reload the calendar from the database. (d) on import, the data is checked, invalid data is reported (with details on which event exactly is invalid), and possibly providing ways to fill the invalid fields with default data - so that a huge import doesn't fail just because one or a few events have some (as in my case, rather irrelevant) invalid data. (Haven't tested calendar import recently, so one or all of the things mentioned in (d) could already happen, I will retest).

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
