### ISSUE TITLE
Calendar doesn't resize with window

### ISSUE THREAD

**Issue by tanghus** [owncloud/apps#592]
### Expected behaviour
When resizing the browser the fullcalendar should also be resized

### Actual behaviour
The calendar size stays the same.
### Steps to reproduce
1. Open the calendar app in a "small" browser window.
2. Resize or maximize the browser window.

ownCloud version:
master pulled 2013-02-17  00:15 GMT+1

### Client configuration
Browser:
Chromium Version 24.0.1312.56 Ubuntu 12.10
Firefox 18.0.2

**Comment by jancborchardt** [comment]
This is fixed since some time now. :)
