### ISSUE TITLE
Search Lucene Memory Problem

### ISSUE THREAD

**Issue by JoachimKunz** [owncloud/apps#611]
Hi,

i have a problem with search_lucene. If Lucene create the index, it stops after a while, because it runs out of memory.
I have already assigned the ownCloud Instance 1.5 GB of memory.
### Server configuration

Operating system: Ubuntu 12.04.2 LTS

Web server: Apache2

Database: MySQL 5.5.29

PHP version: PHP 5.3.10

ownCloud version: 5.0 alpha 1
### Client configuration

Browser: Waterfox 18.0.1

Operating system: Windows 7 Pro SP1 64Bit
#### Web server error log

```
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 957188042 bytes) in /opt/owncloud5-test/apps/search_lucene/3rdparty/pdf2text.php on line 74, referer: https://.../owncloud5-test/index.php/apps/files
```

**Comment by despens** [comment]
Have the same problem ownCloud 7.0.4 (stable)
