### ISSUE TITLE
Viewing birthdays taking place on 29.02. on non leap years

### ISSUE THREAD

**Issue by dryo** [owncloud/apps#635]
No showstopper but a friendloser ;)

If a contact has a birthday on 29.02. of a leap year it comes to problems when showing birthdays in the calendar if the year you are looking at is no leap year.

In most calendars I know these birthdays are shown on 01.03. In ownCloud they are not shown at all. So it's likely you lose a friend. :D

**Comment by jancborchardt** [comment]
@dryo if this still occurs, please reopen this in the Calendar app repository: https://github.com/owncloud/calendar/issues :)
