### ISSUE TITLE
  Error message Invalid VObject. Document ended prematurely.

### ISSUE THREAD

**Issue by Kjukju** [owncloud/apps#687]
While using the owncloud calendar I get this error message after entering a new date to a calender:

_Invalid VObject. Document ended prematurely._

It does not matter if I enter the new date within the owncloud web interface or with a calender app on iPhone using caldav sync.

The entry is made in the DB table _oc_calendar_objects correctly_. If I add a new date to a different calender there will be no problems. The date is added correctly. I cannot solve the problem by creating a new calender and add a date to this new calender.

Owncloud version: 4.5.7
DB: MySQL on Linux Apache
PHP version: 5.3.3

**Comment by JimLoose** [comment]
It's not fixed!!!

I have ownCloud 7.0.4 (stable) + a lot of entries with:
`Invalid VObject. Document ended prematurely.`

My problem is, that the Calendar sync seems to work flawless with OSX Yosemite and iOS 8.
But i miss a lot of calendar entries in my iOS 8 Calendar :(

**Comment by jancborchardt** [comment]
@JimLoose first, sorry for the problems. Can you open a new issue in the [Calendar issue tracker](https://github.com/owncloud/calendar/issues) and use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) to supply the needed info? Thanks!

**Comment by JimLoose** [comment]
@jancborchardt 
i unfortunately have no time to dive into the bug that deep! I already dropped OwnCloud Calendar! Sorry!

**Comment by joefidler** [comment]
Yes I agree this error occured for us last Friday and is not fixed. I am still trying to gather information on the error but its probably a corruption in a calendar database - which resulted in the database being not syncable from CalDav clients (web access was OK) - giving the document premature end message - very bad. I was running on a shared host so have only found a HTTP log file so far which does not show the error. Wish there were more diagnostic tools within Owncloud itself, and tools to "clean up" or repair a broken database. We have since switched away from OwnCloud until I can figure out what happened, and hopefully open a bug report. Too bad after a month of trialing OwnCloud, we liked it.

**Comment by georgehrke** [comment]
@joefidler This error means that the calendar-data itself is broken. If you enable the debug mode you'll get more information including the id of the object so you can check what's broken with the calendar-data

**Comment by joefidler** [comment]
Thanks @georgehrke for the reponse. Unfortunately I deleted the OwnCloud instance and created a new one trying to get things working again. The only thing I have left of the failed OwnCloud is the MySQL database itself. I tried poking around in that with phpMyAdmin but really have no idea how to look at data with that tool. 

The only hard information I have was that the most effected data was a Tasks calendar database  - using the third-party tasks app (https://apps.owncloud.com/content/show.php/Tasks?content=164356). This database was accessed from the Android CalDav Tasks app (https://play.google.com/store/apps/details?id=org.dmfs.tasks&hl=en). When this tasks data was lost it also effected CalDav access to the calendar associated with it, but I was still able to access this via (and download it) via the web. 

I have no other logs etc to analyse, the tasks calendar database was completely lost. Its possible that this error was caused by the Tasks app + CalDav Sync on Android - and its their bug - or there was some data loss over the network connection. But for me the bottom line is that a corruption in data should not cause a crashed, unusable, lost database on the OwnCloud server side. That seems like its not only a reliabity issue but maybe even a potential security issue.

**Comment by georgehrke** [comment]
> But for me the bottom line is that a corruption in data should not cause a crashed, unusable, lost database on the OwnCloud server side. 

The __whole__ database is __not__ lost. It's an error message, that's supposed to tell you that certain events are broken. The calendar is (/ should) still be accessible, even though it contains broken data.

**Comment by joefidler** [comment]
Agreed the data is still in the database, but after we saw the Invalid Object message we could no longer access that Tasks data by any method. The tasks data from that calendar no longer displayed on the web client and gave errors to the CavDav clients. Other calenders and tasks lists were still accesible. I also could not export the data - to recreate a new calendar, so for us that portion (agreed not the whole) of the database  was lost.

**Comment by georgehrke** [comment]
> The tasks data from that calendar no longer displayed on the web client

That's a bug in task app and not directly related to the calendar, please report a bug there.

>  gave errors to the CavDav clients. 

That seems to be a bug in the calendar. please report a new bug in the calendar repo using the issue template jan [mentioned above](https://github.com/owncloud/apps/issues/687#issuecomment-69814630)
If the data is not too sensitive, please attach an example for broken data.

**Comment by joefidler** [comment]
Agreed there is probably a bug in the task app which caused the problem which I will try to followup there. Will also to try and find the broken data in the calendar data and post and an issue report for that.

**Comment by JimLoose** [comment]
i bet we have attachments or geolocation or comments in the original imported mac os calendar (which supports all that)

**Comment by georgehrke** [comment]
> i bet we have attachments or geolocation or comments in the original imported mac os calendar (which supports all that)

we also support all that. 
```Error message Invalid VObject. Document ended prematurely.``` means that the calendar-data is broken and ended unexpectedly. If that's the case OS X calendar should also not be able to parse it.

**Comment by JimLoose** [comment]
OS X + iCloud works flawless

**Comment by georgehrke** [comment]
There might still be an issue with 4-byte unicode chars, although I was sure a fix was merged in core ...

**Comment by joefidler** [comment]
For what its worth we use (used) a mix of Android (4.4.4) with CalDAV, and Linux (OpenSUSE) with Thunderbird and SoGo connector  for clients. No OS X.

**Comment by JimLoose** [comment]
could somebody please reopen this bug, until we have a better bugreport?
(this one is quite difficult to hunt)

**Comment by joefidler** [comment]
To test things I uploaded an exported copy of the "broken" calendar to a fresh OwnCloud database. No calendar data including tasks was lost, and I could not find any funny chars or corrupted data etc. The fact that I was able to restore all the data from the tasks list was surprising - the failed database was functional enough to export an intact ics file.

**Comment by disy-mk** [comment]
Same issue here; maybe the problem of not being unable to share my calendar has is to be credited back to this issue.

**Comment by georgehrke** [comment]
please try to gather as many information about the broken calendar-data as possible. Just saying that you have the same issue doesn't really help if you don't provide example data.

**Comment by disy-mk** [comment]
Well of course I will; I just need someone to point out how to find out which vobject id causes the problem (c.f. the reference above my post)

**Comment by georgehrke** [comment]
enable the debug mode and use the calendar. Some debug notices with information about the id should be logged

**Comment by disy-mk** [comment]
I did (set log level to 0). This is the log:

```
{"reqId":"54c0de4e42cf7","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:06+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de4e42cf7","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:06+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de5a52573","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-22T11:26:18+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54c0de6a74f6d","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:34+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de6a74f6d","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:34+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de6b9b982","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-22T11:26:35+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54c0de775451d","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:47+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de775451d","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:47+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de827f83e","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:58+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de827f83e","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:58+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de8cb897b","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:08+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de8cb897b","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:27:08+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de97d2755","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:19+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de97d2755","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:27:19+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0dea2babb6","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:30+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0dea2babb6","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:27:30+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0df0104804","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-22T11:29:05+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
```

**Comment by JimLoose** [comment]
Could somebody please reopen this issue?

**Comment by georgehrke** [comment]
@JimLoose no, this is the wrong repo and @disy-mk already created a new issue in the calendar repo.

**Comment by seraphyn** [comment]
CentOS 7 with owncloud 8 running in a subdomain with SSL startssl singed.
(Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16)
DavDROID on Android is 0.6.11.
Android is CM 11 M12
WebDav CAL URL is https://beautifulcentosServer/remote.php/webcal/
WebDav Contact full working.
3 Calenders, mine default one persönlich (I think that it could be the Name of the calender :  https://NICEcentosServer/remote.php/caldav/calendars/chris/pers%C3%B6nlich) , family shared, tasks for android and ios.

journalctl --follow  with loglevel 2 gave me 
```
Feb 15 18:30:02 Servername ownCloud[4328]: {PHP} Undefined index: REQUEST_URI at /var/www/html/owncloud/apps/calendar/appinfo/app.php#41
Feb 15 18:30:15 Servername ownCloud[1170]: {vobject} Invalid VObject. Document ended prematurely.
```
audit.log have nothing in it, everything allright with SELinux.
No PHPCache or anything switched on, just deflate as extra.


config.php with loglevel 0 to owncloud.log gave me
```
{"reqId":"da6cc386da34038d2d91371e5f355f01","remoteAddr":"MYIP","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-02-15T18:43:26+01:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/chris\/familie\/"}
{"reqId":"aaadaae871d0940591832c1f7e2b15cc","remoteAddr":"MYIP","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-02-15T18:43:40+01:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/chris\/familie\/"}
```
One time we have had a :  
```
{"reqId":"16feb239b6a6aa53c164267d83121616","remoteAddr":"MYIP","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(123): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(103): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-02-15T18:46:50+01:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
```

access.log
```
MYIP - chris [15/Feb/2015:18:55:23 +0100] "PROPFIND /remote.php/caldav/calendars/chris/familie/ HTTP/1.1" 207 52757 "-" "DAVdroid/0.6.11"
myIP - chris [15/Feb/2015:18:55:28 +0100] "REPORT /remote.php/caldav/calendars/chris/familie/ HTTP/1.1" 404 267 "-" "DAVdroid/0.6.11"
```
And now to the funny thing.
Persönlich at one account to sync :+1: 
Familie at one account does not sync :-1: 
```
MYIP - chris [15/Feb/2015:19:09:15 +0100] "REPORT /remote.php/caldav/calendars/chris/familie/ HTTP/1.1" 207 27881 "-" "DAVdroid/0.6.11"
MYIP - chris [15/Feb/2015:19:09:25 +0100] "REPORT /remote.php/caldav/calendars/chris/familie/ HTTP/1.1" 207 27448 "-" "DAVdroid/0.6.11"
MYIP - chris [15/Feb/2015:19:09:34 +0100] "REPORT /remote.php/caldav/calendars/chris/familie/ HTTP/1.1" 404 267 "-" "DAVdroid/0.6.11"
```

So, should I delete Familie to reimport it, or set up a new one?
In my opinion, the Error does come from a damaged calender, but what is my opnion here, I do not have any idea about this type of code ;)

And one important thing. Familie is the only one with emojis from iOS for the important things of my son.
Hope it helps

**Comment by cquike** [comment]
I am also having a similar issue with Owncloud 8.1. @georgehrke: your link to the new issue is broken, could you please post the correct one?

**Comment by georgehrke** [comment]
Well, you asked, here it is: https://github.com/owncloudarchive/calendar/issues/680

But it won't be of much help, because every version of the calendar app prior to ownCloud 9 is unsupported and there won't be any bugfix releases.

**Comment by Quantentunnel** [comment]
Working with owncloud 8.2, I had the same issue. The error appears with one of my 5 calendars. The calendar still works with the owncloud web-interface. So I looked on the table in the mysql database. I found only one event which were created on the day before. So I deleted it with phpmyadmin and after that, it worked again. The event was created with miCal on iOS 10. The event is in September 2018 and now we have February 2017. 
Maybe these information helps you to fix the error.

**Comment by PVince81** [comment]
@Quantentunnel did that event have a syntax error in it ?

From what I heard, future versions of OC (and Sabre library) will be more robust in regards to syntax errors.

**Comment by Quantentunnel** [comment]
@PVince81 
I don´t know. There was signal why I choosed this event. It was only the last inserted event in owncloud calendar.

But now 24 hours later the same error occurs again. Now I am trying to upgrade from 8.2 to 9.0. I don´t know why but nearly every owncloud update and upgrade crashed. My only plugin is the calendar. So I guess this will happen again and I need some time until I give you more feedback and tell you if the upgrade was/is the solution.

**Comment by Quantentunnel** [comment]
The upgrade from 8.2 over 9.0 to 9.1 works quicker than I expected. Only one error after the upgrade: https://github.com/owncloud/calendar/issues/771
And no fatal error after upgrading. That is a new record!

Currently it is working. Let´s see what will happen in 24 hours. I keep you informed.

**Comment by Quantentunnel** [comment]
Nearly 24 hours later, the calendar still works!

The solution seems to be:
1. Upgrade to owncloud 9.1 (if you use 8.2 please upgrade first of all to 9.0 and then to 9.1!!)
2. Activate the "Share Files" plugin
3. Follow the instruction to update the "Share Files" plugin
4. Check if the "Share Files" plugin is really actived.
