### ISSUE TITLE
warning: Very Large images should not be viewed inside the web interface.

### ISSUE THREAD

**Issue by arm2arm** [owncloud/apps#718]
Picture viewer tries to load in to clients browser the full sized image this causes Browser hang, in the end if you don't have enough memory computer starting to swap. one need to kill browser to stop the process.

I had a few large images in my folder starting from 16000x16000 up to 48000x48000. The sync was successful!!! impressed by sync performance bravo!!

BTW same with Text Editor, if you click to very large TXT/LOG file you should stop browser.

**Comment by jancborchardt** [comment]
If this still occurs, we should fix this in the Gallery+ app https://github.com/owncloud/galleryplus cc @oparoz for reference.

**Comment by oparoz** [comment]
Gallery downloads a thumbnails which fits the screen, nothing bigger.

**Comment by jancborchardt** [comment]
AWESOME!
