### ISSUE TITLE
Picture App: MYSQL: Integrity constraint violation

### ISSUE THREAD

**Issue by mmattel** [owncloud/apps#739]
Ubuntu 12.04, oC from github master (core, apps, 3rdparty) from today, mysql
Ubuntu mounted drives via smb
oC installed from scratch, enabled app: external storage support, added 4 drives as folders, granted to the user (not group)
There is no data in the users root !

Clicking into pictures I get multiple errors in owncloud.log like below

{"app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/mnt\/www\/owncloud\/lib\/image.php#477","level":2,"time":1363100447}

{"app":"PHP","message":"file_get_contents(\/mnt\/www\/owncloud\/data\/mmattel\/files\/mnt\/smb\/bilder_public\/Import\/Weihnachten 08\/2008-02-05_07-47-16_DSC3706.NEF): failed to open stream: No such file or directory at \/mnt\/www\/owncloud\/lib\/files\/storage
\/local.php#110","level":2,"time":1363100448}

{"app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/mnt\/www\/owncloud\/lib\/image.php#477","level":2,"time":1363100448}

{"app":"PHP","message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-60c8440d67eb234ae1d914a5bcb60f6e' for key 'fs_storage_path_hash' at \/mnt\/www\/owncloud\/lib\/db.php#963","level":4,"time":1363103049}

{"app":"PHP","message":"Undefined offset: 1 at \/mnt\/www\/owncloud\/apps\/gallery\/ajax\/gallery.php#12","level":2,"time":1363103051}

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the gallery repo
