### ISSUE TITLE
Request: Encryption of Contact/Calendar database

### ISSUE THREAD

**Issue by farson2003** [owncloud/apps#744]
In short:
We all know these contact/calendar entries both contain very private information.
To my knowledge right now contacts / calendars can't be encrypted, mainly because this must be supported by the CalDAV / CardDAV clients (see this old bugreport by Rancor: http://bugs.owncloud.org/thebuggenie/ow ... es/oc-1444)

Would it be possible for clients to communicate not directly with Owncloud’s CalDAV / CardDAV system, but with an intermediary system that “translates” the encrypted information from ownloud to unencrypted/understandable information before transmission to the client?

I can imagne this is of high interest for all potential users who want to implement a “well secured/encrypted Ownclud installation”, not just for their files, but for all their data.

So that is a feature request, in case it is possible.

**Comment by CoRoe** [comment]
Contacts and calendar entries could be encrypted. Encryption has to be syntax-aware: Keywords in the clear, values encrypted:

> ADR;TYPE=home:;;Heidestrasse 17;Koeln;;51147;Germany

would then become something like this:

> ADR;TYPE=home:;;hjkhjhqwe87934h 485;ruc48d;;25489;dfndsr0l1

In an analogous way for other keywords.

Works only with clients that that are aware of this encryption method, and that share the encryption key. 

Open points:

- Will Google and the like accept records with this garbled content?
- Does this scheme still leak information?

**Comment by bam80** [comment]
>we want that you can access your calendar and contacts with any carddav/caldav client

No need. Encryption is more important here. Other than that, it could be implemented as an option.

**Comment by CoRoe** [comment]
One could insert a proxy between a 'normal' client and the server, with the proxy handling the encryption. The proxy can run on the client system (mobile, laptop, etc.)

**Comment by bam80** [comment]
@CoRoe Such 'proxy' already exists for EteSync server: https://github.com/etesync/etesync-dav. Unfortunately, it doesn't support DAV servers..

**Comment by tasn** [comment]
@bam80 what do you mean by it doesn't support DAV servers? EteSync-dav is a proxy between EteSync and DAV clients, it is a DAV server.

I'm the author of EteSync-dav.

**Comment by bam80** [comment]
@tasn I mean, it doesn't support usual DAV server on it's server side - only EteSync server supported. This is the kind of proxy we were talking about here

**Comment by tanghus** [comment]
>> we want that you can access your calendar and contacts with any carddav/caldav client.

> No need. Encryption is more important here. Other than that, it could be implemented as an option.
If Card-/CalDAV compliance is not important, you might as well invent your own "standard".
