### ISSUE TITLE
OC 5.0.0 Video player crash in full screen mode.

### ISSUE THREAD

**Issue by w4zu** [owncloud/apps#755]
Hello guys.
i like use a video player, but in 5.0.0 dont work in full screen mode, and i am forced to restart apache2 web server.

Video :

File type : .FLV
Size : 57Mo

Steps to reproduce
Play video and click for Full Screen mode.

Same with VideoViewer 0.1.1 and Video player 0.2.

Server configuration

Operating system: Debian 6.0.7

Web server: apache2
PHP Version : 5.3.3-7
Database: mysql

ownCloud version: 5.0.0

sorry for my english.

**Comment by icewind1991** [comment]
if this issue is still valid please reopen in the videos repo
