### ISSUE TITLE
Show color in calendar list

### ISSUE THREAD

**Issue by peteruithoven** [owncloud/apps#763]
Currently it's hard to find which calendar corresponds to which calendar. My simple suggestion would be to show the color of a calendar in the calendar list: 
![Screen shot 2013-03-15 at 1 56 41 AM](https://f.cloud.github.com/assets/523210/261958/7924595a-8d0b-11e2-8fca-51ef99644a52.png)

This can currently be done (very hacky) by adding the following into the second _td_ of _apps/calendar/templates/part.choosecalendar.rowfields.php_

```html
<div style="background: <?php echo $_['calendar']['calendarcolor'] ?>;width:0.5em; height:1em; margin:0.3em 0.3em 0 0; float:left"></div> 
```

**Comment by jancborchardt** [comment]
This is done in the sidebar in the rework. Closing the issue in this old repository.
