### ISSUE TITLE
Can´t skip images in shared folder

### ISSUE THREAD

**Issue by cyberdaemon** [owncloud/apps#773]
### Expected behaviour
To be able to skip images directly in the image viewer when browsing images in a shared folder

### Actual behaviour
The image viewer doesn´t have a button previous/next in shared folder 

### Steps to reproduce
1. share a folder with images 
2. click on a image
3. for the next image you have to close the viewer

### Server configuration
Operating system: Centos 5.9 

Web server: Apache 2.2.3

Database: MySQL 5

PHP version: 5.4

ownCloud version: 5.0

### Client configuration
Browser: none

Operating system: Android 

#### Web server error log
```
none 
```

#### ownCloud log (data/owncloud.log)
```
none 
```

**Comment by icewind1991** [comment]
If this issue is still valid please repen in the gallery repo
