### ISSUE TITLE
Visible Cursor position does not move in Task Title Field (Chromium)

### ISSUE THREAD

**Issue by GuRaX** [owncloud/apps#782]
When edit a task title and move the cursor back or forward with the arrow keys the visible cursor does not move. Only when the mouse enter or leave the field the real position is updated and visible.

I'm using Chromium Version 25.0.1364.172 (187217). In Firefox 19.0.2 the bug does not appear.
I just updated from 4.5.1 and using now v5.0(current stable).

**Comment by icewind1991** [comment]
If this problem is still valid please reopen in the tasks repo
