### ISSUE TITLE
Bookmarks : unable to click import, or bookmarklet in chromium

### ISSUE THREAD

**Issue by davesgonechina** [owncloud/apps#792]
The Bookmarks Settings menu doesn't open, and neither "Read Later" nor "You can also try to import a bookmark file" are links when viewing OC 5.0.0 with Chromium in Ubuntu 12.10, only an image and an underlined sentence. These problems do not occur in Firefox, where the settings menu pops up when clicked and the Read Later and import links are active. Nothing appears in the log when I click on these areas in Chromium.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the bookmarks repo
