### ISSUE TITLE
Daylight saving time: problem with recurring events (v5.0)

### ISSUE THREAD

**Issue by Marvodor** [owncloud/apps#806]
On March 31, the „daylight saving time“ starts in Germany. A recurring event, scheduled for 08:00 every Saturday from March to April is shown with the right time in March but at 9:00 in April. 
It looks as if the event was stored in UTC and displayed in local time. The expected behavior would have been that the event is being scheduled at the same local time for every instance.

![DST issue ownCloud v5 0](https://f.cloud.github.com/assets/3908609/275229/09866690-9082-11e2-8870-6d29c790172c.png)

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
