### ISSUE TITLE
Pictures: not apparent how to add pictures

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/apps#82]
As pictures is essentially just a frontend to all the pictures in the Files app, it’s not apparent how to get started or add pictures.

To fix this, the top bar in the Pictures app should have an upload button just like Files. This then just uploads it to the folder inside Files.

**Comment by jancborchardt** [comment]
cc @libasys & @oparoz on this issue. This has been the prime complaint and problem in usability tests with the Pictures app. (No, not more settings. ;)

**Comment by oparoz** [comment]
Yep, an upload button shouldn't be a problem, but for drag and drop we would need the whole upload mechanism to be moved to public functions or create our own, which would probably be a nightmare since it seems you were forced to write your own

**Comment by jancborchardt** [comment]
@oparoz for now an upload button is fine. We can do drag&drop later. :)

**Comment by oparoz** [comment]
I've had a look and it's the same problem if using an upload button. All the JS we need is in the Files app, so we can't access it.

**Comment by libasys** [comment]
no that is not the problem you get the upload functionality with:
```
script('files', 'jquery.fileupload');
```
and as example form html
```
<form style="display:none;" class="float" id="file_upload_form" action="<?php print_unescaped(\OCP\Util::linkToRoute('gallery.images.uploadImages')); ?>" method="post" enctype="multipart/form-data" target="file_upload_target">
	<input type="hidden" name="id" value="">
	<input type="hidden" name="requesttoken" value="<?php p($_['requesttoken']) ?>">
	<input type="hidden" name="MAX_FILE_SIZE" value="<?php p($_['uploadMaxFilesize']) ?>" id="max_upload">
	<input type="hidden" class="max_human_file_size" value="(max <?php p($_['uploadMaxHumanFilesize']); ?>)">
	<input id="pinphoto_fileupload" type="file" accept="image/*" name="imagefile" />
</form>
```
and a js function like:
```
$('input#pinphoto_fileupload').fileupload({
		dataType : 'json',
		url : OC.generateUrl('routetoyourupload'),
		done : function(e, data) {
}
});
```
and php part as example:
```
       /**
	 * @NoAdminRequired
	 */
	public function uploadPhoto(){
		
		$file = $this->request->getUploadedFile('imagefile');
     ......
       }
```

and that's all, but i see more a problem if you work with caching the images in a js array, with every new uploaded file you have to generate it new!

**Comment by oparoz** [comment]
@libasys - Yes, we could do it that way, but we would probably missing lots of use cases covered by https://github.com/owncloud/core/blob/stable8/apps/files/js/file-upload.js

If it's not an exact match, users will reject it.

**Comment by libasys** [comment]
my 5 cents: I think you have to add to much js to get this feature running and slows the gallery app down!

**Comment by oparoz** [comment]
How will it slow it down (if drag and drop is not implemented)?

**Comment by libasys** [comment]
you have to add js libs on loading the gallery app

**Comment by oparoz** [comment]
Ah, but that's a problem all apps are going to have anyway, since there is no library sharing allowed and since RequireJS is not used.

I agree that it can be a problem to add a large lib to try and solve a problem which only affects a few users, but apparently this is at the top of the list of the most wanted features, so unless the lib is 500k, I think it will be acceptable.

**Comment by libasys** [comment]
this 3 js files needed:
```
OCP\Util::addscript('files', 'file-upload');
OCP\Util::addscript('files', 'jquery.iframe-transport');
OCP\Util::addscript('files', 'jquery.fileupload');
```
you can have a look at the files/ajax/upload.php file if you can use it, what the returning values are!

**Comment by oparoz** [comment]
My main problem is that file-upload is not on bower. It will be a maintenance nightmare to keep track of changes. That's why it needs to move to the public space or be turned in to a bower lib so that apps can use it.
Could this be a way forward @butonic?

**Comment by DeepDiver1975** [comment]
Please reopen in gallery(plus) repo is still valid - THX
