### ISSUE TITLE
Update items in shared calendar

### ISSUE THREAD

**Issue by phormanns** [owncloud/apps#825]
## environment

OwnCloud5, on Debian stable, Apache2, FastCGI, PostgreSQL

## pre-condition

User A shares a calendar users B and C. B and C get permission to create, update and delete.

User B created a new event in this shared calendar. The new event has public visibility.

## expected behaviour

User B is able to update or delete this event.

## actual behaviour

User B gets the error message "Fehlende oder ungültige Felder:", if he tries to update that event. 

User B gets the error message "Löschen fehlgeschlagen", if he tries to delete the event.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
