### ISSUE TITLE
Mozilla_sync and Firefox for Android

### ISSUE THREAD

**Issue by HiBit** [owncloud/apps#826]
Hello Everyone,

i'm running Owncloud: 5.0 and using the mozilla_sync app. I can sync various Firefox installations on differently Computers and everything ist working fine for me. 

But now i've tried to sync Firefox for Android 19.0.2 with my Owncloud but it doesnt work. 
I configure the Android client like all my other clients but at the final Screen where I have confirm my settings the wizzard just stop and didn't take an effect.

Does anyone know about this problem?

**Comment by apg1980** [comment]
Hello,

i am using sophos utm 9.3 webserver protection.
my owncloud server is published via a valid trusted ssl cert from startssl.com and is proxied to the internal http port 80 of the apache webserver (bitnami owncloud appliance).
i am unable to get the ff sync working. Desktop firefox is working.
Are there any known settings i have to check to get the sync working on my android ff devices?
Thanks for your reply.
