### ISSUE TITLE
Can one have a monthly repeating event on the last day of every month?

### ISSUE THREAD

**Issue by chrisisbd** [owncloud/apps#842]
This is probably an enhancement as I don't think it's possible at the moment.

Can one set an event to happen every month on the last day of the month?  It's a common requirement as things like VAT returns are often due on the last day of the month.

It could simply be done by setting a repeating event to start on 31st of a month which has 31 days and repeating monthly.  Owncloud would then put the event on the highest numbered day it could find in each month.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
