### ISSUE TITLE
'OC_Search_Lucene' not found at /var/www/lib/backgroundjob/worker.php

### ISSUE THREAD

**Issue by danielsan1** [owncloud/apps#847]
Hi all,

I found this ongoing error after a fresh OC 5.0 (with database import) installation in the logs:

call_user_func() expects parameter 1 to be a valid callback, class 'OC_Search_Lucene' not found at /var/www/lib/backgroundjob/worker.php#107

together with:

call_user_func() expects parameter 1 to be a valid callback, class 'OC_Search_Lucene_Indexer' not found at /var/www/lib/backgroundjob/worker.php#107

Otherwise everything works fine.

Any ideas about this issue?

(Ubuntu 12.04 64bit / php 5.3.10 / mysql+apache)

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the search_lucene repo
