### ISSUE TITLE
apps/files_texteditor/js/aceeditor/worker-javascript.js is non free

### ISSUE THREAD

**Issue by DavidPrevot** [owncloud/apps#867]
Hi,

As documented in the Debian bug tracking system[0], apps/files_texteditor/js/aceeditor/worker-javascript.js contains non free bits:
[…]
// -- dantman Daniel Friesen Copyright(C) 2010 XXX No License Specified
[…]
// -- dantman Daniel Friesen Copyright (C) 2010 XXX TODO License or CLA
[…]
// -- kossnocorp Sasha Koss XXX TODO License or CLA
// -- bryanforbes Bryan Forbes XXX TODO License or CLA
[…]
// -- iwyg XXX TODO License or CLA
[…]
// -- xavierm02 Montillet Xavier XXX TODO License or CLA
// -- Raynos Raynos XXX TODO License or CLA
[…]
// -- lexer Alexey Zakharov XXX TODO License or CLA
[…]
 *   The Software shall be used for Good, not Evil.

      0: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=692627

Thanks in advance for sorting it out

Regards

David

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the texteditor repo
