### ISSUE TITLE
Shared Calendar can not be downloaded

### ISSUE THREAD

**Issue by ulrich-hansen** [owncloud/apps#884]
User A shares a calendar with user B and gives him the permission to edit, change and update the calendar.

But user B can not download the calendar although the download-icon is present in the calendar properties. Instead, a click on the download icon leads to an empty page like:
https://subdomain.domain.tld/index.php/apps/calendar/export.php?calid=11

Suggestion: Either make the calendar downloadable for User B or don't show the download icon.

Test done with owncloud 5.0 on Debian Wheezy/Apache2
Here are some logs from the ownloud.log in the data directory:

"app":"PHP","message":"Undefined index: permissions at \/var\/www\/owncloud\/apps\/calendar\/lib\/calendar.php#82","level":2,"time":1364378450}
{"app":"PHP","message":"array_key_exists() expects parameter 2 to be array, boolean given at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#1032","level":2,"time":1364378450}
{"app":"PHP","message":"Trying to get property of non-object at \/var\/www\/owncloud\/apps\/calendar\/lib\/sabre\/object.php#50","level":2,"time":1364378450}
{"app":"PHP","message":"Undefined index: permissions at \/var\/www\/owncloud\/apps\/calendar\/lib\/calendar.php#82","level":2,"time":1364378450}
{"app":"PHP","message":"array_key_exists() expects parameter 2 to be array, boolean given at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#1032","level":2,"time":1364378450}
{"app":"PHP","message":"Trying to get property of non-object at \/var\/www\/owncloud\/apps\/calendar\/lib\/sabre\/object.php#50","level":2,"time":1364378450}

And these keep coming up:

{"app":"PHP","message":"array_key_exists() expects parameter 2 to be array, boolean given at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#1032","level":2,"time":1364378593}
{"app":"PHP","message":"array_key_exists() expects parameter 2 to be array, boolean given at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#1032","level":2,"time":1364378593}
{"app":"PHP","message":"array_key_exists() expects parameter 2 to be array, boolean given at \/var\/www\/owncloud\/apps\/calendar\/lib\/object.php#1032","level":2,"time":1364378593}

Hope this helps.

PS: I reopen this issue here, as owncloud/core was obviously the wrong place for this matter.

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
