### ISSUE TITLE
Picture App: Undefined offset for gallery.php

### ISSUE THREAD

**Issue by happysysadm** [owncloud/apps#923]
Windows 2012, IIS 8, OC5 installed from scratch. PHP 5.4.13. DB is mysql.

Enabled app: external storage support, added 1 drives as folders, granted to the OCadmin

I see no pictures in that folder and the issue I see in owncloud.log is:

+1 for Problem 3: {"app":"PHP","message":"Undefined offset: 1 at \/mnt\/www\/owncloud\/apps\/gallery\/ajax\/gallery.php#12","level":2,"time":1363368410

It is very similar to issue 739 (https://github.com/owncloud/apps/issues/739) but my problem is on Windows.

Regards
Manny

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the gallery repo
