### ISSUE TITLE
1 hour time shift when creating calendar events

### ISSUE THREAD

**Issue by nielosz** [owncloud/apps#926]
When creating an event by mouse click the new event starts one hour too late. Also all events are displayed about one hour too early. owncloud is version 5.0.0., owncloud's and php.ini's timezone are europe/berlin, 
 
![Bildschirmfoto vom 2013-04-02 10:40:04](https://f.cloud.github.com/assets/1521157/327353/0ac704b6-9b71-11e2-966c-3a49342d36a3.png)

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the calendar repo
