### ISSUE TITLE
[Calendar] HTML-Entity shown instead of char in "Read only iCalendar link(s)"-Block in settings

### ISSUE THREAD

**Issue by christianschmidt** [owncloud/apps#927]
As you can see in my screenshot, within the settings-popup in the calendar-app, special chars, e.g. german umlauts like "ä" "ö" etc. are displayed as HTML-Entities in the "Read only iCalendar link(s)"-block at the bottom while being shown correctly at the top in the "Your calendars:"-section.

Just a small issue that could be corrected easily i think. If this has already been noticed and mentioned here, nevermind, but i couln't find an corresponding issue filed here.

![oc-cal-entity](https://f.cloud.github.com/assets/1053922/327631/29ebf170-9b7c-11e2-834f-c8c3de14fbae.png)

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
