### ISSUE TITLE
owncloud 5.0.3 error after creating a new user

### ISSUE THREAD

**Issue by ghost** [owncloud/apps#960]
After creating another user i get the following logfile messages:

Warning	PHP	readdir() expects parameter 1 to be resource, boolean given at /is/htdocs/wp11126542_SC5WYNANI9/domain.tld/owncloud/lib/cache/file.php#88	06.04.2013 21:55

Warning	PHP	opendir(/is/htdocs/wp11126542_SC5WYNANI9/domain.tld/owncloud/data/name/cache/) [<a href='function.opendir'>function.opendir</a>]: failed to open dir: No such file or directory at /is/htdocs/wp11126542_SC5WYNANI9/domain.tld/owncloud/lib/files/storage/local.php#40

**Comment by icewind1991** [comment]
If this issue is still valid please reopen in the core repo
