### ISSUE TITLE
CalDAVAddCalendarQueueableOperation

### ISSUE THREAD

**Issue by Detmud** [owncloud/apps#966]
### Expected behaviour
It just works
Creating a new Calendar out of Calendar App 
MacOS X 10.8.3

### Actual behaviour
My owncloudserver response with a 501 when i try to create a new Calendar in calendar.app
CalDAVAddCalendarQueueableOperation

### Steps to reproduce
1. Add Owncloud caldav server
2. add a new calendar
3. ... See Error

### Server configuration
Operating system:

Web server: 

Database:
sqlite
PHP version:

ownCloud version:
5.0.3
### Client configuration
Browser:
NONE
Operating system:
Mac OS X 10.8.3
#### Web server error log
Nope

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"file_exists() expects parameter 1 to be a valid path, string given at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/core\/setup.php#22","level":2,"time":1365260295}
{"app":"PHP","message":"file_exists() expects parameter 1 to be a valid path, string given at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/core\/setup.php#22","level":2,"time":1365260296}
{"app":"PHP","message":"file_exists() expects parameter 1 to be a valid path, string given at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/core\/setup.php#22","level":2,"time":1365260311}
{"app":"PHP","message":"SQLite3Result::fetchArray(): The SQLite3Result object has not been correctly initialised at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/lib\/MDB2\/Driver\/sqlite3.php#942","level":2,"time":1365260316}
{"app":"PHP","message":"file_exists() expects parameter 1 to be a valid path, string given at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/core\/setup.php#22","level":2,"time":1365260317}
{"app":"PHP","message":"file_exists() expects parameter 1 to be a valid path, string given at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/core\/setup.php#22","level":2,"time":1365260318}
{"app":"PHP","message":"Trying to get property of non-object at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/apps\/calendar\/ajax\/event\/edit.form.php#27","level":2,"time":1365260548}
{"app":"PHP","message":"Only variables should be passed by reference at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/apps\/calendar\/templates\/part.share.php#53","level":2,"time":1365260548}
{"app":"PHP","message":"Undefined offset: 1 at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/lib\/connector\/sabre\/principal.php#49","level":2,"time":1365260625}
{"app":"search_lucene","message":"failed to extract meta information for \/Detmud\/files\/: Could not open \"\/var\/www\/virtual\/detmud\/owncloud.detmud.me\/data\/Detmud\/files\/\" (does not exist, or is not a file)","level":2,"time":1365262371}
{"app":"search_lucene","message":"failed to extract meta information for \/Detmud\/files\/: Could not open \"\/var\/www\/virtual\/detmud\/owncloud.detmud.me\/data\/Detmud\/files\/\" (does not exist, or is not a file)","level":2,"time":1365262372}
{"app":"search_lucene","message":"failed to extract meta information for \/Detmud\/files\/: Could not open \"\/var\/www\/virtual\/detmud\/owncloud.detmud.me\/data\/Detmud\/files\/\" (does not exist, or is not a file)","level":2,"time":1365262372}
{"app":"PHP","message":"Undefined offset: 1 at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/apps\/gallery\/ajax\/gallery.php#12","level":2,"time":1365409188}
{"app":"PHP","message":"Undefined offset: 1 at \/var\/www\/virtual\/detmud\/owncloud.detmud.me\/apps\/gallery\/ajax\/gallery.php#12","level":2,"time":1365411418}
 
#### Browser log
Nope

![Screen Shot 2013-04-08 at 11 28 49](https://f.cloud.github.com/assets/103764/350904/a9fea04c-a031-11e2-9ff5-f498520c47df.png)

**Comment by DeepDiver1975** [comment]
please open a new issue in https://github.com/owncloud/calendar/issues/ if still valid with the new calendar app which we deliver with oc9.
